### ISSUE TITLE
display dropped txs as "dropped" with a reason tooltip

### ISSUE THREAD

**Issue by rafaelcr** [hirosystems/explorer#1003]
When a tx has one of these status:
* `dropped_replace_by_fee`
* `dropped_replace_across_fork`
* `dropped_too_expensive`
* `dropped_stale_garbage_collect`

It would be great if the tx status was shown as "Dropped" but if there also was a tooltip on hover that displayed the reason why it was dropped in a friendly human-readable way

**Comment by 314159265359879** [comment]
should there be a `unminable_nonce_already_used`

https://github.com/hirosystems/stacks-blockchain-api/issues/1563
