### ISSUE TITLE
Scam contract report

### ISSUE THREAD

**Issue by TCP0001** [hirosystems/explorer#1006]
The below contract is a scam copy of Mad Ape Tournament minted Oct/Now 2021
SPKC7G5W7VDBR65QV1CDP4DWMN8C5VWNQX429RFQ.ordinals-warriors-apes

For instance ordinals-warriors-apes/9 is the copy of https://opensea.io/assets/ethereum/0xECE4775B96c207CEF81e054A3c607e9326d19d42/30 minted on October 30, 2021

Please flag or take other action
Thanks

**Comment by andresgalante** [comment]
Thanks for this report, It seems like an impossible job to manually overview and flag contracts and I don't think there is an action we can take on the Explorer.

Have you seen other explorers doing similar things?

**Comment by TCP0001** [comment]
Thanks for your reply, I understand your point.
Getting a listing on gamma.io deleted was probably as much as I could push it for now.
Still, since I don't know much about explorers, I went all-in with authority to check if there were any way to flag obvious scam contracts detected. lol

To answer your question, I did not

**Comment by andresgalante** [comment]
An idea that we had in the past is to have a white list of contracts that we know we can flag as legitimate, but that'd be manual labor that we can't maintain at the moment. 

Anyway, thanks for the report, I'll keep this in mind
