### ISSUE TITLE
Summary is showing twice

### ISSUE THREAD

**Issue by 314159265359879** [hirosystems/explorer#1010]
Just the one at the top is enough, thank you ;-)

![image](https://user-images.githubusercontent.com/33360391/221350233-3022dcfa-aa3b-402d-86e5-99f48cfa1ee1.png)

**Comment by andresgalante** [comment]
@He1DAr this happens in all pending tx pages

**Comment by andresgalante** [comment]
I also found another page where we show more information than we should; let's tackle these together:

https://explorer.stacks.co/txid/SP2M0GDCMTZN0WDB8R8SNTH3DVVTKP6NV1HYSKWZT.reasonable-sapphire-sturgeon?chain=mainnet
