### ISSUE TITLE
I have still not received my stx

### ISSUE THREAD

**Issue by John90555** [hirosystems/explorer#1011]
I sent stx to my binance wallet, it’s been 12 hours and I’ve still not received it. This is the transaction ID
0x70ce19e27fe9b537aca69433172752f8ee2eaaf8ac3d4bd672833857852b6767.

**Comment by andresgalante** [comment]
This tx 0x70ce19e27fe9b537aca69433172752f8ee2eaaf8ac3d4bd672833857852b6767 is confirmed.

If there is an issue please contact Binance, or ask for help on Discord.
