### ISSUE TITLE
Address and transaction not found

### ISSUE THREAD

**Issue by whoabuddy** [hirosystems/explorer#1021]
**Describe the bug**

This started yesterday, while viewing transactions or addresses on the explorer, they occasionally time out with a generic message.

**To Reproduce**

No clear action to cause it, but in the screenshot it looks like CORS issues.

Refreshing fixes it sometimes, usually waiting a little while and trying again does too.

**Expected behavior**

There would be an error that indicates what the actual problem is, not just a fallback to the item not being found.

This is confusing when you want to know, for example, if an address or tx exists by looking it up on the explorer. Seeing "address not found" can be confusing if it's just a connection error between the explorer and API.

**Screenshots**

![Screenshot from 2023-02-28 04-48-11](https://user-images.githubusercontent.com/9038904/221847037-adfbdd08-c403-4f1b-b1c6-633f42e560f6.png)

![Screenshot from 2023-02-28 04-50-04](https://user-images.githubusercontent.com/9038904/221847045-16c2f4ab-ad47-471b-a043-a02e0f71b9da.png)

**Additional context**

Links from screenshot:

- https://explorer.stacks.co/address/SP2BHRM69D9ERMT59TA7SPSR5G42N0Z9XG6ZHFHG7?chain=mainnet
- https://explorer.stacks.co/txid/0xb6f38b25421d9023c474a8d19c2777d83617afa704123662616260ed848f7213?chain=mainnet

Edit: also happened trying to view a contract at the link below

- https://explorer.stacks.co/txid/SP1H1733V5MZ3SZ9XRW9FKYGEZT0JDGEB8Y634C7R.miamicoin-core-v2?chain=mainnet

**Comment by andresgalante** [comment]
Thanks for the report @whoabuddy

the path has been fixed
