### ISSUE TITLE
Failed to purchase BTC domain name, the domain name has not been successfully registered due to multiple deductions, please help to solve it

### ISSUE THREAD

**Issue by mrchenou** [hirosystems/explorer#1027]
**Describe the bug**
Failed to purchase BTC domain name, the domain name has not been successfully registered due to multiple deductions, please help to solve it

Transaction ID 0xf7343902ebb20b07eaa96a4c76deccbbefcc959aff9a96a85e02f6d3e4b3a11b      --Pre-order successful
                       0x1c623a451647de6e4c4456ec1ee08ce552c1625bd468f8eabdd73bcf3b20310e    --broadcast failed
Address SP3HHSJDCRBKH67HXHWF8GV7ASCCG4R0FBD5DG5MC
Block#  778929
Time stamp ‎2023-03-02 13:46

block information：

Pre-order successful
https://explorer.stacks.co/txid/f7343902ebb20b07eaa96a4c76deccbbefcc959aff9a96a85e02f6d3e4b3a11b?chain=mainnet

broadcast failed
https://explorer.stacks.co/txid/0x1c623a451647de6e4c4456ec1ee08ce552c1625bd468f8eabdd73bcf3b20310e?chain=mainnet
https://explorer.stacks.co/txid/1c623a451647de6e4c4456ec1ee08ce552c1625bd468f8eabdd73bcf3b20310e?chain=mainnet

how do i do it？

![20230302145258](https://user-images.githubusercontent.com/59752925/222353425-0ba8fc77-cc85-42f3-a080-d81a50303d63.png)

**Comment by andresgalante** [comment]
Hi @mrchenou this isn't an issue with the Explorer; please ask for support on Discord.
