### ISSUE TITLE
Show receipt time or age for mempool txs on transaction page

### ISSUE THREAD

**Issue by badonyx** [hirosystems/explorer#1030]
Receipt time is a useful alternative to block time for txs still in the mempool. 

Receipt age is currently exposed at https://explorer.stacks.co/transactions (Pending tab) but not on the transaction page where it would be more actionable for users examining their own transactions.

**Comment by andresgalante** [comment]
Hi, thanks for the report 🙏 

Are you suggesting adding the time stamp on the pending tx detail page? The list already has a time.

**Comment by harrybasra95** [comment]
Hey @andresgalante, Right now if we will open a transaction from the pending tab. In the transaction view page, there is no column that shows the time or age of the transaction. I think he might be referring to that.

![image](https://github.com/hirosystems/explorer/assets/20265606/eccffa8f-82ff-4ecd-b55b-2b7483a6cef9)

**Comment by andresgalante** [comment]
@harrybasra95 Thanks for helping me understand it! 🙏 

Would you like to take a stab at adding it? We can add a new row in the Summary list titled "Broadcasted" and the value is the time stamp.

what do you think?

**Comment by harrybasra95** [comment]
I think it will work, I'll create a PR for that.
@andresgalante
