### ISSUE TITLE
transaction can't be confirmed for hours now

### ISSUE THREAD

**Issue by DannyLeetw** [hirosystems/explorer#1034]
![Screenshot_20230305_082929_com huawei browser](https://user-images.githubusercontent.com/42167351/222935951-d38905ea-b98e-478d-9fd6-1b52b14320af.jpg)
![Screenshot_20230305_082942_com huawei browser](https://user-images.githubusercontent.com/42167351/222935955-02950585-16ae-4f29-bdce-928e71a42569.jpg)
![Screenshot_20230305_085012_com huawei browser](https://user-images.githubusercontent.com/42167351/222935956-a2da5616-17d7-488f-8740-47cc7ee1f32e.jpg)
![Screenshot_20230305_085934_com huawei browser](https://user-images.githubusercontent.com/42167351/222935957-d0976ca3-fefb-4cda-b58c-fd68ca1622f3.jpg)
**Describe the bug**

Transaction ID 0x49e687f1002ae5090a318cde291fb32c69fd1401cd2cf0c03de2b511bf6b29e6
Address SP2VCK8HGFXN790EA3B003DXQ3BT6B0A0CJAZY0HD
Block#  779356~779361
Time stamp

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots or consol.log to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem here:

**Comment by DannyLeetw** [comment]
transfer took more than 9 hours to be confirmed

**Comment by andresgalante** [comment]
Hi @DannyLeetw this isn't a bug in the Explorer. Please ask for help in Discord
