### ISSUE TITLE
Transaction filtering poison microblocks

### ISSUE THREAD

**Issue by obycode** [hirosystems/explorer#1041]
**Describe the bug**
I noticed that when filtering the list of transactions, poison micro block transactions show in the list no matter what filter selections are made.

**To Reproduce**
1. Go to https://explorer.stacks.co/transactions?chain=mainnet
2. Click on Filters and de-select all options
3. Click "Load more transactions" until you see a poison microblock

**Expected behavior**
We should be able to filter these out as well. Maybe we need an additional filter for them.

**Screenshots**
<img width="1243" alt="image" src="https://user-images.githubusercontent.com/1473715/223563733-fe659d98-85c4-4510-a390-3ba1158cb30a.png">

**Desktop (please complete the following information):**
 - OS: macOS 13.2.1
 - Browser: Chrome
 - Version: 110

**Comment by andresgalante** [comment]
After the refactor we are surfacing them. The solution here is to add another filer for poison microblocks.

**Comment by andresgalante** [comment]
Sure, if you can take this issue, that'd be fantastic! thanks!

**Comment by shamim-io** [comment]
@andresgalante added a PR. Kindly review it. Thanks!
