### ISSUE TITLE
Changing cities for the same function in the sandbox requires a page refresh

### ISSUE THREAD

**Issue by Tim-Butterfield** [hirosystems/explorer#1047]
Checking get-block-winner in the sandbox for MIA and NYC may return the same result.

1. Go to the sandbox for ccd006-citycoin-mining
https://explorer.stacks.co/sandbox/contract-call/SP8A9HZ3PKST0S42VM9523Z9NV42SZ026V4K39WH.ccd006-citycoin-mining?chain=mainnet
2. Click on the get-block-winner function
3. Enter valid city id and block height and check the result
4. Cancel out of the result and repeat the same call for the other city id with the same (or different) block height and get the same result
5. Doing a page refresh between calls will let the next call have the correct result.

The results for each call should be correct for the selected city id and block height without requiring a page refresh.

MacOS 3.2.1 (22D68)
Brave/Chromium 
[Version 1.49.120 Chromium: 111.0.5563.64 (Official Build) (arm64)](https://brave.com/latest/)

**Comment by friedger** [comment]
This is a general issue that applies to all function calls

**Comment by 2snEM6** [comment]
This seems like a minor issue but in my humble opinion it can cause a lot of frustration for devs or people that use the sandbox since functions return misleading "cached" (?) values
