### ISSUE TITLE
Transaction pending for 20 hours!

### ISSUE THREAD

**Issue by ShelterSwap** [hirosystems/explorer#1049]
**Describe the bug**
My transfer of STX has been pending for like 20 hours. Screen shot provided. 

Transaction ID: 0xf747156019bac463b28f956b655c18a8121f58d50077f304616994e19c77bce2
Address:
Block#  
Time stamp

[Screenshot 2023-03-14 at 10.45.24 AM PDF.pdf](https://github.com/hirosystems/explorer/files/10970014/Screenshot.2023-03-14.at.10.45.24.AM.PDF.pdf)

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots or consol.log to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem here:

**Comment by andresgalante** [comment]
Hi, this isn't an Explorer issue. Please ask for help in STX Discord
