### ISSUE TITLE
fetch FT metadata from new Token Metadata API

### ISSUE THREAD

**Issue by rafaelcr** [hirosystems/explorer#1051]
Could the Explorer start fetching FT metadata from the new Token Metadata API? This will fix the current issue caused by the 302 redirection we put in place in the Stacks API from the old endpoints to the new

We should add the metadata API as a configurable ENV var for devs who want to run their own instance.

You will be able to use a TS client once this PR is merged: https://github.com/hirosystems/token-metadata-api/pull/134

**Comment by andresgalante** [comment]
This one should be fix now, Thanks Rafa 🙏
