### ISSUE TITLE
Augmented Reality Tool

### ISSUE THREAD

**Issue by jakxbtc** [hirosystems/explorer#1065]
Hi guys,
In the past I created augmented reality (AR) stuff on the loopring network (eth L2) and the Devs integrated an AR tool to their loopring explorer. So I uploaded a normal file to get displayed at the marketplace and within the metadata there was a section where I could paste the CID of the AR file ( i uploaded both files to an IPFS first and bond them together in the metadata). When you open the loopring explorer with your mobile device it automatically reads the metadata and gets your 3D/AR model ready to use.. So you just need to press one button at the explorer to turn into mixed reality and be able to play with the NFT.
The model loopring used is called "model viewer". I spoke with Andy of your team and he liked the idea.
The model viewer is also here at github (but Im too dumb with dev-stuff unfortunately).

My team and me are working a collection of 444 unique NFT and we would love to be the first AR collection at stacks with your help in integrating a AR tool to the stacks explorer. I know a couple of other AR creators who are looking forward to it to finally join stacks.
Ill attach a link of an example from the loopring explorer (you should open it with your mobile device to get the button displayed) and also examples of our work.

Me and my team are looking forward to help you with integrating the tool in the near near future!
Kindly regards!

https://lexplorer.io/nfts/0xae4c80574a33357c661b0ec391387a6b1cc4ee78-0-0x1e84a3806578dee542f375479ceb51d55557d606-0xf5109293b2fefc859f9cfa81b3f4ae462e15a8477fa6efbf1cf12748e69946d4-10
![button](https://user-images.githubusercontent.com/128549622/226755439-15c622c7-f4c8-4323-93eb-de352709bea8.jpg)
![Degen Hyena Pack 421](https://user-images.githubusercontent.com/128549622/226755534-84b61c65-83a0-493f-b4f4-3dbb95154558.png)
![Degen Hyena Pack 387](https://user-images.githubusercontent.com/128549622/226755539-2f600042-a931-4132-b1e3-5ea55188eada.png)
![IMG_0608](https://user-images.githubusercontent.com/128549622/226755648-a563c826-8a7a-4444-8e40-d24935238357.jpg)

**Comment by kyranjamie** [comment]
I would use this all the time, +1

**Comment by jakxbtc** [comment]
> Hi @jakxbtc as I mentioned to you on Discord, even though this is cool, this is a considerable undertaking for a very use-case-specific feature. Would this be something that Gamma can implement?
> 
> @chresko Lets keep it in mind as we think of the roadmap.

I talked to gamma devs and they also don’t have time to integrate this tool. Super sad because lots of 3D artists are out there who would benefit from that tool. 
After Loopring integrated it super many 3D artists came and brought a new chapter to it, so it’s a huge benefit for all.
Would be awesome if you guys could consider it, because it would help us a lot with making decisions for our collection if we can stick to stacks or searching for other options

**Comment by andresgalante** [comment]
> Would be awesome if you guys could consider it, because it would help us a lot with making decisions for our upcoming collection

Please do not plan around the explorer supporting AR, unfortunately, we don't have the bandwidth to do it.
