### ISSUE TITLE
EXPLORER MIGRATION: "Page not found" message appears for transaction in the mempool on STAGE works Fine in PROD

### ISSUE THREAD

**Issue by timstackblock** [hirosystems/explorer#1067]
**Describe the bug**
Video of issue https://somup.com/c0e3Fdy7U2

While using the staging explorer and clicking into the below pending transactions on the transactions tab it brings up a "Page not found" error message 

(https://explorer.staging.blockstack.xyz/txid/0xa926f32f0d2d71de124e38a856a2c79bdc723bc7c47055f825fcd656c2a0e8c5?chain=testnet)

<img width="1487" alt="Screen Shot 2023-03-22 at 1 34 35 PM" src="https://user-images.githubusercontent.com/49165468/226996165-0c1c18fa-62be-42da-a77a-57d5cb487489.png">

But the same transaction on the PROD explorer loads as expected meaning something is broken on the staging explorer

https://explorer.stacks.co/txid/0xa926f32f0d2d71de124e38a856a2c79bdc723bc7c47055f825fcd656c2a0e8c5?chain=testnet

<img width="1477" alt="Screen Shot 2023-03-22 at 1 54 13 PM" src="https://user-images.githubusercontent.com/49165468/226996093-036a8e20-e001-4ab1-bc69-15752627507b.png">

**Comment by timstackblock** [comment]
Slack convo with @He1DAr @rafaelcr suggest that this is an API issue with the transaction not being present.

<img width="1491" alt="Screen Shot 2023-03-22 at 5 03 41 PM" src="https://user-images.githubusercontent.com/49165468/227262769-a1d93dad-1d28-47b6-b153-fc00c08aa276.png">

**Comment by andresgalante** [comment]
Thanks @rafaelcr
