### ISSUE TITLE
[Sandbox] replace contracts with new Stacks 2.1 contracts in list of suggested contracts

### ISSUE THREAD

**Issue by friedger** [hirosystems/explorer#1068]
**Describe the bug**
Currently, genesis contracts from Stacks 2.0 are suggested that are out dated or inactive

![image](https://user-images.githubusercontent.com/1449049/227122534-b9a4c32e-1cf1-476b-b0e5-849a2bcf2dfb.png)

**Expected behavior**
Show a list of new contracts like 
pox-2, cost-3, etc
maybe even BNSx contract

**Comment by 314159265359879** [comment]
+1 
I really like when these latest contracts are easy to reach via the sandbox.

**Comment by andresgalante** [comment]
@friedger Can you point us to the genesis block for Stacks 2.0, please?

**Comment by friedger** [comment]
666050 as defined in https://api.mainnet.hiro.so/v2/pox

**Comment by obycode** [comment]
Bumping this issue to be prepared to update to pox-3 with 2.4 activation.

**Comment by 314159265359879** [comment]
I believe this closed automatically. Lets reopen?
I see #1116 changed it to pox-2 so it still requires a change to point to pox-3 when 2.4 goes live.
