### ISSUE TITLE
STX transfer taking ALL DAY to confirm?

### ISSUE THREAD

**Issue by frankbadalamenti** [hirosystems/explorer#1077]
Hello, I sent this transaction earlier today from my ledger wallet (connected to Hiro desktop app) to my xverse wallet address (connected to xverse wallet extension), and it's literally taking all day to confirm.  Can you please help me troubleshoot what is going on with this simple token transfer?  Thanks.

https://explorer.stacks.co/txid/0x8b0446868f001442a06763379797473086022fdbaa4a202beababcdcfe546d6a?chain=mainnet

Regards,
Frank

**Comment by andresgalante** [comment]
Hi Frank, this isn't a bug in the Explorer, please ask for help in Discord.
