### ISSUE TITLE
Create a list of FT tokens

### ISSUE THREAD

**Issue by igorsyl** [hirosystems/explorer#1088]
- List all SIP-10 tokens and provide search capability and asset page.
- Search and filter transactions by memos.

Reference: https://etherscan.io/tokens

@saralab would love to link to Explorer's asset page for sBTC from https://sbtc.world.

cc @renashah

**Is your feature request related to a problem? Please describe.**
Assimilate this: https://etherscan.io/tokens

**Describe the solution you'd like**
Need to find FT token list.

**Describe alternatives you've considered**
Scan stacks-node sqlite db's.

**Additional context**
Critical for sBTC.

**Comment by igorsyl** [comment]
Today I can't point sBTC users to a token page. If there's no token page then we may have to build one in the sBTC Bridge app. cc @radicleart if you can do this? cc @andrerserrano

**Comment by andresgalante** [comment]
I'll ping @chresko for prioritization, we need discoverability for sBTC

**Comment by andresgalante** [comment]
@chresko @He1DAr I am bumping this up since I think it's an important feature to work on.

Maybe @andromeda995 can take a stab at designing it?

**Comment by andresgalante** [comment]
For the first iteration, we'll create a list of FTs that links to each FT contract page.

After that, we can improve each FT page with things like Holders, market information, etc.

**Comment by shamim-io** [comment]
By any chance you can assign this issue to me? @andresgalante @He1DAr . Also, I would request.. if you can provide the designs.

**Comment by andresgalante** [comment]
@andromeda995 can you help @shamim-io with designs for this?

@shamim-io if you feel more comfortable with smaller contributions, there are plenty marked as [`good first issue`](https://github.com/hirosystems/explorer/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) and are incredibly valuable for our users 🙏

**Comment by He1DAr** [comment]
Hi @igorsyl! Could you please provide some details regarding the search by memos feature and whether it's needed for sBTC?

**Comment by igorsyl** [comment]
> Hi @igorsyl! Could you please provide some details regarding the search by memos feature and whether it's needed for sBTC?

Hi! Although searching Stacks transfers by memo would be useful, I think a more relevant feature is to be able to search contract calls by argument value.

sBTC deposits and withdrawals are contract calls that include a bitcoin tx id as one of the arguments.
Given a bitcoin tx id I would want to search for the Stacks contract call transaction that is associated with the transaction id.

For example, checkout the selection here:

https://explorer.hiro.so/txid/0xda86ebe97e7dc598e61e46b5cbf7757a06cff1efb7541dc0e63975d3d3d7bd1c?chain=testnet

<img width="807" alt="image" src="https://github.com/hirosystems/explorer/assets/1248500/7fb9998d-81ce-438b-b710-e9472ad135cc">

**Comment by He1DAr** [comment]
@igorsyl Makes sense!
@zone117x Would it be possible to add search by argument value to `/extended/v1/search/`? It could also be a new endpoint.
