### ISSUE TITLE
The problem of not being able to transfer to the wallet after a transaction failure

### ISSUE THREAD

**Issue by SeongyeolYun** [hirosystems/explorer#1091]
I staked New York City Coin in 2022. It was marked as a success at the time.
I was waiting for it to be going well, and recently checked the Hiro Wallet.
But as a result, it was changed after 3 days due to staking failure?

Then, the New York City Coin I requested for staking must be in the wallet or can be transferred to the wallet by claiming it.
While this feature is not supported
New York City Coin went from V1 to V2
Then I have to change the staked New York City Coin V1 to V2 after sending it to my Hiro wallet.
The function to change to V2 seems to be in Hero Wallet.

It seems that V1 does not have the function itself to return the failed part of the transaction to my wallet.

https://explorer.hiro.so/txid/0xf5293dae0518685ced8fb76a89127f32306a7d8d357b507ddfff49ec41ba555a?chain=mainnet

Please let me know how to solve that problem. If not, this seems to be the problem.

**Comment by andresgalante** [comment]
This isn't a problem of the Explorer, please ask for help in Stacks Discord.
