### ISSUE TITLE
Explorer uses Stacks/Bitcoin logos and terms when in Subnets mode

### ISSUE THREAD

**Issue by jbencin** [hirosystems/explorer#1097]
**Describe the bug**
If you add a Subnet network to Explorer, and check the box that it is a Subnet, all logos and terms in Explorer still show Stacks as the network, and Bitcoin as the burnchain

**To Reproduce**
Run the explorer in Subnets mode

**Expected behavior**
- Change "Stacks" references -> "Subnets"
- Change "Bitcoin" references -> "Stacks"

**Screenshots**
![explorer-subnets](https://user-images.githubusercontent.com/4306391/233165936-c9997138-6e91-42c0-aefa-ff458e1567f7.png)

**Comment by andresgalante** [comment]
Thanks for the report. We are still improving our subnet experience

**Comment by andresgalante** [comment]
@shamim-io This is another one you could take if you are up to learning more about subnets.

Like STX blocks related to BTC blocks, subnet blocks are associated with STX blocks. Therefore the icon in subnet view should be STX instead of BTC

What do you think?

**Comment by shamim-io** [comment]
@andresgalante, I completely agree with you. 
I require two forms of assistance regarding this issue: 
1. Could you provide a recommendation for the subnet block icon? If there isn't any specific icon for subnet block, can i use the STX icon for both STX block and subnet blocks?

2. Can you share a URL that I can use to create a subnet network on my end? 
Thank you!

**Comment by andresgalante** [comment]
@eugeniadigon or @andromeda995, what do you think about Shamim's question first question? To me Stacks to Stacks icon makes sense. Do we have a subnet icon?

@He1DAr can you help with 2 please?

**Comment by andromeda995** [comment]
I don't think we should have a subnet icon unless we can create something custom that is not ambiguous.

I would use the "subnet" badge that is shown in the UI (screenshot above) for the network selector

**Comment by andresgalante** [comment]
@shamim-io there is information on how to set up a network here:

 https://docs.hiro.so/subnets/overview?_gl=1*1w78s48*_ga*MTE5NDkyNzIxMS4xNjcxNDY2MzQ2*_ga_NB2VBT0KY2*MTY4NzIyMzEwMC44Ni4xLjE2ODcyMjY5NTguMC4wLjA.

**Comment by andresgalante** [comment]
I'll close this issue and we'll bring it back if Subnets became relevant
