### ISSUE TITLE
Display dollar amount on Stacks tokens

### ISSUE THREAD

**Issue by nikola4888** [hirosystems/explorer#1101]
This is my first attempt at using github for suggestions so i'll keep it short and simple. Currently it's near impossble to add my holdings to my portfolio simply because if i were to do that i'd have to through every single transaction, look at what time it was made then i have to see at what price was the token at that time and then add that to my portfolio and as you can imagine it would take ages. Now my suggestion is to simply add dollar amount displayed on each and every transaction where the dollar amount is displayed at the correct time when the transaction was made. I've given an example of arbiscan showing just that. I've also added the file from ALEXLAB dex where it clearly shows how its impossible to be used for anything useful with regards to calculations. Thank you for reading and i'm open for discussion on the matter.
![Screenshot (459)](https://user-images.githubusercontent.com/128379649/233705130-c7bac04a-55de-4bd7-ac5a-9162901aeca8.png)
![Screenshot (460)](https://user-images.githubusercontent.com/128379649/233705136-55a8fbe9-bfba-42b3-9136-66481969d9dc.png)
![Screenshot (461)](https://user-images.githubusercontent.com/128379649/233705139-7843a639-d251-443a-ba8a-6766e70aa6e6.png)

**Comment by andresgalante** [comment]
Thanks for the suggestion. We'll look into it.

**Comment by shamim-io** [comment]
@andresgalante I would like to take up this issue. 
Since I am new to this repository... Can you please guide me on how do I start tackling this issue? Thanks in advance..

**Comment by He1DAr** [comment]
@shamim-io Thank you for looking into this! If you check the postconditions section in a tx, you'll see the STX value displayed (in this example, it's 335 STX). We can display the dollar value beside it using the component `StxPriceButton` which has the capability of displaying the value now as well as on day of tx. You can find this component in many places e.g. homepage 
<img width="570" alt="image" src="https://user-images.githubusercontent.com/97111756/236912937-0962705a-acb4-4ddf-b66e-ff2b27c7307e.png">

**Comment by shamim-io** [comment]
@He1DAr @andresgalante I have raised a PR. Kindly review it and give feedback. Thanks again!!
