### ISSUE TITLE
Save custom networks locally

### ISSUE THREAD

**Issue by hugocaillard** [hirosystems/explorer#1102]
**Is your feature request related to a problem? Please describe.**
When a network is added to the explorer (in my case, a subnet), it's not saved. I have to add it every time I open a new explorer window. 

**Describe the solution you'd like**
It would be nice to save the custom networks in local storage. 

**Additional context**
We Subnets incoming, end-users and developers will interact more and more with the subnet

**Comment by He1DAr** [comment]
Confirmed with @hugocaillard that it works now.
