### ISSUE TITLE
Component app-config.tsx can be optimized

### ISSUE THREAD

**Issue by shamim-io** [hirosystems/explorer#1108]
**Describe the bug**

Transaction ID 
Address 
Block#  
Time stamp

Component `app-config.tsx` can have following enhancements: 
1. Define interface for the component props to avoid using 'any' type.
2. Memoize the handleRouteChangeComplete function using useCallback to prevent unnecessary re-renders.
3. Add dependencies to the useEffect hooks to prevent unnecessary re-renders.
4. Remove console.log statements.
5. Improve the code readability by properly formatting the JSX code.

**Comment by shamim-io** [comment]
Can I take up the issue? @andresgalante

**Comment by andresgalante** [comment]
Yes, please!! a PR is very welcome! 🙏

**Comment by shamim-io** [comment]
@andresgalante I have raised a PR. Please check it and let me know if everything is okay. Thanks!

**Comment by andresgalante** [comment]
Thanks for the PR!  🎉 We'll review it today

**Comment by andresgalante** [comment]
I know this PR was closed. If you think you have a case for it and numbers to justify the performance improvement, we are happy to reconsider it.

Else please feel free to close the issue 🙏
