### ISSUE TITLE
Failed transaction

### ISSUE THREAD

**Issue by Siralfonso2015** [hirosystems/explorer#1117]
I have a failed transaction of 100 stx. It didn't deliver to the recipient's address and I wasn't refunded also. Kindly assist. 
![IMG_7177](https://user-images.githubusercontent.com/131431154/236915538-fc48aff6-d6e5-45ce-8fe2-f8196c6e2d73.png)

TransactionHash: 1c83b8bd7e2d444f16dc106eceb3649b759c343240f857b1342da7d1072f46d1

Sender address: SP2RJ2JGP8EA5ZCCV4DZGAFRMJTD4JZ8C84ZP1RWP

Recipient address: SP1P72Z3704VMT3DMHPP2CB8TGQWGDBHD3RPR9GZS

**Comment by andresgalante** [comment]
The tx was dropped https://explorer.hiro.so/txid/0x1c83b8bd7e2d444f16dc106eceb3649b759c343240f857b1342da7d1072f46d1?chain=mainnet

And it should be back to the sender. We'll add a feature to explain better why a tx failed soon
