### ISSUE TITLE
Can we have different icons for Filter transactions?

### ISSUE THREAD

**Issue by shamim-io** [hirosystems/explorer#1122]
**Describe the bug**
Currently we have similar icons for Coinbase, Poison-microblock and Token transfer in Filter Transaction. I think we can have different icons for each one of them. 

**To Reproduce**
1. Go to 'https://explorer.hiro.so/transactions?chain=mainnet'
2. Click on 'filters'

**Screenshots**
<img width="539" alt="Screenshot 2023-05-09 at 10 34 34 PM" src="https://github.com/hirosystems/explorer/assets/29030948/89ecff6e-9f7d-41f2-a841-0382f8209c7f">

**Comment by shamim-io** [comment]
##### If this enhancement is desired: 

I would like to take up the issue. 

Maintainers please suggest the icons that can be added here. 

Thanks!

**Comment by andresgalante** [comment]
@andromeda995 Can you suggest icons, please?

**Comment by andromeda995** [comment]
Yup I can work on this - I will post an update here for the Figma mocks once it's finished.

**Comment by shamim-io** [comment]
@andromeda995 Any update on this ?

**Comment by andromeda995** [comment]
<img width="660" alt="CleanShot 2023-06-14 at 18 15 12@2x" src="https://github.com/hirosystems/explorer/assets/128061836/f73d0d11-793d-4d1f-9c06-36bf42f848b0">

@shamim-io

**Comment by andromeda995** [comment]
https://www.figma.com/file/31q1g27k69z1yXb6r6vrRD/Explorer-(will-be-deprecated)?type=design&node-id=4978%3A24133&t=kVbFIQVQutk0iDOB-1

@shamim-io  please use these two icons at 16x16px to replace what we currently have for coinbase (on left) and poison microblock (on right)

**Comment by shamim-io** [comment]
@andromeda995 @andresgalante @He1DAr Added a PR of new icons addition. [Feature: Added transaction icons #1181]. Kindly review it. Thanks!

**Comment by andresgalante** [comment]
@shamim-io Thanks for another great PR! 🎉
