### ISSUE TITLE
StxPriceButton click gives 'NaN' on historical data

### ISSUE THREAD

**Issue by shamim-io** [hirosystems/explorer#1125]
**Describe the bug**
StxPriceButton click gives 'NaN' on historical data

**To Reproduce**
1. Go to 'https://explorer.hiro.so/transactions?chain=mainnet'
2. Click on 'STX Transfer transaction PriceButton'
3. It gives NaN on historical data

**Expected behavior**
It should give some numerical data

**Screenshots**
<img width="413" alt="Screenshot 2023-05-10 at 5 01 41 AM" src="https://github.com/hirosystems/explorer/assets/29030948/bef45607-e1bb-437c-81a6-bcc184bbe99c">

**Comment by shamim-io** [comment]
I wonder its happening due to some wrong API response of `useHistoricalStxPrice`.

**Comment by andresgalante** [comment]
This is a known issue, it happens because sometimes we hit the rate limit of Coingeeko's API. Do you have an idea of how are can improve it?

**Comment by shamim-io** [comment]
@andresgalante I understand! After reviewing the code, it appears that when Coingeeko's API limit is exceeded, it returns `undefined`. Instead of displaying `NaN`, I recommend showing the existing tooltip indicating that the status is not available. Something like:

1. "Apologies, but the current price of STX is unavailable. Please try again later."
2. "Oops! It seems that the STX price is temporarily unavailable. Please check back shortly."

What are your thoughts on these updates?

**Comment by andresgalante** [comment]
You are right, ay text is better than NaN. It can't be that long though since we don't have the space.

Here is a suggestion, what if when we get rate limited we just remove the component and show no $ at all?

**Comment by shamim-io** [comment]
@andresgalante I raised a PR for the same [ https://github.com/hirosystems/explorer/pull/1184 ]. Kindly review it. 

Enhancement details: 
When Coingecko's API limit is exceeded, it results in an undefined value. In such cases, if the historicalData is undefined, we refrain from displaying the historical data (USD value) on the frontend.
