### ISSUE TITLE
Custom token icons show in hiro wallet, but not show in explorer.

### ISSUE THREAD

**Issue by LaserEyesNFT** [hirosystems/explorer#1136]
Hi, the explorer doesn't show the token icons:
https://explorer.hiro.so/address/SP16KWQY6ZPXNYT43A4RKXBXMFT3V7ZMV5YYNR1CK?chain=mainnet
 
ORD
ORDI token(amount 100,000)
LASER token( amount 2100):
 
Please help. Thanks.

**Comment by andresgalante** [comment]
@He1DAr let's check if the token is following [SIP-10 metadata](https://github.com/stacksgov/sips/blob/main/sips/sip-010/sip-010-fungible-token-standard.md) and if it does, then we could show it on the Explorer
