### ISSUE TITLE
Result not showing correctly

### ISSUE THREAD

**Issue by obycode** [hirosystems/explorer#1138]
In [this transaction](https://explorer.hiro.so/txid/0xc0390b44c7b6c00e248318426b00ca11855f43a1f45c610568d49a111adbda8b?chain=testnet&api=https://api24.testnet.dev.hiro.so), the principal in the result is not shown:
<img width="553" alt="image" src="https://github.com/hirosystems/explorer/assets/1473715/49abc019-fcc4-41fd-a5fd-25bfc0cca076">

The result is:
```
(ok (tuple (stacker 'ST2CY5V39NHDPWSXMW9QDT3HC3GD6Q6XX4CFRK9AG) (total-locked u50000000000110)))
```

**Comment by shamim-io** [comment]
@obycode I am unable to reproduce the above error using the link you have provided above. It says `Internal server error`.

Would you kindly provide an another link, so that i can reproduce the error. 

Thanks!

**Comment by obycode** [comment]
This seems like another bug that this link causes an internal server error. If you first add a new network with the URL, https://api24.testnet.dev.hiro.so, then click that link, it should work.

**Comment by shamim-io** [comment]
@obycode I have raised a PR solving this issue. Kindly review it. Thanks!

**Comment by obycode** [comment]
Thanks for taking a look @shamim-io. I left a comment on the PR.

**Comment by shamim-io** [comment]
@obycode oh! My bad.. I understood it now. I will modify the PR. 
Can you please provide me a transaction id by which i can test the same. 

The above transaction id you have provided is showing as invalid.

**Comment by andresgalante** [comment]
Thanks @shamim-io ! 🎉 you are killing it!
