### ISSUE TITLE
Explorer dev Error: Illegal value for token color: #000

### ISSUE THREAD

**Issue by shamim-io** [hirosystems/explorer#1140]
**Describe the bug**
In development mode I encountered the `Error: Illegal value for token color: #000 ` many times.

This error message typically occurs when attempting to set a color value that is not supported or recognized by the system or software.

**Expected behavior**
In most cases, colors are represented using different color models such as RGB (Red, Green, Blue) or hexadecimal notation. In the case of hexadecimal notation, colors are represented by a six-digit code preceded by a hash symbol (#), such as #000000 for black.

**Screenshots**
<img width="759" alt="Screenshot 2023-05-17 at 1 35 59 AM" src="https://github.com/hirosystems/explorer/assets/29030948/666d707d-80f6-4d05-83e3-00480b7666f9">

**Comment by andresgalante** [comment]
@shamim-io Thanks for the fix! awesome work, as usual.

For next PR, you can use a [keyword that closes the issue automatically when merge](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests).

**Comment by shamim-io** [comment]
Thanks for guide. I will definitely refer to it next time.
