### ISSUE TITLE
SHNT coin disappears

### ISSUE THREAD

**Issue by BLUEGHOST1475** [hirosystems/explorer#1145]
**Describe the bug**

Transaction ID https://mempool.space/tx/f390376ba9f74a6061bfc2fd4b92789b72a3595d11848a2bd6823ddd155a98e9
Address bc1qjd6wv5vtqemuc9pjy2jzwylnyk5nefu3pjng3d
Block#  
Time stamp ‎2023-05-19 20:39

**To Reproduce**
I transferred SHNT coins from another wallet, but 3000 SHNT disappeared

**Expected behavior**

**Screenshots**
If applicable, add screenshots or consol.log to help explain your problem.
<img width="883" alt="image" src="https://github.com/hirosystems/explorer/assets/91274218/68f4b5fe-bb94-41ae-9178-30189e8a973f">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem here:

**Comment by andresgalante** [comment]
This doesn't seem to be a bug on the Explorer project, if it is please provide more details. thanks!
