### ISSUE TITLE
[Connect] Error during transaction request Error: Cannot recognize PayloadType: 6   

### ISSUE THREAD

**Issue by dartman10** [hirosystems/explorer#1151]
Encountering the following error when deploying a contract from my own app:
`[Connect] Error during transaction request Error: Cannot recognize PayloadType: 6  
`

The same error is reproducible in Explorer sandbox:

<img width="1254" alt="renPM" src="https://github.com/hirosystems/stacks.js/assets/34408740/f5abc021-37ee-46a2-8370-459a59fc9848">

Thanks!

**Comment by janniks** [comment]
I would update `connect` to latest, the new types are fairly recent

**Comment by andresgalante** [comment]
This issue will be closed by https://github.com/hirosystems/explorer/issues/1028

**Comment by chresko** [comment]
Bumping this to next iteration.

**Comment by andresgalante** [comment]
This should be solved
