### ISSUE TITLE
update URL in explorer about section

### ISSUE THREAD

**Issue by elenananana** [hirosystems/explorer#1152]
currently it says **[stacks.explorer.so** ](https://explorer.stacks.co/) - should be explorer.hiro.so

thanks!

**Comment by shamim-io** [comment]
@elenananana, could you please specify the exact location where you encountered the URL `stacks.explorer.so` ? If you are referring to the main website URL, it is `explorer.hiro.so` only. Thank you!

**Comment by andresgalante** [comment]
@elenananana Shamim is right, I just did a search on the codebase and there is no reference of `stacks.explorer.so` 

Where can we find it?

**Comment by abhinavk9757** [comment]
@andresgalante  
OP is pointing to the link that is added in the About section of this GitHub repository.
A maintainer can change it.

![image](https://github.com/hirosystems/explorer/assets/14936826/f1f5ce0c-6b5f-4094-9eef-db02c555e9e2)

**Comment by andresgalante** [comment]
Excellent! thanks for spotting it @abhinavk9757
