### ISSUE TITLE
Transactions not showing up on the explorer

### ISSUE THREAD

**Issue by bilalanees98** [hirosystems/explorer#1162]
**Describe the bug**
On the testnet a broadcasted transaction can be found on the API, however opening up that same transaction in the explorer returns a "Tx not found" error.

Transaction ID: 18a96a9c04601c842440a67063926593c9d1d7e218bc4bcca069511f28cb8d23
Explorer link: https://explorer.hiro.so/txid/18a96a9c04601c842440a67063926593c9d1d7e218bc4bcca069511f28cb8d23?chain=testnet 
API link: https://stacks-node-api.testnet.stacks.co/extended/v1/tx/0x18a96a9c04601c842440a67063926593c9d1d7e218bc4bcca069511f28cb8d23 

**To Reproduce**
1. Broadcast an name-update transaction from btc.us (testnet version: btc-website.tintashlabs.xyz)
2. After broadcast open up the explorer and search for the tx
4. Transaction is not found.

**Expected behavior**
The transaction should should show up as soon as it is broadcast.

**Screenshots**
![Screenshot 2023-06-12 at 5 04 44 PM](https://github.com/hirosystems/explorer/assets/62988673/ec43b06f-290e-453e-937b-7b123f6ae2fd)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome

**Comment by andresgalante** [comment]
@ayush117 yes, please! go for it 🚀

**Comment by ayush117** [comment]
@andresgalante  Can you please tell me and clarify that the issue needs to be fixed on blockchain-api-client SDK as we are getting error("error": "cannot find contract by ID ST000000000000000000002AMW42H.bns") from their and possibly the contract should be present and it shouldn't have thrown the error. 

Or we need to handle the error on explorer frontend and show the rest of the information. Like this in the screenshot.
![Screenshot (513)](https://github.com/hirosystems/explorer/assets/25580209/e478017c-f718-473b-adbf-c9544a882507)
By doing this, We won't be able to show the source code section.

**Comment by chresko** [comment]
@andresgalante Are we able to reproduce this issue?
