### ISSUE TITLE
Faucet

### ISSUE THREAD

**Issue by Padriansah091** [hirosystems/explorer#1170]
**Describe the bug**

Transaction ID 
Address 
Block#  
Time stamp

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots or consol.log to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem here:

**Comment by andresgalante** [comment]
We're seeing issues with faucet transactions stuck in pending and address balances displaying incorrect numbers.

We need to resync from Genesis to repopulate the missing data, including any other missing data that may not be immediately noticed today.  This is the best way to ensure the data is clean and consistent moving forward.

Unfortunately, this might take a couple of days. Please follow the updates here:

https://status.hiro.so/incidents/psgbfczfcc6c
