### ISSUE TITLE
Faucet

### ISSUE THREAD

**Issue by skurat042aa** [hirosystems/explorer#1179]
**Describe the bug**
Cant't recieve testnet tokens STX

Transaction ID  0x2b73492ba6b646f3b27b457b6883b518375b2eb9e75a161743da441c09b788c9
Address ST1JZSWBPS4FV8MVPN2GP36V61P25ZXQNNXRC2ZPQ
Block#  don't know
Time stamp can't see

**To Reproduce**
1. Go to 'https://explorer.hiro.so/sandbox/faucet?chain=testnet'
2. Click on 'request STX'
4. See error: nothing happens. Tried to download hiro wallet desktop, also can't get testnet tokens

**Expected behavior**
Thought testnet tokens will be recieved

**Screenshots**
If applicable, add screenshots or consol.log to help explain your problem.
![photo_2023-06-17_23-56-50](https://github.com/hirosystems/explorer/assets/102252873/4f35ca0c-0b0d-41c1-8a81-f9c8dc1bc2df)
![photo_2023-06-17_23-57-03](https://github.com/hirosystems/explorer/assets/102252873/fd981e05-39ef-427b-9322-a908847ff3a5)
![photo_2023-06-17_23-57-09](https://github.com/hirosystems/explorer/assets/102252873/7b115815-c982-498e-a474-6278bf26a875)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser google chrome
 - Version 114.0.5735.134

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem here:

**Comment by skurat042aa** [comment]
![image](https://github.com/hirosystems/explorer/assets/102252873/ff43008e-3002-4d19-9f87-9339151187f9)
This is what happens in couple of minutes, when i try to request tokens

**Comment by 314159265359879** [comment]
Thanks for reporting, I am seeing these issues too. @skurat042aa I send some testnet STX your way.

**Comment by skurat042aa** [comment]
[314159265359879](https://github.com/314159265359879), thanks, it came)
