### ISSUE TITLE
Faucet request fail

### ISSUE THREAD

**Issue by Johonkawa** [hirosystems/explorer#1180]
I requested for stx faucet but not completed the transaction 
Transaction id - 
0x6826f5ee4b2e263494198ee4de2a3c0a82229d45b9fa1519278fe6bf95e7e7b3
![Screenshot_2023-06-19-22-50-02-399_com kiwibrowser browser](https://github.com/hirosystems/explorer/assets/117196123/71c9cd57-a384-4fd6-b285-70e0971b6b86)

**Comment by andresgalante** [comment]
We're seeing issues with faucet transactions stuck in pending and address balances displaying incorrect numbers.

We need to resync from Genesis to repopulate the missing data, including any other missing data that may not be immediately noticed today.  This is the best way to ensure the data is clean and consistent moving forward.

Unfortunately, this might take a couple of days. Please follow the updates here:

https://status.hiro.so/incidents/psgbfczfcc6c
