### ISSUE TITLE
cant claim faucet

### ISSUE THREAD

**Issue by mehradharmi** [hirosystems/explorer#1185]
hello sir i am claiming faucet but this not show any faucet

**Comment by andresgalante** [comment]
We're seeing issues with faucet transactions stuck in pending and address balances displaying incorrect numbers.

We need to resync from Genesis to repopulate the missing data, including any other missing data that may not be immediately noticed today.  This is the best way to ensure the data is clean and consistent moving forward.

Unfortunately, this might take a couple of days. Please follow the updates here:

https://status.hiro.so/incidents/psgbfczfcc6c
