### ISSUE TITLE
The Export CSV btn is out of place

### ISSUE THREAD

**Issue by andresgalante** [hirosystems/explorer#1188]
The `Export as CSV` button on the address page is out of place. It should be a sibling of the filter action and be placed at the left of the filters. (For example https://explorer.hiro.so/address/SPQR489BFKKAQPNF3KRTAVVBJ404DWY42KRPHQQ0?chain=mainnet)

<img width="903" alt="Screenshot 2023-06-21 at 20 55 09" src="https://github.com/hirosystems/explorer/assets/1832037/30d93940-c056-43c6-a2b3-f5010f17950b">

Bonus points if since we are at it, we convert it from a span to a `<button>` so the HTML is semantic.

**Comment by Uzafar90** [comment]
I think if you wrap the buttons under one div and use flexbox with space-between then you can align it perfectly.

**Comment by andresgalante** [comment]
@Uzafar90 Cool! do you want to take a stab at sending a PR?

**Comment by Uzafar90** [comment]
Sure, I'm currently at work but I'll go ahead and fork it so I can work on it tonight.

**Comment by Uzafar90** [comment]
@andresgalante You can assign it to me.

**Comment by Uzafar90** [comment]
Hey @andresgalante, I would like to apologize for taking up your valuable time, but I noticed that you're utilizing Stack UI for your styling, which I'm not familiar with. Hopefully, there will be an opportunity for me to learn and contribute to it in the future.

**Comment by andresgalante** [comment]
@Uzafar90 don't worry and thanks for trying! 

For the record we are not using Stacks UI anymore, we moved to ChakraUI. This should be as simple as moving the component to be a sibling of the filter.

**Comment by yashhhguptaaa** [comment]
Hey @andresgalante Please can you assign me this. I understand the issue and would raise a PR.

**Comment by yashhhguptaaa** [comment]
<img width="1263" alt="Screenshot 2023-06-27 at 2 37 19 AM" src="https://github.com/hirosystems/explorer/assets/82795074/098154c4-71a5-4ee3-a0ba-4a71a44895e9">

@andresgalante I have actually done this locally. If you can just assign me, I will raise PR.

**Comment by andresgalante** [comment]
@yashhhguptaaa thanks for the offer. There is an open PR https://github.com/hirosystems/explorer/pull/1195

if you want, you can review it 🙏

**Comment by yashhhguptaaa** [comment]
> @yashhhguptaaa thanks for the offer. There is an open PR #1195
> 
> if you want, you can review it 🙏

Ohh, I thought it's an open issue since no one is assignee. Sure, I will review. Thanks for the offer 😃

**Comment by yashhhguptaaa** [comment]
Hey @andresgalante I just wanna make a request 🙏. Who so ever is working on an open issue. Can you mention him as an assignee. Because I have seen other Open issue as well which does not have assignee mentioned. So, it reduces the confusion for the other person.

**Comment by andresgalante** [comment]
@yashhhguptaaa will do, thank for calling it out
