### ISSUE TITLE
i cannot confirm my testnet requested since 3days now

### ISSUE THREAD

**Issue by Christianogbonnaya** [hirosystems/explorer#1192]
**Describe the bug**

Transaction ID 
Address 
Block#  
Time stamp

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots or consol.log to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem here:

**Comment by andresgalante** [comment]
Please check the testnet status here https://status.hiro.so/
