### ISSUE TITLE
Use the Incident title as the message to display on Explorer during degraded service

### ISSUE THREAD

**Issue by saralab** [hirosystems/explorer#1196]
Can we use the title of the Incident to display on the Explorer ? 
Incident says : "[Degraded Ordinals API Performance](https://status.hiro.so/incidents/t5vwnjb7thzl)" whilst the explorer shows "Partially Degraded Service"

**Comment by andresgalante** [comment]
We don't get the title from the status page API. We'll try to get it from the RSS feed

**Comment by andresgalante** [comment]
We should make the banner as close to this UI as possible https://www.figma.com/file/kSjh3IR55mWgo6F37Pl5Tc/Platform-Design-System?type=design&node-id=1127-22198&mode=design&t=QBMZiy2PjHiygp20-0
