### ISSUE TITLE
did not receive STX test tokens

### ISSUE THREAD

**Issue by bartews** [hirosystems/explorer#1197]
did not receive STX test tokens
tb1qzlg4r6evtwjlt7x0ky3lmrpfaw0zmz8luypsee
ST35CWV4BXGABQZSX9W9WJ7YV6PCJXZF8T4APGHBM

**Additional context**
Add any other context about the problem here: 
![11112](https://github.com/hirosystems/explorer/assets/136733719/c9d9dd7e-3330-4baa-970a-66525a2dfd5a)
![11111](https://github.com/hirosystems/explorer/assets/136733719/c5511000-eb22-4aef-aba7-f4914b97a5ea)

**Comment by andresgalante** [comment]
The faucet should be working, Can you please check again and reopen this issue if it isn't?
