### ISSUE TITLE
Missing Stx

### ISSUE THREAD

**Issue by jarvis6644** [hirosystems/explorer#1199]
I withdrawal some of my STX from blockchain to binance but they say 'sandbox Found a bug in the Stacks Blockchain?'
so could you please help me out.
This is the link.
https://explorer.hiro.so/txid/0x76ef4a39032324a3e082d2b01a1d86be976adde7ba2615bd9e1709ef8f2db80b?chain=mainnet

**Comment by jarvis6644** [comment]
please help me out

**Comment by andresgalante** [comment]
The transfer is confirmed, this is not a problem with the explorer. Please ask for help in the #support discord channel
