### ISSUE TITLE
Handle subnet burnchain blocks correctly

### ISSUE THREAD

**Issue by obycode** [hirosystems/explorer#1200]
**Describe the bug**

The burnchain for a subnet is the parent Stacks network, not Bitcoin, so we need some adjustments in the visualizations that show the subnet blocks' connection to the burnchain. Currently, it shows the correct block number, but shows a bitcoin icon and links to the bitcoin block.

**To Reproduce**
1. Go to https://explorer.hiro.so/?chain=testnet&subnet=https://api.subnets.testnet.dev.hiro.so
2. See bitcoin icons and links in the Recent Blocks section

**Expected behavior**
Perhaps the Stacks block should have a new icon for subnet blocks, then the burnchain block should have the Stacks icon and link to the Stacks block.

**Screenshots**
<img width="456" alt="image" src="https://github.com/hirosystems/explorer/assets/1473715/8555a3cb-923b-4d72-b335-c44de2e271b9">

**Comment by andresgalante** [comment]
@obycode is this duplicated from https://github.com/hirosystems/explorer/issues/1097 ?

**Comment by obycode** [comment]
Ah, yes it is! 🙏
