### ISSUE TITLE
Pending faucet request 

### ISSUE THREAD

**Issue by Graceruchi1** [hirosystems/explorer#1206]
It's an amazing project!
I tried sending in some faucet to the address below and it's been showing pending for 30mins now. Thanks

tb1qwgp4x4c90da5pk300ws9ut2clmuche35qnz5fz

**Comment by andresgalante** [comment]
Hi @Graceruchi1, this isn't an Explorer issue. You'll find help at the [#support Discord channel](https://discord.gg/SK3DxdsP).
