### ISSUE TITLE
Swap wstx to velar KO

### ISSUE THREAD

**Issue by cryptoroms64** [hirosystems/explorer#1219]
**Describe the bug**
Hi, I've tried many times to swap some wstx token (tesnet) to velar using https://app.velar.co/swap, but all my transactions failed. Could you please explain me why ??

Transaction ID 0x924dbde872d5afd4042d74536724facb92838f118424e2b75b7cac0a2f33d10b
Address ST1MC6G0H5EGCP43BBVJTAACBKPYVDNFNNHHEXH14
Block#  0x6ce67da90f9b0ad9777e71a1da9154ff49f10740b9b3a3d60bd2ea35d4c09179
Time stamp 

**To Reproduce**
1. Go to 'https://app.velar.co/swap'
2. Click on 'Swap'
3. Enter an amount of 'wstx'
4. Confirm transaction to swap token.

**Expected behavior**
I'm expecting that the transaction is successful after some minutes, but everytime it fails. 

**Desktop (please complete the following information):**
 - Browser chrome

![Capture1](https://github.com/hirosystems/explorer/assets/138517226/ef35c3dd-3308-44dc-a7d2-6b0e83967e35)
![Capture](https://github.com/hirosystems/explorer/assets/138517226/fc54e5a5-2d28-4172-9de2-08f637bd31d5)

**Comment by andresgalante** [comment]
This doesn't seem like an issue in the Expolorer, maybe you can ask help in Discord https://discord.gg/pw4kGYuK
