### ISSUE TITLE
STX Transfer

### ISSUE THREAD

**Issue by jonathanjwh** [hirosystems/explorer#1228]
Hello,
At 14:21:44 on 03/07/2023 I unknowingly made a transfer to a different address starting SP2. I would really appreciate someone to help me find where they've gone! My guess is this is something to do with the upgrade to Stacks 2.1...?
Cheers!

**Comment by andresgalante** [comment]
Hi @jonathanjwh this isn't an Explorer issue. Maybe you can contact the community in Discord https://discord.gg/pw4kGYuK

**Comment by jonathanjwh** [comment]
Apologies @andresgalante I'm grateful for the Discord link. Cheers
