### ISSUE TITLE
faucet 

### ISSUE THREAD

**Issue by Kizzy1** [hirosystems/explorer#1229]
the test token from the faucet cannot be gotten and this is why many have been unable to test the network 

Address: ST3AVQA73JT8H03F7Z0WK2MQ8N2K5SJ5DJE0DNM30

to get faucet 
one is expected to
1. Go to '... https://explorer.hiro.so/sandbox/faucet?chain=testnet
2. Click on 'connect wallet' 
3. Scroll down to 'request stx' 
4. the test token are expected to be in once wallet but for 2 days now,  test token (STX) haven't been received .

**Comment by andresgalante** [comment]
I can't reproduce the issue. Please check if you ate in the correct network and address on your wallet and re open the issue if needed
