### ISSUE TITLE
STX Token Transfer SENT which I did NOT do

### ISSUE THREAD

**Issue by STX-Stargem** [hirosystems/explorer#1234]
Here's the TRX id: 0x6829fa018ff0642fbc90255a8d3901e38f7f763c89c8fad629a2cbec01efaa63
Where did my tokens go? Why did that happen?
Please HELP! URGENT!

**Comment by STX-Stargem** [comment]
Sender address: SP2HEDH4SXP1A34M9KDY00PJEM6YP1QDMVD2BFYDH
Recipient address: SP2KW0M6MBSSAV1BFDKH56VFNZK73Z36C0N369K9M
Link: https://explorer.hiro.so/txid/0x6829fa018ff0642fbc90255a8d3901e38f7f763c89c8fad629a2cbec01efaa63?chain=mainnet

Where did my STX go? Is it still within STX / Hiro system or network? Please help clarify what happened.

**Comment by andresgalante** [comment]
This isn't an Explorer issue.

Please request community support on the #support channel in [Discord](https://discord.gg/FdhdMUrZ).
