### ISSUE TITLE
Holdings indicator in the address page is incosistent

### ISSUE THREAD

**Issue by andresgalante** [hirosystems/explorer#1235]
The holdings indicator in the summary panel is inconsistent with the holdings panel on the right

Here is an example:
https://explorer.hiro.so/address/SPTW196D2867VBY2CAH71G8MMGJ7QYDMT7MZPG7Q?chain=mainnet

It indicates that there are 2 tokens, but the holdings panel shows none.

<img width="1249" alt="image" src="https://github.com/hirosystems/explorer/assets/1832037/5e597ed8-09c9-4216-99c4-1b2fcb0bbe09">

**Comment by bharat2913** [comment]
Hey, @andresgalante 

I checked the issue and found that we're not showing holdings in the right Holding section if the token balance is Less than or equal to "0".


Here we are returning "null", if the token balance is "0"
![image](https://github.com/hirosystems/explorer/assets/67862382/8330b80b-aecd-43cc-9c54-ce0e4c12e3d1)



Now, either In the right Holding section we can show the tokens whose balance is "0", like the one I shared in attachment.
Or in the left we only show count for those no. of tokens whose balance is greater than "0".

What should we do?


![image](https://github.com/hirosystems/explorer/assets/67862382/efd02c96-6cc5-4cc4-a549-cebf44e03308)

**Comment by andresgalante** [comment]
@bharat2913 thanks for the follow up 🙏 

The one on the right is right :) Would you be able to send a PR making the correct the one on the left panel please?

**Comment by bharat2913** [comment]
Sure @andresgalante.

Just to confirm, On the left panel we only show count for those no. of tokens whose balance is greater than "0". Right?

**Comment by bharat2913** [comment]
@andresgalante I have opened a PR. Please review. Thanks!
