### ISSUE TITLE
Better Subnets support

### ISSUE THREAD

**Issue by hugocaillard** [hirosystems/explorer#1240]
Here some ideas to improve Subnets support (in addition to #1097)

- When adding a network, we probably don’t need the check box "This is a subnet" since this information can be obtained on the already called /v2/info endpoint if there is a property parent_network_id

- We might want a united way to pass networks to the URL, for example:
    - this work: 
    /txid/ST2P8G9R5DQGCSVAQ5YTZ2XGC7X1421W8NC6VB26A.parfait-nft?api=https://api.testnet.hiro.so/
    - this doesn't:
    /txid/ST2P8G9R5DQGCSVAQ5YTZ2XGC7X1421W8NC6VB26A.parfait-nft?api=https://api.subnets.testnet.hiro.so/

**Comment by andresgalante** [comment]
Thanks Hugo, lets close this one for now and reopen it if subnets became more relevant
