### ISSUE TITLE
why the amount is not transferred to POOL

### ISSUE THREAD

**Issue by anuragcse611** [hirosystems/explorer#1247]
**Describe the bug**

I have transferred the amount to the user but it is not received by the user..hence the txid is generated but showing nothing in the explorer...the txid is not showing in the explorer..please help..

Transaction ID  : 77c9e32cff44e3a36d80ac9619687b12184df0d00a7c5370a655439cfe374fa1
Address : SPW9J5KWAWS7QJ759KHTYM70S6TQHNB17GWCWY9N
Block#  
Time stamp : 20 Jul 2023 10:18:38

**To Reproduce**

**Expected behavior**

the expectation is that the pool transferred the amount to user and after that the amount will again transferred to POOL account..but the pool is able to transferred and user received it..but user cannot transferred the amount to pool ..but the txid is generated which is not showing in the explorer

**Screenshots**
If applicable, add screenshots or consol.log to help explain your problem.
![image](https://github.com/hirosystems/explorer/assets/57407428/30c1a86e-d165-43a3-a05f-18207cd2fd7a)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem here:

**Comment by chresko** [comment]
Is this an Explorer issue or stacking pool issue?

**Comment by andresgalante** [comment]
This isn't an Explorer issue.

Please ask for community support on the #support channel in [Discord](https://discord.gg/FdhdMUrZ).
