### ISSUE TITLE
Stuck tx

### ISSUE THREAD

**Issue by richie07777** [hirosystems/explorer#1278]
**Describe the bug**
I have a stuck transaction that has holistically been stuck for more than a day. I sent 5,465.00 stacks to a coinbase address yesterday and raised the fee 10x via hiro/leather to increase the speed of it. That increased tx stayed pending for ~23 hours and then I raised the tx by 5x. That raised tx is still stuck and has been stuck for 4 hours now. 

Explorer Link: https://explorer.hiro.so/txid/0x2f5d4176bc8341bac463db2b6cd8c7c36cb9fdf7e62b4de1cda243a1039cdc84?chain=mainnet)
Transaction ID: 0x2f5d4176bc8341bac463db2b6cd8c7c36cb9fdf7e62b4de1cda243a1039cdc84
Sending Address: SP1PFX6CZ516SBVB3NZXTZX2XCHRSHXK58X1P3VNH

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots or consol.log to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem here:

**Comment by andresgalante** [comment]
The tx has been dropped.
