### ISSUE TITLE
Introduce a block view that defines the relationship between STX and BTC blocks

### ISSUE THREAD

**Issue by andresgalante** [hirosystems/explorer#1291]
- ✨ group blocks by btc block (enhancement)
- ✨ show av block time in a btc block space of time (enhancement)
- Bare in mind that there might be hundreds of STX blocks per one BTC block

**Comment by eugeniadigon** [comment]
_For visibility:_

Here's the Recent blocks widget redesign, validated with Engineering
https://www.figma.com/file/31q1g27k69z1yXb6r6vrRD/Stacks-Explorer-Working-File?type=design&node-id=5260%3A8113&mode=design&t=g0JfThTCDkvarV9Y-1

This update introduces:

- Grouping by Bitcoin block toggle/view
- View by block height or by block
- "Update" new blocks banner when Live updates are toggled off
- Stacks blocks "threads" when Group by Bitcoin block is off
- UI/styles updates

-------------------------------------------------------------

I also translated these updates to the "Recent blocks" page: https://www.figma.com/file/31q1g27k69z1yXb6r6vrRD/Stacks-Explorer-Working-File?type=design&node-id=5397%3A31504&mode=design&t=g0JfThTCDkvarV9Y-1

And to the Blocks detail page: https://www.figma.com/file/31q1g27k69z1yXb6r6vrRD/Stacks-Explorer-Working-File?type=design&node-id=5396%3A30354&mode=design&t=g0JfThTCDkvarV9Y-1

We can review these designs at our next meeting, and once approved, I'll turn them into to-do's here

**Comment by andresgalante** [comment]
related to https://github.com/hirosystems/explorer/issues/1505

**Comment by andresgalante** [comment]
I'll close this issue, and we'll follow up on the last details here https://github.com/hirosystems/explorer/issues/1603
