### ISSUE TITLE
Downloading .csv for an address downloads incomplete data if history is <30 transactions

### ISSUE THREAD

**Issue by 314159265359879** [hirosystems/explorer#1292]
**Describe the bug**
The export as .csv function will download the last 30 entries per default. It will only include more if you click "Load more transactions" to reveal additional transactions. 

Any address will do to reproduce. 

![image](https://github.com/hirosystems/explorer/assets/33360391/d404ba4c-352e-4b90-8947-8dd7cefbe7ce)

![image](https://github.com/hirosystems/explorer/assets/33360391/9e7e318e-c3ae-4d27-be89-fbc405eb3877)

**To Reproduce**
1. Go to explorer.hiro.so
2. visit any address with more than 30 transactions for example: https://explorer.hiro.so/address/SP2YADQRAJ4468KEX4CYD4MQPF0S6QYFT5BRA22J0?chain=mainnet
3. click export as csv
4. view the csv and see only the last 30 transactions.

**Expected behaviour**
The expected behaviour is that users can specify the entries they want to include (for example by year for tax purposes) or to get the complete history of the address.

**Comment by 314159265359879** [comment]
Perhaps a filter option can be added here to display "Last years" history, or 2022 history etc (from date X - to date Y). for tax purposes:
![image](https://github.com/hirosystems/explorer/assets/33360391/03569137-077b-4e1d-8d46-b489f072d15f)

Users don't expect the csv export to only contain entries currently displayed on screen, rather that they get the complete history.

**Comment by andresgalante** [comment]
Adding filters is a good idea, To start with we should fix the issues with the download action: it has a bug where it can only download the tx that are shown on the page (30 tx) and it doesn't show FT tx. 

Until we fix it the workaround is using https://fatstx.github.io/transactions
