### ISSUE TITLE
Hard to find contracts deployed in the past

### ISSUE THREAD

**Issue by gmchung** [hirosystems/explorer#1294]
<img width="645" alt="스크린샷 2023-09-26 오후 3 22 49" src="https://github.com/hirosystems/explorer/assets/35640822/4f87fecf-32ee-4a5d-a7fb-78bf69450be4">

To find the history of contracts deployed in the past, we need to go to the address where the contract was deployed and continue to click 'Load more transactions' to load the transaction history.

<img width="637" alt="스크린샷 2023-09-26 오후 3 22 58" src="https://github.com/hirosystems/explorer/assets/35640822/df0a8709-848c-4ce6-ad75-220013766733">

And it needs to show the exact date and time the contract or transaction was created.

**Comment by 314159265359879** [comment]
@gmchung to see the exact date/time you can hover over the time when looking at the contract deployment, is that helpful?

see here:
![image](https://github.com/hirosystems/explorer/assets/33360391/9fa18b06-6b9c-468e-b0b7-2b40a7b4c952)

**Comment by andresgalante** [comment]
We are working on an improved search and filters.

I'll close this issue for now
