### ISSUE TITLE
Prep for the hackathon: running regtest locally

### ISSUE THREAD

**Issue by andresgalante** [hirosystems/explorer#1296]
We'd like the locally running stack-explorer to direct to the locally running regtest blockchain explorer instead of the default testnet blockchain explorer.

We've prepped the sBTC repo for the hackathon with a devnet, where within this `devenv` directory the hackers can spin up a docker compose file that launches a bunch of services. You can give it a look here: [link](https://github.com/stacks-network/sbtc/tree/main/devenv)

When we use the stacks explorer locally clicking on the bitcoin block number directs us to the default testnet blockchain explorer. We'd like it to connect to the explorer that shows the regtest bitcoin block. This would only be relevant when the stacks explorer is running locally so I'd think an environment variable or configuration for the container running stacks explorer would be sufficient.

There is a video of the issue here https://github.com/hirosystems/explorer/assets/1832037/78ad310b-0ce3-4bc3-bcc6-18f54f73d0bc

And an branch with an (unfinished fix) has been started here: https://github.com/EmbeddedAndroid/explorer/commits/cfg-btc-endpoint

**Comment by He1DAr** [comment]
We can customize the base BTC explorer URL (`https://mempool.space/block/`/`https://mempool.space/block/testnet`) using an environment variable. Additionally, we can introduce a new optional field when adding a custom network.

**Comment by He1DAr** [comment]
@EmbeddedAndroid here's the PR https://github.com/hirosystems/explorer/pull/1306, also deployed to dev https://explorer.dev.hiro.so/?chain=mainnet
Please let me know if you have any suggestions. I'm looking forward to your feedback!
