### ISSUE TITLE
unstaking Miami coins

### ISSUE THREAD

**Issue by come-on-down** [hirosystems/explorer#1304]
Im having extreme difficulties in retrieving my staked miami coins and their reward distribution. I staked them for six months, which has now elapsed. but I cannot figure out how they are to be returned to me. Can I be assisted possibly? I thank you in advance for all time and consideration given towards my situation.

**Comment by Elyalfa** [comment]
I keep getting this error while trying to claimed my NYC nd MIA coins to my XVERSE wallet.

"Notice
This transaction would have succeeded, but was rolled back by a supplied post-condition"

**Comment by come-on-down** [comment]
Thank you for your reply, I appreciate it very much. Can you explain a bit further? I still am unsuccessfully in recalling my coins. I cannot find any information on how to do this. Again I thank you for all your time and consideration 🙏Sent from my iPhoneOn Nov 22, 2023, at 10:39 AM, Ely Alfaro ***@***.***> wrote:﻿
I keep getting this error while trying to claimed my NYC nd MIA coins to my XVERSE wallet.
"Notice
This transaction would have succeeded, but was rolled back by a supplied post-condition"

**Comment by andresgalante** [comment]
This isn't an Explorer issue.

Please ask for community support on the #support channel in [Discord](https://discord.gg/FdhdMUrZ).
