### ISSUE TITLE
Title and icon missing in sandbox page

### ISSUE THREAD

**Issue by Safvan-tsy** [hirosystems/explorer#1307]
![Screenshot from 2023-10-15 19-10-25](https://github.com/hirosystems/explorer/assets/90437519/6b198dc9-934f-4c53-b85a-2574a6dc6c1f)
![Screenshot from 2023-10-15 19-10-17](https://github.com/hirosystems/explorer/assets/90437519/3b2f178a-3ca4-42b1-95ef-0616fa2c3c96)
![Screenshot from 2023-10-15 19-10-02](https://github.com/hirosystems/explorer/assets/90437519/d3037f40-38a7-4e8c-8cb7-751b2d7f8e19)
see the /sandbox page is missing the title and icon

**Comment by andresgalante** [comment]
This has been fixed https://explorer.hiro.so/sandbox/deploy?chain=mainnet

thanks for the report
