### ISSUE TITLE
Wrong memo/Tag

### ISSUE THREAD

**Issue by Andallyn** [hirosystems/explorer#1308]
I wanted to send 115.40044STX tokens to my binance wallet address but I sent the wrong tag/memo.

This is the Transaction ID - 0x41735df3b596d1f708c465cdb93df350a32a2257757ab190cea4013f2199dec1

**Comment by andresgalante** [comment]
This isn't an Explorer issue.

Please ask for community support on the #support channel in [Discord](https://discord.gg/FdhdMUrZ).
