### ISSUE TITLE
UI Updates

### ISSUE THREAD

**Issue by eugeniadigon** [hirosystems/explorer#1309]
A batch of UI updates for the Explorer
cc @andresgalante @He1DAr 

🔗 [Figma link](https://www.figma.com/file/31q1g27k69z1yXb6r6vrRD/Stacks-Explorer-Working-File?type=design&node-id=5260%3A5478&mode=design&t=KkdwcfsyeCkJzm3v-1)

**Header:**
- [x] Update background image. Add borders (top, left, right) and "unstick" it (leave static)
- [x] Update "Stacks Explorer" title font size
- [x] Update Stacks icon (attached)

**Nav bar:**
- [ ] Group Transactions, Blocks, Tokens under "Explore" dropdown. 
- [x] Update Network selector to new style, and change text so it shows current selected network

**Stats block:**
- [x] Update all font styles and BTC icon

**Recent transactions column:**
- [x] Add title
- [x] Update tabs style and "Filter" style
- [x] Add "Update transactions" feat
- [ ] Update STX current value tag style
- [ ] Update all font styles of the rows
- [ ] Move TX hash to be next to the time stamp, crop to 5...5 characters
- [ ] Update "View all recent transactions" button style

**Recent blocks column:**
- [ ] Update "Live view" text to "Live updates" and toggle/font style
- [x] Remove checkmark icon
- [ ] Remove microblocks legend
- [ ] Remove chevron arrow on the right
- [ ] Replace "an hr ago" for "1 hr ago" text
- [x] Update STX icon and block heights font styles
- [ ] Update "View all recent blocks" button style

**Footer:**
- [ ] Update link and text styles and spacing
- [ ] Add Newsletter box

![stacks-icon](https://github.com/hirosystems/explorer/assets/78865845/f3f944bf-7d04-40c8-9cb0-828f3e8a2973)

**Comment by eugeniadigon** [comment]
@max-crawford This update involves adding the newsletter box on the footer. Let us know if you need to assist in some way to connect marketing systems for this. Thanks!

**Comment by max-crawford** [comment]
@eugeniadigon The only thing I care about is making sure that we are able to track submissions on this form, so we are able to see how this form does and compare it to other newsletter captures we have on our website. Ideally, this should follow a similar nomenclature to what we have used for previous forms. Happy to get involved here as needed as soon as we are ready for it.

**Comment by eugeniadigon** [comment]
@He1DAr I revised these tasks, I'm leaving here some feedback:

**Header:**
- [ ] Background image: add borders (top, left, right) - Is it possible to add these borders or would it have negative implications?
<img width="1000" alt="Screenshot 2024-01-11 at 10 58 24" src="https://github.com/hirosystems/explorer/assets/78865845/b5e30ad9-655e-4811-ad08-fecea4a85b32">

----------------------
**Nav bar:**
Pending:
- [ ] Replace "Blockchain" with "Explore" and group Transactions, Blocks, Tokens under this dropdown.
- [ ] Tweak: This was my mistake - would it be possible to change the font style of Explore / Sandbox / Mainnet and Prices for: `font-size: var(--stacks-fontSizes-sm)` and `font-weight: var(--stacks-fontWeights-r)`

----------------------
**Stats block:**

- [ ] Title of each block should be in uppercase

<img width="1465" alt="Screenshot 2024-01-11 at 10 55 37" src="https://github.com/hirosystems/explorer/assets/78865845/6e8cd950-8b15-4e48-bde3-33f108dd6395">

----------------------
**Recent blocks:**

- [ ] Replace "live view" for "Live updates" and capitalize L
<img width="295" alt="Screenshot 2024-01-11 at 11 07 05" src="https://github.com/hirosystems/explorer/assets/78865845/b10beed3-7ebb-42b0-8dc3-e947e5c3ceb9">

- [ ] STX Icon: This one shouldn't have a border, please remove `border: var(--stacks-borders-1px)`
<img width="1564" alt="Group 6106" src="https://github.com/hirosystems/explorer/assets/78865845/15cc4064-40db-4002-b7bc-21c579375305">

----------------------
**Recent transactions:**

- [ ] Update transaction types icon. Related #1328 

<img width="886" alt="Screenshot 2024-01-11 at 11 12 25" src="https://github.com/hirosystems/explorer/assets/78865845/9107c7bb-2958-431e-a30c-8836a39b93ae">

- [ ] View all recent transactions / blocks button: Update button height and font weight

<img width="1008" alt="Screenshot 2024-01-11 at 11 13 47" src="https://github.com/hirosystems/explorer/assets/78865845/95d9e0e3-e6b0-4c4e-9424-68a95cdcf007">

----------------------
**Transaction row:**

- [ ] Move txid to the right column and truncate
- [ ] Move Fee details to left column and capitalize Fee
- [ ] Underline block hash on hover
- [ ] Replace "STX transfer" for "Token transfer" to standardize with Filter tx types
- [ ] Update price tag color and font-weight
<img width="963" alt="Frame 44345" src="https://github.com/hirosystems/explorer/assets/78865845/e115945e-ffdf-4129-8f7b-6e26758e4765">

- [ ] Move txid to the right column and truncate
- [ ] Update Contract call font style to differentiate from Function call
<img width="942" alt="Frame 44346" src="https://github.com/hirosystems/explorer/assets/78865845/0eaefd29-3500-4652-b666-35b3513506de">

- [ ] Bug: When tx failed, the second row appears misaligned

<img width="729" alt="Group 6106" src="https://github.com/hirosystems/explorer/assets/78865845/6f16bd08-647d-4eb1-bd2b-2c28bc95926b">

**Comment by eugeniadigon** [comment]
Just realised that the STX Icon on "Recent blocks" column, on dark mode, has a border - which should be removed 

<img width="700" alt="Screenshot 2024-01-25 at 11 48 51" src="https://github.com/hirosystems/explorer/assets/78865845/9b5a8bba-3413-44c1-b80e-079d92a2b603">

**Comment by andresgalante** [comment]
We can consider this one done with Nick's PR
