### ISSUE TITLE
`Something went wrong` error page

### ISSUE THREAD

**Issue by kyranjamie** [hirosystems/explorer#1310]
Looking into https://github.com/leather-wallet/extension/issues/4368, I'm running into occasional issues where the explorer shows this error when switching to testnet mode.

Looks like a combination of CORS issues, 429s and other failed requests. 

![image](https://github.com/hirosystems/explorer/assets/1618764/2eb42e5b-f69c-46c6-badd-342b200c289b)

**Comment by andresgalante** [comment]
This should be fixed
