### ISSUE TITLE
Visual bug "light mode", sponsored label not displayed

### ISSUE THREAD

**Issue by 314159265359879** [hirosystems/explorer#1317]
**Describe the bug**
"Sponsored" label on sponsored transactions is displayed with font in the background color which makes it invisible. There used to be a grey background for this text. 

Transaction ID https://explorer.hiro.so/txid/0xc2fc1c40ff4728bed552b6b3dbd051da0b0b75f5ac48d8ca9b325ee8d990faad?chain=mainnet

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://explorer.hiro.so/txid/0xc2fc1c40ff4728bed552b6b3dbd051da0b0b75f5ac48d8ca9b325ee8d990faad?chain=mainnet
2. "see" error:
![image](https://github.com/hirosystems/explorer/assets/33360391/a771b2bf-e1b7-4f00-a841-8c9c1cd16a85)

3. Select the fees line...
4. to see the "sponsored" label is hidden:
![image](https://github.com/hirosystems/explorer/assets/33360391/0ed86f97-5de9-436d-b258-97e438110267)

**Expected behavior**
It used to be displayed like this which was friendly to light- and dark-mode. 

[![image](https://github.com/hirosystems/explorer/assets/33360391/ed49a62d-05fd-4250-8fd6-3c73f76ac58c)
](https://github.com/hirosystems/explorer/issues/655)

Environment: Windows 11, Latest Chrome and Firefox.

**Comment by andresgalante** [comment]
Thanks for the report. Let's fix this one on the next release @He1DAr

**Comment by He1DAr** [comment]
Thank you for reporting this. It will be fixed in the upcoming release.
<img width="667" alt="image" src="https://github.com/hirosystems/explorer/assets/97111756/e574ee67-a516-43ea-aca9-5ccafb68439b">
<img width="680" alt="image" src="https://github.com/hirosystems/explorer/assets/97111756/48d6a644-bc1c-4d3f-8dd3-c26963dd5a1f">
