### ISSUE TITLE
Docker image fails to build

### ISSUE THREAD

**Issue by niwim** [hirosystems/explorer#1323]
**Describe the bug**
When running docker build the build fails

**To Reproduce**
1. Run ``docker build -t <image-name> .``
2. See error
```
18.63 .../node_modules/bufferutil install$ node-gyp-build
18.70 .../node_modules/bufferutil install: sh: node-gyp-build: not found
18.71  ELIFECYCLE  Command failed.
18.71 .../node_modules/utf-8-validate install$ node-gyp-build
------
Dockerfile:17
--------------------
  15 |     
  16 |     RUN npm install -g pnpm
  17 | >>> RUN pnpm i
  18 |     RUN pnpm build
  19 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c pnpm i" did not complete successfully: exit code: 1

```

**Expected behavior**
Expecting the image to build successfully.

**Comment by niwim** [comment]
This seems to be related to the 8.10.0 release of pnpm, specifying the version to 8.9.2 resolves the issue, will suggest solution in PR.

**Comment by andresgalante** [comment]
This should be fixed now, thanks!!
