### ISSUE TITLE
Filter transactions + tx types update

### ISSUE THREAD

**Issue by eugeniadigon** [hirosystems/explorer#1328]
**[🔗 Figma link](https://www.figma.com/file/31q1g27k69z1yXb6r6vrRD/Stacks-Explorer-Working-File?type=design&node-id=5416%3A36752&mode=design&t=xsBCPxCrSEYK5Ohj-1)**

**This update includes:**
- Update transaction type icons
- Adds sBTC-related transaction types: `mint`, `burn`, `tenure change`, `tenure extension`
- Deprecates poison-microblock transaction type
- Update filter drop-down
- Change "Filter" text for "Filters"
- Inverts filtering logic: now should work by selecting what to filter, instead of unselecting everything but the one to filter
- Adds number(s) of filters applied upon filtering (Related: https://github.com/hirosystems/explorer/issues/815)

**Preview:**
<img width="985" alt="Image" src="https://github.com/hirosystems/explorer/assets/78865845/68ca426c-0f69-40f0-99af-23990a67b8e0">
<img width="2095" alt="Image-1" src="https://github.com/hirosystems/explorer/assets/78865845/9e227492-86df-4f64-b256-e3648fade1d3">

**Comment by eugeniadigon** [comment]
Update: I added to the design file "Tenure change" for this sBTC new transaction type

**Comment by andresgalante** [comment]
@eugeniadigon we'll need to make some changes here: the `peg-in` and `peg-out` tx types are no longer being implemented

there will be:
- a new variant of coinbase tx `NakamotoCoinbase`, the api will just expose the new property(s) on the existing coinbase tx type to make things simple
- a new tx type `TenureChange` which is ready this [API PR](https://github.com/hirosystems/stacks-blockchain-api/pull/1753)
- a new tx type `TenureExtension` — not yet implemented

For the testnet readiness, we will need support for all these 3 tx types.

**Comment by eugeniadigon** [comment]
> @eugeniadigon we'll need to make some changes here: the `peg-in` and `peg-out` tx types are no longer being implemented
> 
> there will be:
> 
> * a new variant of coinbase tx `NakamotoCoinbase`, the api will just expose the new property(s) on the existing coinbase tx type to make things simple
> * a new tx type `TenureChange` which is ready this [API PR](https://github.com/hirosystems/stacks-blockchain-api/pull/1753)
> * a new tx type `TenureExtension` — not yet implemented
> 
> For the testnet readiness, we will need support for all these 3 tx types.

I edited the first message with these changes as to not create confusion. Design is also updated on Figma

**Comment by eugeniadigon** [comment]
@He1DAr The update is looking great! Only got some small feedback + a new tweak for the empty state, since I thought the text could be improved.

- The "Filter" button: Can you match the border radius from the design? And when the button is hover/active, the text should be in Slate 900 color.
- The Checkboxes: Can they be Purple 600 for light mode, and Purple 400 for dark mode?

<img width="562" alt="Screenshot 2024-01-11 at 09 42 42" src="https://github.com/hirosystems/explorer/assets/78865845/2ea45319-0fb4-466b-a7a6-f6ec18a2b8ca">

<img width="617" alt="Screenshot 2024-01-11 at 10 08 21" src="https://github.com/hirosystems/explorer/assets/78865845/7cf98505-eca7-400a-94d3-769947e78ff8">

------------------------

### Empty state:

Design: https://www.figma.com/file/31q1g27k69z1yXb6r6vrRD/Stacks-Explorer-Working-File?type=design&node-id=5998%3A1810&mode=design&t=fMkjzPuuKXh2M4rs-1

Preview:
<img width="832" alt="Empty state" src="https://github.com/hirosystems/explorer/assets/78865845/f2576493-b167-4578-bab1-86f9e89c06d4">

**Comment by andresgalante** [comment]
this one should be done

**Comment by eugeniadigon** [comment]
I left some feedback above which I think was not applied yet

**Comment by andresgalante** [comment]
Still to do the review in this comment:

https://github.com/hirosystems/explorer/issues/1328#issuecomment-1887167056
