### ISSUE TITLE
Display error boundaries around page sections

### ISSUE THREAD

**Issue by eugeniadigon** [hirosystems/explorer#1333]
Initial proposal from @He1DAr : 

> > 
> A proposal to implement error boundaries around page sections. This approach aims to contain errors within their closest boundary rather than allowing them to disrupt the entire page. An example (shown in the video) is for a case where blocks API requests fail (which affects one of the stats sections as well as the block list). We could also display a reset button to attempt to rerender the errored section (helpful in case of transient errors). Please share your thoughts and feedback.

https://github.com/hirosystems/explorer/assets/78865845/3b091e52-7ef5-4f5b-a9a2-7da85fae8a9f

UI adjustments can be seen here: [🔗 Figma link](https://www.figma.com/file/31q1g27k69z1yXb6r6vrRD/Stacks-Explorer-Working-File?type=design&node-id=5532%3A1332&mode=design&t=sPX4jXH6dN3x0YSs-1)

*Note: Keep the title of the section on the top bar so the user knows which data failed to load

<img width="1440" alt="Homepage" src="https://github.com/hirosystems/explorer/assets/78865845/f6d4b8be-b3eb-4b62-8df2-53411b825fdb">

**Comment by andresgalante** [comment]
@eugeniadigon For this component to be reused it'd be ideal if it's the exact same without changes in alignment. Can we keep it either aligned left or center?

**Comment by andresgalante** [comment]
I'll close it since it'll be improved on the new design
