### ISSUE TITLE
Replace generic error message in tx page with granular error messages

### ISSUE THREAD

**Issue by eugeniadigon** [hirosystems/explorer#1335]
Proposal by @He1DAr 
> planning to replace the generic error message in tx page with granular error messages (explorer currently displays the first message in all cases). Additionally, we can display the error status code (if it's an API error).

![image (1)](https://github.com/hirosystems/explorer/assets/78865845/2e21c2ac-248a-4f87-bbc9-13ef50e734c1)
![image (2)](https://github.com/hirosystems/explorer/assets/78865845/ac9762b6-8ffa-4ce5-a37f-5084a17cb094)
![image](https://github.com/hirosystems/explorer/assets/78865845/e9c5134e-bad9-43f8-8c4b-57ff1e2539f3)

------
### Revised design:
Figma: https://www.figma.com/file/31q1g27k69z1yXb6r6vrRD/Stacks-Explorer-Working-File?type=design&node-id=5572%3A1356&mode=design&t=3h7EgWEhblGlG4CX-1
<img width="1440" alt="400 Error" src="https://github.com/hirosystems/explorer/assets/78865845/23a7ae0b-894d-4ef4-9adb-b69fac2b7b39">
<img width="1441" alt="404 Error" src="https://github.com/hirosystems/explorer/assets/78865845/73c8f861-e679-4faa-9cb3-ffff23305008">
<img width="1441" alt="500 Error" src="https://github.com/hirosystems/explorer/assets/78865845/e24d11ae-81ec-445c-a7d2-7f4cc123e69c">

- Hide H1 from page
- Update error images and text styles
- Update buttons styles

**Comment by andresgalante** [comment]
@He1DAr Let's track this as a separate task. First the nextjs upgrade, and then UI changes.

**Comment by andresgalante** [comment]
I'll close it since it'll be improved on the new design
