### ISSUE TITLE
STx withdrawal from m blockchain wallet went to a random wallet

### ISSUE THREAD

**Issue by HP-O** [hirosystems/explorer#1347]
**Describe the bug**

STx withdrawal from blockchain wallet went to a random wallet

Transaction ID 0x06d5be1af744bc2a533458c93e42f728708454f5cdf89959222e7e6c60c45f91
Address SP2JC5XYNHZ7ZZQR174XE9C4NGXMTR81C2MSYFGRC
Block#  129,247
Time stamp 9:24:48 PM 11/20/2023

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots or consol.log to help explain your problem.

**Desktop (please complete the following information):**
 - OS: 

**Smartphone (please complete the following information):**
 - Device: iPhone 
 - Browser via blockchain app
 - Version 

**Additional context**
Add any other context about the problem here: tried to transfer STx from the airdrop to my wallet on an exchange instead it went to a random wallet with over $100k worth of stx.

**Comment by andresgalante** [comment]
This isn't an Explorer issue.

Please ask for community support on the #support channel in [Discord](https://discord.gg/FdhdMUrZ).
