### ISSUE TITLE
String arguments containing quotes are not displayed

### ISSUE THREAD

**Issue by friedger** [hirosystems/explorer#1350]
**Describe the bug**
String arguments containing quotes are not displayed on transaction page

Transaction ID : 0x709ba5bdf936302c9e7bd7aac6e4cf4a048eff3e00e2728a3fb5a27cecd8a9a5
Address : SP2GW18TVQR75W1VT53HYGBRGKFRV5BFYNAF5SS5J.Cerulean-Marketplace-v1
Block#  #130419 #819137

**To Reproduce**
1. Go to https://explorer.hiro.so/txid/0x709ba5bdf936302c9e7bd7aac6e4cf4a048eff3e00e2728a3fb5a27cecd8a9a5?chain=mainnet
2. Click on https://api.hiro.so/extended/v1/tx/0x709ba5bdf936302c9e7bd7aac6e4cf4a048eff3e00e2728a3fb5a27cecd8a9a5
3. compare the last arguments (satisfaction-vote)
4. See that they are shown differently

**Expected behavior**
Show satisfaction-vote also on the explorer page

**Screenshots**

![image](https://github.com/hirosystems/explorer/assets/1449049/0049aa30-400a-47c4-aaed-e6c9469fc100)
![image](https://github.com/hirosystems/explorer/assets/1449049/b76b766f-3e57-4431-8b0a-45aaffbab425)

**Comment by xyzerobtc** [comment]
Thanks @friedger for reporting. 
We also see that the service does not show in the explorer. 

<img width="1353" alt="image" src="https://github.com/hirosystems/explorer/assets/16929732/c5a3323b-2fc1-4b0a-9a87-a7ecbb6c6ab9">

**Comment by SushilBro** [comment]
Thanks @friedger for reporting.
We also see that the service "job-title" does not show in either testnet and mainnet explorer.

**Comment by xyzerobtc** [comment]
@andresgalante thank you for fixing and closing!
