### ISSUE TITLE
STX Transfer

### ISSUE THREAD

**Issue by bwedg** [hirosystems/explorer#1352]
**Describe the bug**
The STX transfer is stuck in mempool.
Transaction ID <img width="1600" alt="Screen Shot 2023-12-04 at 12 06 33 PM" src="https://github.com/hirosystems/explorer/assets/129986550/c5d4efcc-0b9f-4d88-8194-c4d96e408b6d">Address 
Block#  
Time stamp

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots or consol.log to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem here:

**Comment by bwedg** [comment]
Please reverse the transfer and deposit funds in Leather wallet

**Comment by andresgalante** [comment]
Hi, this isn't an Explorer issue, please ask for help in [Discord](https://discord.gg/5wSVM5vM)
