### ISSUE TITLE
Update Favicon

### ISSUE THREAD

**Issue by eugeniadigon** [hirosystems/explorer#1356]
The current one looks blurry/pixelated. Attaching updated favicon package

<img width="385" alt="Screenshot 2023-12-11 at 16 14 56" src="https://github.com/hirosystems/explorer/assets/78865845/00d01559-12cf-4a91-89c0-ad2ccfae6ea1">

[favicon_stacks_explorer.zip](https://github.com/hirosystems/explorer/files/13637433/favicon_stacks_explorer.zip)

**Comment by BLuEScioN** [comment]
@eugeniadigon these favicons are purple and not black. Can you update the zip file please?

**Comment by eugeniadigon** [comment]
> @eugeniadigon these favicons are purple and not black. Can you update the zip file please?

That's ok - I should've specified that the update also includes a color update.

For more context, in the Stacks brand, black is usually used for ecosystem/general applications. Purple for areas more specific to the currency and blockchain.
<img width="2000" alt="Logo" src="https://github.com/hirosystems/explorer/assets/78865845/f79a4e7d-e99d-4e9b-8f2c-4e7ca290a37b">

**Comment by BLuEScioN** [comment]
Ok. I am using the android-chrome-512x512.png for the highest clarity

There were a lot of favicons to choose from:
![image](https://github.com/hirosystems/explorer/assets/20312835/93fab862-e849-4e82-b36f-90d42c05a594)
