### ISSUE TITLE
For transaction event query, the data returned by the interface is inconsistent with the browser display

### ISSUE THREAD

**Issue by hanzhenlong1314** [hirosystems/explorer#1360]
**Describe the bug**

For transaction event query, the data returned by the interface is inconsistent with the browser display
https://explorer.hiro.so/txid/0x53d915fcf3668650fccb7009ac3c6cb04c77b991625cb47923dc4ec6467cec3d?chain=mainnet The number of display events is 38

![image](https://github.com/hirosystems/explorer/assets/25896081/ef165b84-2332-4b4a-9bba-65fa0fedff64)
curl --location --request GET 'https://stacks-node-api.mainnet.stacks.co/extended/v1/tx/0x53d915fcf3668650fccb7009ac3c6cb04c77b991625cb47923dc4ec6467cec3d' The interface returns only 20 pieces of data

![image](https://github.com/hirosystems/explorer/assets/25896081/c2257404-6c13-44db-a8b4-1327a686ff22)

**Comment by zone117x** [comment]
Hello, tx events are paginated. See the API docs for a usage: https://docs.hiro.so/api/get-list-of-details-for-transactions
