### ISSUE TITLE
Add Bitcoin block timing information to the explorer

### ISSUE THREAD

**Issue by cuevasm** [hirosystems/explorer#1361]
A common series of questions is driven by the fact that not everyone understands the link between Stacks and Bitcoin. To illustrate why, perhaps, a Stacks block hasn't come through in a while, I send folks to https://mempool.space/.

I think it'd be a better experience if folks could just see pertinent Bitcoin block timing information right in the Stacks explorer. This needs to be surfaced where people are looking , generally at a pending transaction or the main page. This will still be relevant in Nakamoto because while maybe there will be less waiting around for the Bitcoin block for Stacks transactions, the sBTC deposit and withdrawals are secured when the transactions are settled to Bitcoin, knowing about when that may happen will be very useful. Perhaps there is an API that makes this easy too: https://mempool.space/docs/api/rest

Anyway, it would prevent a lot of panic and if well designed, could visually teach/ illustrate the deep link to Bitcoin. Thanks!

**Comment by diwakergupta** [comment]
Explorer already shows this info on pending transactions, e.g. see https://explorer.hiro.so/txid/0xea084b135b0866b33d8709a6b4fbc20752967aba76fc191db591f0fc2c429ee8?chain=mainnet (if it confirms by the time you see this, just open any other pending transaction)

@cuevasm is this what you had in mind?

<img width="869" alt="Screenshot 2023-12-15 at 10 21 49 AM" src="https://github.com/hirosystems/explorer/assets/15990/b95544d1-cbf4-4a3f-a3ed-15cf6c2486a0">

**Comment by cuevasm** [comment]
I think something is needed in the main view of pending transactions, this is where people go looking for 'is the chain halted?!'. I think a UI tweak can make this a lot more obvious is needed, less my opinion and more that this is the most common thing I have to point out so I have to assume people are not getting or understanding the information as it's currently provided

**Comment by andresgalante** [comment]
Hi @cuevasm, we are working on a new block's view and we have plans for a better way to display tx status, which as you mention is one of the most important things to show on the Explorer.
