### ISSUE TITLE
MY FUNDS WAS NOT CREDITED

### ISSUE THREAD

**Issue by mutebitsu** [hirosystems/explorer#1373]
Dear sir.
my name is Muhammad,from Uganda, a month ago I made a transaction from blockchain through STX but it did mot reach my address I provided instead it wqs credited to adifferent address starts with SM.......HJY so what should I do to get my money back to the right address please?
Regards
Muhammad
Email: mutebimuhammad@yahoo.co.uk
![Screenshot_20231221-103514](https://github.com/hirosystems/explorer/assets/154045213/bc3211c4-68ea-4a00-a43c-639bbea49714)

**Comment by andresgalante** [comment]
Hi Muhammad, this is not an Explorer issue, please ask for support in Discord
