### ISSUE TITLE
Transaction taking more than 12 hours

### ISSUE THREAD

**Issue by Nandi-Space** [hirosystems/explorer#1374]
Hello Stacks Support,

I transferred 89 stacks from Stx wallet to Leather wallet but it has taken more than 12 hours and the transaction is still not completed yet.

Please have a look. Thank you.

https://explorer.hiro.so/txid/0x7a23bce7ded2135fa712574abfe700727ffa1dfccdbfdd4eb4ee1197d40efe2f?chain=mainnet

Transaction ID: 0x7a23bce7ded2135fa712574abfe700727ffa1dfccdbfdd4eb4ee1197d40efe2f

Thank you,
Narayan

**Comment by andresgalante** [comment]
The tx got canceled, this is not an Explorer issue, please ask for support on Discord 🙏 

Thanks!
