### ISSUE TITLE
It's been 4 days and my $stx haven't arrived yet

### ISSUE THREAD

**Issue by naivewolf96** [hirosystems/explorer#1377]
It's been 4 days and my $stx haven't arrived yet
Transaction ID 0xe61210cc45001ca4f969f7972fe63af2ecbc6bfb3499d4a16e022c5723b01bf7
Address SP2X8YA18YXYFV06HNR7ZT0RDG25932E3CSJYXB86
Memo
101987426
Block#822444 
Block#822445 
Block#822446
Time stamp  ‎
2023-12-23 03:30 
2023-12-23 03:41
2023-12-23 03:53

https://explorer.hiro.so/txid/0xe61210cc45001ca4f969f7972fe63af2ecbc6bfb3499d4a16e022c5723b01bf7?chain=mainnet

![Screenshot_3](https://github.com/hirosystems/explorer/assets/154635198/cf47b0c2-0d52-4223-a619-ad421c4a67ab)
![Screenshot_2](https://github.com/hirosystems/explorer/assets/154635198/761035b9-4b75-4581-820a-f25701ce52a7)

**Comment by andresgalante** [comment]
This is not an Explorer issue, please ask for help in [Discord](https://discord.gg/jHc23pyQ)
