### ISSUE TITLE
 pending

### ISSUE THREAD

**Issue by fddddddddddddddddddddddddd** [hirosystems/explorer#1378]
my transactions have been pending for 8 hours and are not going through adress :SPA20YD402217XZCCJTJ0RTENA3P4Z7WHSC1H6S1
can you helo me pls?

**Comment by marcusdepauli** [comment]
Fiz mint na rede https://stx20.com/Explore ao todo foram 27 ainda se encontra pendente já a mais de 48 hrs  no https://explorer.hiro.so/address/SP2NDDXWYJED6KT46KVXXJ3369H57RM9J35E89XAW?chain=mainnet . Executei uma anterior foram 24 hrs  deu tudo ok preciso de um auxilio por favor. grato!!!

**Comment by andresgalante** [comment]
This is not an Explorer issue, please ask for help in [Discord](https://discord.gg/jHc23pyQ)
