### ISSUE TITLE
tx memo mistake accidental touch 

### ISSUE THREAD

**Issue by cavebear34** [hirosystems/explorer#1379]
theres no bug that i found, i was trying to do an stx transaction and accidentally put the memo tag wrongly,1 number was wrong and i wonder if i still can recover those funds from the limbo they r in to the origin adress. here is the transaction id. thanks a bunch, thats sums it for me.
       0x4dba6178a599d36ac707ad7a597d3e73c3c0156b15913393d807e67bf915441c

**Comment by andresgalante** [comment]
Please ask for help in [Discord](https://discord.gg/jHc23pyQ)
