### ISSUE TITLE
please improve the speed of transaction times

### ISSUE THREAD

**Issue by bayuromdhoni** [hirosystems/explorer#1380]
**Describe the bug**

Transaction ID 0xc7770d4802303b9a9cc25bd4e84b4c3e47fac2d5a47bf60bcbbdfbc1410baa9b
Address SP24BY1AVMMZ4FFC6PMNHAV352C6B6T5QCENJ4HS0
Block#  
Time stamp 14 hrs ago

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots or consol.log to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following informatio
![stxrepport](https://github.com/hirosystems/explorer/assets/39779889/cff42f83-fef2-4a84-b971-59f9bfa6c09d)
n):**

**Additional context**
Add any other context about the problem here: 
I sent stx from the main wallet to my 2nd wallet pending 14 hours ago please help the team to improve the time speed.

I suggest improving transaction speed, during the bitcoin bullrun the bitcoin project will increase including stx so that investors are comfortable.

**Comment by andresgalante** [comment]
This is not an Explorer issue, please ask for help in [Discord](https://discord.gg/jHc23pyQ)
