### ISSUE TITLE
tx dropped stx

### ISSUE THREAD

**Issue by creatorul9** [hirosystems/explorer#1381]
**Describe the bug**

Transaction ID 0xa890390fe82eaab3a38f55d18401042aba84c032e23944bc9ed5b2d55aa2d16f
Address SP3XNJG9QZ3FWSM3CG5VT9PVJ97BG0W4PTWWTDGBE
Block#  
Time stamp
my tx is dropped but still pending in my wallet please help !

**Comment by andresgalante** [comment]
This is not an Explorer issue, please ask for help in [Discord](https://discord.gg/jHc23pyQ)
