### ISSUE TITLE
pending fund trasfer

### ISSUE THREAD

**Issue by Harshal9900** [hirosystems/explorer#1383]
**Describe the bug**

Transaction ID 0x21afdc6ca5ba6b2f7f338ea97bc99031d73d615054080ba9f692cbf89f0d9f69
Address SP3TQJ3VCWJHB60GVSPHRX4XVW9X4F9P8J9BYC2FR
Block#  822661
Time stamp

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots or consol.log to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem here:

**Comment by andresgalante** [comment]
This is not an Explorer issue, please ask for help in [Discord](https://discord.gg/jHc23pyQ)
