### ISSUE TITLE
 It's been 20 hours since I sent the STX, but TT

### ISSUE THREAD

**Issue by napool707** [hirosystems/explorer#1384]
**Describe the bug**

Transaction ID : 0x438916b28eec9e7029091621690daa75e766213df5b6c2158628bdee95005d73
Address : SPGVE109Z6QHEV5H3YJFSAKMNED78XSQVM2B6A3G
Block#  : 
Time stamp : 

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots or consol.log to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem here: 
Hello~ It's been 20 hours since I sent the STX, but it hasn't arrived. I need help. Time is running out. Please help me solve the problem. (email: barrri707@gmail.com)
![100](https://github.com/hirosystems/explorer/assets/151032448/e145d859-f038-44aa-8bb5-786ea219d7d8)
![101](https://github.com/hirosystems/explorer/assets/151032448/40d8ccb2-e63c-4084-8bf9-4926b7121e6e)

**Comment by napool707** [comment]
Add any other context about the problem here:
Hello~ It's been 20 hours since I sent the STX, but it hasn't arrived. I need help. Time is running out. Please help me solve the problem. (email: [barrri707@gmail.com](mailto:barrri707@gmail.com))

**Comment by andresgalante** [comment]
This is not an Explorer issue, please ask for help in [Discord](https://discord.gg/jHc23pyQ)
