### ISSUE TITLE
Já se passaram 48 horas desde que enviei o STX.

### ISSUE THREAD

**Issue by marcusdepauli** [hirosystems/explorer#1386]
*Descreva o bug**
Uma descrição clara e concisa do que é o bug.

ID da transação 0x75988d87f2830a96f7d310439bf85b2fb90827ca706e39c70200bb886cc778b3
Endereço SP2NDDXWYJED6KT46KVXXJ3369H57RM9J35E89XAW
Bloquear#
Carimbo de hora

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Vá para '...'
2. Clique em '....'
3. Role para baixo até '....'
4. Veja o erro

**Comportamento esperado**
Uma descrição clara e concisa do que você esperava que acontecesse.

**Capturas de tela**
Se aplicável, adicione capturas de tela ou console.log para ajudar a explicar seu problema.

**Desktop (preencha as seguintes informações):**
  - SO: [por ex. iOS]
  - Navegador [por ex. cromo, safári]
  - Versão [por ex. 22]

**Smartphone (preencha as seguintes informações):**
  - Dispositivo: [por ex. iPhone6]
  - SO: [por ex. iOS8.1]
  - Navegador [por ex. navegador de ações, safari]
  - Versão [por ex. 22]

**Contexto adicional**
Adicione qualquer outro contexto sobre o problema aqui:
Adicione qualquer outro contexto sobre o problema aqui:
Olá~ Já se passaram 48 horas desde que enviei o STX, mas ele ainda não chegou. Eu preciso de ajuda. O tempo está se esgotando. Por favor me ajude a resolver o problema. (e-mail: [depauli36@gmail.com](mailto:depauli36@gmail.com)
OBS: TENHO MAIS 26 TRANSAÇÕES PENDENTES COMO ESTA

**Comment by andresgalante** [comment]
Hi, your tx has been canceled https://explorer.hiro.so/txid/0x75988d87f2830a96f7d310439bf85b2fb90827ca706e39c70200bb886cc778b3?chain=mainnet

This is not an Explorer issue, please ask for help in Discord
