### ISSUE TITLE
The STX transfer is stuck in mempool. Transaction ID 0x190c0ad309f75fa86887d6ac3104fe469f1b9eda8d6a093b67234bd1b2c06cf4

### ISSUE THREAD

**Issue by mellowmeli** [hirosystems/explorer#1389]
**Describe the bug**

Transaction ID: 0x190c0ad309f75fa86887d6ac3104fe469f1b9eda8d6a093b67234bd1b2c06cf4
Address 
Block#  
Time stamp

**To Reproduce**

**Expected behavior**
This should be deposited as expected or returned to sender.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac OS 14
 - Chrome

**Smartphone (please complete the following information):**
 - Device:Iphone 15
 - Browser  chrome

**Additional context**
Withdrew STX from my Ledger to Kucoin exchange for deposit on 12/26/23 and it still has not been deposited.

**Comment by andresgalante** [comment]
Hi, this isn't an Explorer issue, please ask for help in [Discord](https://discord.gg/5wSVM5vM)
