### ISSUE TITLE
我转了100个stx失败了，钱为什么没有原路返回给我，我的钱呢？？

### ISSUE THREAD

**Issue by huchao1997** [hirosystems/explorer#1392]
交易ID
0x6292115215acdd93e052aff0990a4966c0d599ce2bf2b9bc7b073a46a5227080
区块哈希
[0x16b563a0ba1ba34e959845c4ce42edeb13dbf647404223c419cf998dff164772
![544554](https://github.com/hirosystems/explorer/assets/84821670/24cc6e68-7203-4520-bca2-e02904c5cceb)
![4543](https://github.com/hirosystems/explorer/assets/84821670/901ac93a-2976-4618-9be6-7a7c12d2a33e)

**Comment by andresgalante** [comment]
Hi, this isn't an Explorer issue, please ask for help in [Discord](https://discord.gg/5wSVM5vM)
