### ISSUE TITLE
I transferred 100 STX tokens to pledge. The pledge failed and the tokens were not returned to me. Please return the tokens to me. Thank you.

### ISSUE THREAD

**Issue by huchao1997** [hirosystems/explorer#1393]
交易ID
0x10bdcf10ffee72994f493ac36760f4e95a76c8471370182fd4705c2153dc173d
区块哈希
[0x16b563a0ba1ba34e959845c4ce42edeb13dbf647404223c419cf998dff164772
![544554](https://github.com/hirosystems/explorer/assets/84821670/5fb9c26a-623b-49df-8dab-252b64558f0d)
![Uploading 4543.png…]()

**Comment by andresgalante** [comment]
Hi, this isn't an Explorer issue, please ask for help in [Discord](https://discord.gg/5wSVM5vM)
