### ISSUE TITLE
Dark mode flips

### ISSUE THREAD

**Issue by andresgalante** [hirosystems/explorer#1394]
I see a bug with dark mode. To reproduce it:

Go to any page
change to dark mode
Go back to the homepage by clicking on the stx icon
It goes back to light mode.

The same happens when it's the other way around

**Comment by Aman-zishan** [comment]
> I see a bug with dark mode. To reproduce it:
> 
> Go to any page change to dark mode Go back to the homepage by clicking on the stx icon It goes back to light mode.
> 
> The same happens when it's the other way around

I experienced the same bug while building a project on stacks so i thought i'll try to contribute but when i clone and run the project seems like the state is being persistent , not able to reproduce the bug

**Comment by andresgalante** [comment]
@Aman-zishan thanks for the help, what do you mean by "building a project on stacks"

**Comment by andresgalante** [comment]
@Aman-zishan we fixed the dark mode state last Friday, thanks again for the help. There are issues you can pick from the backlog if you want to contribute
