### ISSUE TITLE
Dropped

### ISSUE THREAD

**Issue by vlamidza** [hirosystems/explorer#1407]
Hi, I didnt receive stx tokens from binance, the explorer said its droped, shoud i except them to be returned to the binance wallet or not? thanks

Transaction ID 0x84d4c40c0c27cb6bebaa1877b8cd0edeed5bf0474146c750e172367bff2d690f
Address SP9DD7VWH9VVKA7CM077DRNPNQK9DNQXYZGCY3WB
Block#  
Time stamp 19:33:43 06/01/2024

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots or consol.log to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem here:

**Comment by andresgalante** [comment]
This isn't an Explorer issue.

Please ask for community support on the #support channel in [Discord](https://discord.gg/FdhdMUrZ).
