### ISSUE TITLE
BTC earned breakdown from STX stacked

### ISSUE THREAD

**Issue by thezilverfox** [hirosystems/explorer#1409]
Hi there,

The BTC wallet address that was used for the below contract and tran ID has not received all the BTC. Can you please send a breakdown of the BTC that should have been received for my stacked STX?

Contract
SP000000000000000000002Q6VF78.pox-3

Tran ID
0x296064d8755444040c107cb0c5de582569f46fedaa3fa66b2e7f67d9ed260716

Blockhash
0xd442968758f7cf09927223bfcc86585adea0bd847f9438972ee2e8f33aa07d7f

thank you

**Comment by andresgalante** [comment]
This isn't an Explorer bug, please ask for help on [Discord](https://discord.gg/epxhBABW)
