### ISSUE TITLE
Sending

### ISSUE THREAD

**Issue by Alfonova-Node** [hirosystems/explorer#1410]
**Describe the bug**

Transaction ID 0xa0ee24b37c2ea128ee1c35ddc13db5ab1f46a437569da32528986ed41fa77385
Address SP30CACVWQWZ03W11WQJK3PVNM1PAPC36VZWM36AR
Block#  
Time stamp

**Comment by andresgalante** [comment]
This isn't an Explorer bug, please ask for help on [Discord](https://discord.gg/epxhBABW)
