### ISSUE TITLE
[URGENT]. Transfer of STX stuck in pending for nearly 9 hours

### ISSUE THREAD

**Issue by jeffkaplan88** [hirosystems/explorer#1412]
Unlike prior recent transfers of STX from my Stacks Wallet 2.0 to my Coinbase account, today there seems to be a problem.  My transaction has been pending for over 8 hours - which seems like something might be wrong.  Is there some error that can be seen?

Transaction ID:
0x790249a2e7e7ca181ea52d2a23cca98b1fdf8f5301f2ea89daefd7efa376141c

Here is the link on the Stacks Explorer:
https://explorer.hiro.so/txid/0x790249a2e7e7ca181ea52d2a23cca98b1fdf8f5301f2ea89daefd7efa376141c?chain=mainnet

Can someone please urgently check if there is some problem?  This is a rather important transaction to complete.

Let me know what further info is required.

Thanks,
Jeff
email:  jeffkaplan88@gmail.com

**Comment by andresgalante** [comment]
Hi @jeffkaplan88 , this isn't an issue in the Explorer. Please [ask for help in Discord](https://discord.gg/ED3vxMKU)
