### ISSUE TITLE
do not show error message for a token that is not SIP-10 compliant

### ISSUE THREAD

**Issue by rafaelcr** [hirosystems/explorer#1413]
<img width="350" alt="Screenshot 2024-01-09 at 9 05 29" src="https://github.com/hirosystems/explorer/assets/216195/a12a7ab4-498a-47aa-a2e2-4ac0687c2d89">
The explorer should not display "Unknown error" if the token is not returned by the Metadata API, as these tokens are most likely not SIP-10 compliant.

It should only show users the number of tokens they own while failing silently.

**Comment by rafaelcr** [comment]
Link shown above is: https://explorer.hiro.so/address/SP1K1A1PMGW2ZJCNF46NWZWHG8TS1D23EGH1KNK60?chain=mainnet

**Comment by andresgalante** [comment]
Good point, thanks @rafaelcr
