### ISSUE TITLE
Swap taking 12 hours and still pending

### ISSUE THREAD

**Issue by Knwurrole18** [hirosystems/explorer#1418]
I have a transaction that has been pending for more than 12 hours. It was just a swap. Also, I’ve been trying to send stacks and it has been 5 hours and it is still pending. I have upped my Stx for fees to try and push the txns through but nothing is happening. Both IDs are below and my stacks address is SP1PMQ2YBHN641R05PKX1M1YBP4HMKDX5TN09CFB2

Transaction ID 0x094a74cca31926f35d98fbdb3a3e781bb6996121205d69939bae70f3bd5dff98

0xcb11637f72a6690d913c79b2b3caa40c417f55631399303ef9fa06ca4adf51a2gg

Please let me know if I can provide any more information to get these txns processed. Thank you. 

Luke

**Comment by andresgalante** [comment]
This isn't an Explorer issue.

Please ask for community support on the #support channel in [Discord](https://discord.gg/FdhdMUrZ).
