### ISSUE TITLE
TX stuck not finalized 

### ISSUE THREAD

**Issue by diamondintheruf** [hirosystems/explorer#1424]
**Describe the bug**
A clear and concise description of what the bug is. I delegated 3000 tokens to address SPXVRSEH2BKSXAEJ00F1BY562P45D5ERPSKR4Q33 and since then I am not able to see a tab on my wallet to un delegate .
This was nine months ago .TX ID 0x2010d1ef66bcba0ea795a1b72376c2e26d6856dbb3a253b3ca682ed0ff0662e0 and contract SP001SFSMC2ZY76PD4M68P3WGX154XCH7NE3TYMX.pox-pools-1-cycle . 1:51:36 PM 4/3/2023 [#100780](https://explorer.hiro.so/block/0x7f37d17fdfe16299ba9856ef48007c3eeb724bfc15665c7dd7c0b5e4bc2d5041?chain=mainnet)
[#783803](https://mempool.space/block/783803)
9 months ago  .Not sure why I am not able to see how to undelegate. I used to have stacks wallet then I had to update to Hiro wallet.

Kindly look into it.
My email is numericabc@gmail.com 
Regards 
Ashwin P

Transaction ID 
Address 
Block#  
Time stamp

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots or consol.log to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem here:

**Comment by andresgalante** [comment]
This isn't an Explorer issue.

Please ask for community support on the #support channel in [Discord](https://discord.gg/FdhdMUrZ).
