### ISSUE TITLE
failed transaction This transaction did not succeed because the transaction was aborted during its execution.

### ISSUE THREAD

**Issue by Okeny168** [hirosystems/explorer#1425]
**Describe the bug**

Transaction ID 
Address 
Block#  
Time stamp

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots or consol.log to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem here:

**Comment by Okeny168** [comment]
How can I add more stx to let this transaction go through?
![Screen Shot 2024-01-14 at 12 01 31 AM](https://github.com/hirosystems/explorer/assets/29685383/2bb632de-ed9c-4fef-9f93-951f33228469)
![Screen Shot 2024-01-14 at 12 01 31 AM](https://github.com/hirosystems/explorer/assets/29685383/2684d731-878a-4a91-bea7-4762f8d35518)

**Comment by andresgalante** [comment]
This isn't an Explorer issue.

Please ask for community support on the #support channel in [Discord](https://discord.gg/FdhdMUrZ).
