### ISSUE TITLE
Scam

### ISSUE THREAD

**Issue by LourencoManuelAlves** [hirosystems/explorer#1429]
this transition is scam activitie:
0x1f07dc2e6cfe2129cb14e207a7e4f592c246df28aae3e596f1a6449c8f20854c.

This wallet is Scam activitie: **SPCP3WTTCRYQ1YFZXNHP3SH61G980674Z5PBAKD3**

I lost my all STX token

**Comment by andresgalante** [comment]
This isn't an Explorer issue.

Please ask for community support on the #support channel in [Discord](https://discord.gg/FdhdMUrZ).
