### ISSUE TITLE
Transactions Page Updates

### ISSUE THREAD

**Issue by eugeniadigon** [hirosystems/explorer#1430]
A couple of widgets and UI updates for the Transactions page + inclusion of Mempool information.
Related: #1390

### **In this update:**
**General:**
- [x] Remove "Recent transactions" subtitle (above "Confirmed" selector) as it's redundant
- [x] Add "Show: value" selector to replace the click action on price tags to display different values. This setting affects all the price tags on the page.
- [x] Update "Sort by" selector to match design

**Fee stats:**
- [x] Add mempool stats and section titles
`Let's make this a seperate PR`
- [x] Add explainer tooltip over No priority, Low, Medium, High
`Let's make this a seperate PR and hit it when creating the new mempool header`
- [x] Add filter by Tx type
**Standardize numbers:**
- [x] Use tabular numbers for fees
- [x] Limit numbers to 4 decimals (except when number is 0, example: 0.0000034 STX = 0 STX)

**Transaction row:**
- [x] Replace “In anchor block + block hash” for Block number. Having "In anchor block" in every row is redundant, and block hash doesn't offer valuable information, plus it links to Block page.
- [x] Rearrange Tx information in its respective lines and columns
- [x] Replace "STX transfer" for "Token transfer" as Tx type title
- [x] Update Tx type icons
- [x] In Pending transactions, remove "Pending" from Tx row (redundant)
**Timestamps:**
- [x] Replace “a min ago” for “1 min ago”
- [x] Replace “a few secs ago” for “Now”
- [x] Add full timestamp tooltip

**Mobile:**
- [ ] Fee stats has a reduced version. Shows only average by default (still possible to filter) 
- [ ] Update Tx rows to match design (order of elements, sizes, etc)

**Preview:**
<img width="1834" alt="Transactions Page" src="https://github.com/hirosystems/explorer/assets/78865845/113c3b11-358a-4a5e-bb87-149ddebc3cc1">

@andresgalante @He1DAr

**Comment by BLuEScioN** [comment]
Add explainer tooltip over No priority, Low, Medium, High
 
 What is the explainer? 
 
 @eugeniadigon

**Comment by BLuEScioN** [comment]
In the figma [file](https://www.figma.com/file/31q1g27k69z1yXb6r6vrRD/Stacks-Explorer-Working-File?node-id=6039%3A117&mode=dev), I see the on the txs page, block # is in the bottom right of the tx list item. Is this accurate? I thought we were replacing that with nonce (edited)

**Comment by BLuEScioN** [comment]
When you say
 Limit numbers to 4 decimals (except when number is 0, example: 0.0000034 STX = 0 STX)
In the attached example, the numbers should be 0.0001 and 0.0111 STX, respectively?

https://files.slack.com/files-pri/T02BM1EP6-F06F550CHQC/image.png

**Comment by BLuEScioN** [comment]
@eugeniadigon I am not sure what this means
 Use tabular numbers for fees

**Comment by eugeniadigon** [comment]
@BLuEScioN :

1. Tooltips text: Waiting on guidance from Andy

2. Tabular numbers: It's a CSS text property, [more info here](https://sebastiandedeyne.com/tabular-numbers)

3. Decimals: In that example, we have: 0.01 STX, 0.011123 STX, 0.0025 STX, 0.00018 STX... All with different quantities of decimal numbers. I'm not sure if this already follows a certain logic, but it'd be nice to standardize it and always use the same # of decimals (except when it'd be 0.0000... then might as well just use "0"). I'm open to other suggestions!

4. "In the Figma file, I see the on the txs page, block # is in the bottom right of the tx list item. Is this accurate? I thought we were replacing that with nonce" -> **_Confirmed_** transactions will have respective block number, **_Pending_** transactions will have nonce

**Comment by BLuEScioN** [comment]
Regarding 3, I don't think 0.0000... should be 0, as that would mean we are saying the fee cost 0, which is not how blockchains work. There always has to be a fee. I recommend limiting the decimal place to the first 2 significant digits.

**Comment by eugeniadigon** [comment]
> Regarding 3, I don't think 0.0000... should be 0, as that would mean we are saying the fee cost 0, which is not how blockchains work. There always has to be a fee. I recommend limiting the decimal place to the first 2 significant digits.

I see, currently we rely on tooltips to show the full number when 0 STX is displayed but I realize that's not the best UX. Limiting the decimal to the first 2 significant digits sounds good.

**Comment by BLuEScioN** [comment]
Rearrange Tx information in its respective lines and columns
 Fee stats has a reduced version. Shows only average by default (still possible to filter)
 Update Tx rows to match design (order of elements, sizes, etc)

@eugeniadigon Can you calrify these requirements? I am not sure what the ask is here

**Comment by BLuEScioN** [comment]
@eugeniadigon 
The new filter type that we have for showing the average transaction fee for a specific transaction type is basically the transaction type filter we already have.
Is there any way to reuse the transaction type filter we already have, or do we need the new filter?
![image](https://github.com/hirosystems/explorer/assets/20312835/f038f470-1010-44ac-a700-9bf56e1d5316)

**Comment by eugeniadigon** [comment]
> Rearrange Tx information in its respective lines and columns
Fee stats has a reduced version. Shows only average by default (still possible to filter)
Update Tx rows to match design (order of elements, sizes, etc)
> 
> @eugeniadigon Can you calrify these requirements? I am not sure what the ask is here

**1) Rearrange Tx information in its respective lines and columns:**
Right now we have this: 
Tx Value: Tx ID [value tag] .......................................................... Time stamp
Tx type - Send Address - Receive Address ................................ In anchor block - Block hash - Fee
<img width="702" alt="Screenshot 2024-02-01 at 09 53 29" src="https://github.com/hirosystems/explorer/assets/78865845/052e1a38-5695-4b61-97f4-825cbd82384d">

And should be updated/rearranged for this: 
Tx Value [value tag] ............................................................................... Tx ID - Time stamp
Tx type - Send Address - Receive Address - Fee  ................................ ~~In anchor block~~ Block hash - Nonce
<img width="950" alt="Screenshot 2024-02-01 at 09 55 08" src="https://github.com/hirosystems/explorer/assets/78865845/73c38b13-72a5-49ee-b5f9-92e835457303">


**2) Fee stats has a reduced version. Shows only average by default (still possible to filter)**
Just clarifying that [on the mobile version](https://www.figma.com/file/31q1g27k69z1yXb6r6vrRD/Stacks-Explorer-Working-File?type=design&node-id=6086%3A4089&mode=design&t=7yM2oOPAeP5CPm6C-1), the Fee stats are not broken down by Tx type, but only shows the average. The filter of "Show:" remains there to make it possible to see fees for other Tx types.

**3) Update Tx rows to match design (order of elements, sizes, etc)**
This is to match this (current mobile tx row)
<img width="465" alt="Screenshot 2024-02-01 at 10 12 22" src="https://github.com/hirosystems/explorer/assets/78865845/ec881ebf-5d9d-44e2-9e24-7d224548c7e6">

To this (also on Figma):
<img width="284" alt="Screenshot 2024-02-01 at 10 11 16" src="https://github.com/hirosystems/explorer/assets/78865845/8a91c58c-36b9-4632-bb59-5ef35f49f054">

**Comment by eugeniadigon** [comment]
> @eugeniadigon The new filter type that we have for showing the average transaction fee for a specific transaction type is basically the transaction type filter we already have. Is there any way to reuse the transaction type filter we already have, or do we need the new filter? ![image](https://private-user-images.githubusercontent.com/20312835/301341471-f038f470-1010-44ac-a700-9bf56e1d5316.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3Nzc4MTYsIm5iZiI6MTcwNjc3NzUxNiwicGF0aCI6Ii8yMDMxMjgzNS8zMDEzNDE0NzEtZjAzOGY0NzAtMTAxMC00NGFjLWE3MDAtOWJmNTZlMWQ1MzE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDA4NTE1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlN2JiNGJlMDA4YzgyODE0NDhlNTgzMjljOTFiN2U1OWYyNmM4OGZkZWQzZGUwODNlODQ3Yjg3ZDI4MTg2MTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z6DwDNH4DhoWOMzeNfJM_vP7ZitgaF2D1cPWdvoyXUA)

I understand the ask, but I want to make it explicit that these filters serve different purposes. The first one is to show the _average fee_ for a certain transaction type. The second one is to filter the tx type shown on the tx list. It would be weird to have the same filter, that looks exactly the same, twice on the page, but one only affects the fees and the other one only affects the tx list (in that case, why not just make a general filter for the whole page? but that would be even more confusing)

**Comment by BLuEScioN** [comment]
Ok. It looks like 
 - Fee stats has a reduced version. Shows only average by default (still possible to filter)
 - Update Tx rows to match design (order of elements, sizes, etc)
 Are the only tasks that were not tackled. Let's create separate tasks for those.

**Comment by BLuEScioN** [comment]
Opened up new tasks to address what was missed on this task
