### ISSUE TITLE
Space between menu and submenu

### ISSUE THREAD

**Issue by obycode** [hirosystems/explorer#1433]
**Describe the bug**
When I open the submenu under "Blockchain", if I'm not fast enough moving my mouse, the menu disappears.

**To Reproduce**
1. Mouse over "Blockchain" so that submenu appears
2. Slowly move the mouse down to the submenu
3. See the submenu disappear

**Expected behavior**
If I don't move my mouse outside of the area, then the submenu should stay in place.

**Screenshots**

Uploading Screen Recording 2024-01-18 at 8.02.41 PM.mov…

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Safari and Chrome

**Comment by andresgalante** [comment]
Thanks Brice 🙏 We'll fix this when we do the redesign
