### ISSUE TITLE
Bridge transaction via Alex not completed 

### ISSUE THREAD

**Issue by anthonyfiore** [hirosystems/explorer#1438]
**Describe the bug**     
Transaction has not been completed and its well over a day now that I pegged out of abtc to btc, using the Alex bridge.  Never had a problem with this b4 that had taken this long. Is there a problem? 

Transaction ID -
0x8a56efe3b642260bedd708f9d465803abb6d0487881bbcccc386d44191a005b1

Address SP72WTDT0RZ4MCEKNZV9TKEVXPMS4W88C1ATJRHD 
Block#  
Time stamp

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots or consol.log to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem here:

**Comment by andresgalante** [comment]
This isn't an Explorer issue.

Please ask for community support on the #support channel in [Discord](https://discord.gg/FdhdMUrZ).
