### ISSUE TITLE
Event number wrapping at 2 digits

### ISSUE THREAD

**Issue by obycode** [hirosystems/explorer#1451]
**Describe the bug**
This is very minor but I noticed on [this transaction](https://explorer.hiro.so/txid/0xf9327457c83f6bf9b15de4013e7acab213a9492397e2077970f9bc07b2ae7aa0?chain=mainnet) that the event numbers are wrapping at 2 digits. 

Transaction ID: 0xf9327457c83f6bf9b15de4013e7acab213a9492397e2077970f9bc07b2ae7aa0

**Expected behavior**
These numbers should continue to count up. 

**Screenshots**
![image](https://github.com/hirosystems/explorer/assets/1473715/565fa4d5-1025-41d7-af1b-282fd3946f3e)

**Comment by andresgalante** [comment]
@zone117x This looks like an issue on the API, we actually get 0 instead of 100

what do you think?

**Comment by zone117x** [comment]
Can you show me the endpoint with the issue? I'm looking at the network requests made by that page and the event indexes in the responses look correct, e.g. https://api.hiro.so/extended/v1/tx/0xf9327457c83f6bf9b15de4013e7acab213a9492397e2077970f9bc07b2ae7aa0?event_offset=100&event_limit=100&unanchored=true

**Comment by He1DAr** [comment]
It's a client side issue. I'll push a fix.
