### ISSUE TITLE
I sent my STX tokens from Ledger to Binance but i did't receive at my Binance acc.

### ISSUE THREAD

**Issue by arthurwdmf** [hirosystems/explorer#1458]
**Describe the bug** I sent my STX tokens from Ledger to Binance but i did't receive at my Binance account. The Status of transaction is "Confirmed". https://explorer.hiro.so/txid/0x5e5f92073400995c366958b995c6df8f645e024c1fbdeb95b3a85013fd01abc9?chain=mainnet (this is the link of the transaction)

Transaction ID 0x5e5f92073400995c366958b995c6df8f645e024c1fbdeb95b3a85013fd01abc9
Address SPKMPKDH8N0RX6RQEYPX4Z1QM0KSK0XYTHRAWGTH(Ledger Adress) to SP2TA4FGB43WVAS8MVS6YCWTSN2BZNQ1ASGEAKSDD(Binance Adress)
Block#  
Time stamp 02/21/2024 11:52 AM

**To Reproduce**

**Expected behavior**

**Screenshots**
 
![Ledger transaction](https://github.com/hirosystems/explorer/assets/147115539/b52c121c-122d-4e00-a3c6-575d5c3b9d6f) 
![image](https://github.com/hirosystems/explorer/assets/147115539/581bb89b-961d-4b9c-ab77-2073f806cf2a)
![image](https://github.com/hirosystems/explorer/assets/147115539/4f635270-81b5-4685-be21-836573560ffb)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem here:

**Comment by He1DAr** [comment]
Tx is confirmed, I suggest you contact the exchange to track down your tokens.
