### ISSUE TITLE
Need Help With Failed/Dropped Transaction

### ISSUE THREAD

**Issue by obooks29** [hirosystems/explorer#1464]
<img width="594" alt="Screenshot 2024-02-23 013244" src="https://github.com/hirosystems/explorer/assets/66366120/47e54268-7682-4c86-94b2-aef8647b1bae">
<img width="907" alt="Screenshot 2024-02-23 105533" src="https://github.com/hirosystems/explorer/assets/66366120/bebe8c26-4a67-4859-9d82-7f6d542268bf">

About a week ago I sent some STX from my blockchain wallet to a Binance account. Up until now, it has not been delivered to the receiving wallet nor has it returned to the sending wallet. The status on the blockchain is Dropped.

Below are the details of the transaction: 

Senders wallet:   SP11C44GS0ZYCQ8JH4GK27NZQJM2G7VKKPZ2H6ZQB
Receiving Wallet:  SP2TA4FGB43WVAS8MVS6YCWTSN2BZNQ1ASGEAKSDD
Amount:  97.65625 STX
Transaction ID:  0xf1f106788af6782110ef3042282158c8d5caa90d08deed4cfcfa21fd05a9c9e8

Please Help resolve. Thanks

**Comment by He1DAr** [comment]
It appears that your transaction has been dropped. You may attempt a new transaction.

**Comment by obooks29** [comment]
I checked the transaction and it seems been dropped. However, the fund was not restored to the sending wallet but is in another wallet which is in no way associated with the sending or receiving wallet. Was the fund intercepted because I don't seem to understand how a transaction dropped and the fund from the transaction ended in another wallet?

**Comment by obooks29** [comment]
> It appears that your transaction has been dropped. You may attempt a new transaction.

I checked the transaction and it seems been dropped. However, the fund was not restored to the sending wallet but is in another wallet which is in no way associated with the sending or receiving wallet. Was the fund intercepted because I do nt seem to understand how a transaction dropped and the fund from the transaction ended in another wallet.
