### ISSUE TITLE
STX sent from BYBIT exchange but not received in ledger

### ISSUE THREAD

**Issue by mohitbery67** [hirosystems/explorer#1470]
i sent STX on STX chain from bybit to ledger but did not receive funds in m y ledger.
funds can be seen on 
https://explorer.hiro.so/txid/0xde978ffdc78a6908bd9a96d7db5a8fad0c1a9ab5a2e013dfd1965033f7b8bb13?chain=mainnet

Transaction id 
0xde978ffdc78a6908bd9a96d7db5a8fad0c1a9ab5a2e013dfd1965033f7b8bb13

Kindly help
 regards

MOHIT

**Describe the bug**

Transaction ID 
Address 
Block#  
Time stamp

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots or consol.log to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem here:

**Comment by andresgalante** [comment]
This isn't an Explorer issue.

Please ask for community support on the #support channel in [Discord](https://discord.gg/FdhdMUrZ).
