### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by JackJames1x** [hirosystems/explorer#1472]
*Hello,
2 days ago I made a wrong transaction from my blockchain.com wallet
with 100 STX coins in a wallet that appears on your website and I would like to know if the coins can be returned to me... I have already contacted and talked to the blockchain people about this problem and I would like to know how is it processed for return?
https://explorer.hiro.so/txid/0xb3a87ace8905e91784627da62f7042646ad8468fcc34e98caa17859b6de9b007

**Comment by andresgalante** [comment]
This isn't an Explorer issue.

Please ask for community support on the #support channel in [Discord](https://discord.gg/FdhdMUrZ).
