### ISSUE TITLE
Text overlap in transactions

### ISSUE THREAD

**Issue by eugeniadigon** [hirosystems/explorer#1474]
When the text line is too long, it overlaps with the right column creating a visual bug. This happens mostly on the homepage. Would it be possible to crop with an ellipsis (...) or limit the amount of characters in viewport sizes smaller than 1024px, or start the next breaking point at 1024px?

<img width="782" alt="Screenshot 2024-02-29 at 14 18 16" src="https://github.com/hirosystems/explorer/assets/78865845/5114f9d2-0b91-480f-8a9c-a99b03547a25">

**Comment by BLuEScioN** [comment]
@eugeniadigon I can try the ellipsis approach, and if that doesn't work, I can divide the space into two and then try the ellipsis approach. I think wrapping is off the table. However, I also haven't been able to replicate this scenario. It doesn't seem to occur often. Do you have a consistent repro that I can use to fix this issue?

**Comment by eugeniadigon** [comment]
It does happen quite a lot, also with the second row in token transfers:

https://github.com/hirosystems/explorer/assets/78865845/2fd5d2e2-f5e2-4a85-96c1-4465e001eac2

https://github.com/hirosystems/explorer/assets/78865845/9301dd47-73ca-4f56-bbec-025b24ea4ec5


Maybe cutting into two lines could be a better solution?
<img width="814" alt="Frame 316125137" src="https://github.com/hirosystems/explorer/assets/78865845/f094feee-f786-46bf-9c88-1a6c44b6eaee">


([Figma](https://www.figma.com/file/31q1g27k69z1yXb6r6vrRD/Stacks-Explorer-Working-File?type=design&node-id=7210%3A40114&mode=design&t=IXayzvK6GmlqCy58-1))
