### ISSUE TITLE
Homepage layout breaks in 'tablet' responsive size

### ISSUE THREAD

**Issue by eugeniadigon** [hirosystems/explorer#1475]
https://github.com/hirosystems/explorer/assets/78865845/975852ad-0284-4693-8d64-f2c7d4db6bb8

**Comment by BLuEScioN** [comment]
Unable to repro
https://www.loom.com/share/4eb9151748284924a9789a2f18c28803?sid=45b0b901-9a3b-4f34-aab6-12149278bba1

**Comment by eugeniadigon** [comment]
Weird, can't reproduce it either myself, will close this
