### ISSUE TITLE
Update Navbar architecture and styles

### ISSUE THREAD

**Issue by eugeniadigon** [hirosystems/explorer#1478]
**[🔗 Figma link to component](https://www.figma.com/file/31q1g27k69z1yXb6r6vrRD/Stacks-Explorer-Working-File?type=design&node-id=6625%3A10402&mode=dev&t=FkmHd2FPaShjdZ8S-1)**

- [ ] Group Transactions, Blocks, and Tokens links under "Explore". In the future, this will also be the home to Signers and Stacking links
- [ ] Match text styles to component
- [ ] Update dropdown styles of Explore and Network selection
- [ ] Update Mobile design

<img width="970" alt="Screenshot 2024-03-05 at 17 19 10" src="https://github.com/hirosystems/explorer/assets/78865845/a6fa9f4a-105d-4362-9144-659fa952d922">

<img width="654" alt="Screenshot 2024-03-05 at 17 24 59" src="https://github.com/hirosystems/explorer/assets/78865845/16905f9b-3259-488f-a056-eafc2f22c6cb">

**Comment by andresgalante** [comment]
This is done
