### ISSUE TITLE
Update search bar component

### ISSUE THREAD

**Issue by eugeniadigon** [hirosystems/explorer#1495]
[**🔗 Figma link to component**](https://www.figma.com/file/31q1g27k69z1yXb6r6vrRD/Stacks-Explorer-Working-File?type=design&node-id=6866%3A10821&mode=dev&t=UuvXotDjnNJVHzaf-1)

- Related (empty state): https://github.com/hirosystems/explorer/issues/1485
- Related: https://github.com/hirosystems/explorer/issues/1493
- Related: https://github.com/hirosystems/explorer/issues/1494

----------------

- Align search dropdown to search input field
- Remove "search results/not found" title (redundant)
- Update error/empty state

<img width="1603" alt="Screenshot 2024-03-06 at 13 42 19" src="https://github.com/hirosystems/explorer/assets/78865845/98622c3a-4212-4f87-b765-fdf496066110">

**Comment by andresgalante** [comment]
Can this one be useful for the new search somehow?
