### ISSUE TITLE
Lost my token in Leather wallet

### ISSUE THREAD

**Issue by Raznsingh** [hirosystems/explorer#1501]
Hello,
On March 4th at 9:32 pm, without my permission all of my tokens and coins were taken out from my leather wallet. It was all my savings from the past 2 years. 

my email address is raznsingh@gmail.com

Here is my leather wallet address
SPZYBX4K32R71EAB8SQHC79T4T1CWAVB6600P3TW

and here is the wallet it was transferred to
.SP286DVWPTGD3MG9431J9Z6Y0HW69V5AB6X69YWGS

I am also sending links of transactions.
Please let me know what I can do to retrieve my tokens and coins.

LINK that shows the transactions
https://explorer.hiro.so/address/SPZYBX4K32R71EAB8SQHC79T4T1CWAVB6600P3TW

MY WALLET 
https://stxtools.io/wallets/SPZYBX4K32R71EAB8SQHC79T4T1CWAVB6600P3TW

New Wallet that was transferred to
https://stxtools.io/wallets/SP286DVWPTGD3MG9431J9Z6Y0HW69V5AB6X69YWGS

**Comment by Ramon44-lab** [comment]
They will never reply you on here and they can’t do anything I almost lost about 10 ethereum few days ago thanks to blackhathacker who helped me recover my coins from the scammers  message him on telegram https://t.me/Blackhathacker110

**Comment by andresgalante** [comment]
This isn't an Explorer issue.

Please ask for community support on the #support channel in [Discord](https://discord.gg/FdhdMUrZ).
