### ISSUE TITLE
Update Events row component

### ISSUE THREAD

**Issue by eugeniadigon** [hirosystems/explorer#1502]
Update Events row component to reflect the latest API updates
@He1DAr @rafaelcr 

**[🔗 Figma link](https://www.figma.com/file/31q1g27k69z1yXb6r6vrRD/Stacks-Explorer-Working-File?type=design&node-id=7070%3A81908&mode=dev&t=IzzrnTvrsGA3r7BL-1)**

### Preview:
<img width="902" alt="Frame 316125137" src="https://github.com/hirosystems/explorer/assets/78865845/4d7da467-726b-4465-90e1-45c48cca3c6f">

<img width="993" alt="Frame 316125138" src="https://github.com/hirosystems/explorer/assets/78865845/a77abed3-8f3d-47fd-99b1-b1fe47d5fbe5">

**Comment by andresgalante** [comment]
Part of this issue has been implemented here https://github.com/hirosystems/explorer/pull/1514
