### ISSUE TITLE
Standardize Transaction ID pages

### ISSUE THREAD

**Issue by eugeniadigon** [hirosystems/explorer#1503]
This issue tackles standardization for Transaction ID pages and their different transaction types and statuses:
- Coinbase
- Transfer
- Function Call
- Contract deploy
- Pending transaction
- Failed transaction

**🔗 Figma links to related components: [Tags](https://www.figma.com/file/31q1g27k69z1yXb6r6vrRD/Stacks-Explorer-Working-File?type=design&node-id=6625%3A7525&mode=dev&t=UuvXotDjnNJVHzaf-1), [ID Details](https://www.figma.com/file/31q1g27k69z1yXb6r6vrRD/Stacks-Explorer-Working-File?type=design&node-id=6624%3A7777&mode=dev&t=UuvXotDjnNJVHzaf-1), [Transactions row](https://www.figma.com/file/31q1g27k69z1yXb6r6vrRD/Stacks-Explorer-Working-File?type=design&node-id=6624%3A7775&mode=dev&t=UuvXotDjnNJVHzaf-1), [Events row](https://www.figma.com/file/31q1g27k69z1yXb6r6vrRD/Stacks-Explorer-Working-File?type=design&node-id=6993%3A73604&mode=dev&t=UuvXotDjnNJVHzaf-1)**

[**🔗 Figma link to page mock-ups**](https://www.figma.com/file/31q1g27k69z1yXb6r6vrRD/Stacks-Explorer-Working-File?type=design&node-id=6809%3A36401&mode=dev&t=UuvXotDjnNJVHzaf-1)

### General updates:

- Updates to Details (Summary) section. Unify text styles. Move `transaction status` and `transaction type` tags to the Details table. Update the way data is shown (time stamp, block height, fees). Update 'copy' icon.

<img width="1908" alt="Group 316125025" src="https://github.com/hirosystems/explorer/assets/78865845/944022e1-e449-463c-a1c8-04384b8af9c2">

<img width="1908" alt="Group 316125024" src="https://github.com/hirosystems/explorer/assets/78865845/61211393-d47b-41fe-97ea-8b7b46d04a9b">

-----------------------------------

- Update Bitcoin anchor details table text styles
<img width="945" alt="Group 316125023" src="https://github.com/hirosystems/explorer/assets/78865845/d6364979-393c-4600-b8c3-ccbc98249290">

-----------------------------------

- Update Contract details column styles and icons
<img width="945" alt="Group 316125022" src="https://github.com/hirosystems/explorer/assets/78865845/cbe3d625-f03f-49d4-abf6-53340f5ed38c">

-----------------------------------

- Update events component (https://github.com/hirosystems/explorer/issues/1502)

<img width="1096" alt="Group 31612502s6" src="https://github.com/hirosystems/explorer/assets/78865845/c40a2008-1681-44cd-a76d-138772bf373a">

-----------------------------------

- Update post-conditions component
<img width="1063" alt="Group 316125027" src="https://github.com/hirosystems/explorer/assets/78865845/f2bcd4f1-d247-4537-b96d-80f9276cc79d">

-----------------------------------

- Update available functions component
<img width="1908" alt="Group 316125026" src="https://github.com/hirosystems/explorer/assets/78865845/e1e5a863-61be-433d-92b5-43ff5a3d6843">

-----------------------------------

- Update function call component
<img width="1908" alt="Group 316125028" src="https://github.com/hirosystems/explorer/assets/78865845/2419aaf6-b949-4d28-943c-e86658661308">
 
-----------------------------------

- Update source code component
<img width="1908" alt="Group 316125029" src="https://github.com/hirosystems/explorer/assets/78865845/f0f5afff-5b75-4a43-a804-e37b19a33cc6">

-----------------------------------

- Add transaction history + status help/guidance
<img width="2868" alt="Group 316125030" src="https://github.com/hirosystems/explorer/assets/78865845/8f5f8953-61e5-447c-a97c-89bb8694e84a">

**Comment by andresgalante** [comment]
I'll close this one as we'll change things when we do the redesign
