### ISSUE TITLE
Toggle expand-collapse STX Blocks in the Group by BTC Block view. 

### ISSUE THREAD

**Issue by saralab** [hirosystems/explorer#1505]
In the Group by BTC Block view in both the Home Page and Blocks page,  enable expand-collapse as an option for each BTC block to toggle the STX Transactions under it. It will also help view multiple BTC Blocks one one screen. 

Additionally, include the Total Number of STX transactions per BTC Block next to  the BTC Block number.
For Live View, this count will have to keep up and updated with each incoming STX Block 
 
<img width="1361" alt="Screen Shot 2024-03-07 at 4 51 14 PM" src="https://github.com/hirosystems/explorer/assets/264896/eaf079a2-29ec-44f5-ac80-e77d41bb5503">

**Comment by eugeniadigon** [comment]
Here are the [updated components](https://www.figma.com/file/31q1g27k69z1yXb6r6vrRD/Stacks-Explorer-Working-File?type=design&node-id=6792%3A7105&mode=dev&t=ASKe4Hoi6fHr1CWy-1), and [updated page mock-ups](https://www.figma.com/file/31q1g27k69z1yXb6r6vrRD/Stacks-Explorer-Working-File?type=design&node-id=6452%3A33446&mode=dev&t=ASKe4Hoi6fHr1CWy-1)
