### ISSUE TITLE
$NAKAMOTO token's metadata need get refreshed

### ISSUE THREAD

**Issue by Satoshiaaw2** [hirosystems/explorer#1512]
**Describe the bug**
link: https://explorer.hiro.so/address/SP3R4MHK99JAAM0N3T0CBZRZVSVQFG1N75DQ08JSD?chain=mainnet
$nakamoto token's metadata need get refreshed.

**Comment by andresgalante** [comment]
cc @rafaelcr can you help me do this one please 🙏

**Comment by rafaelcr** [comment]
hi @andresgalante this was refreshed last night 👍 let me know if you need me to do it again

**Comment by andresgalante** [comment]
Excellent! thanks! I'll close the issue
