### ISSUE TITLE
Contract deploy estimations are off

### ISSUE THREAD

**Issue by pradel** [hirosystems/explorer#1515]
**Describe the bug**

The contract deploy estimation is the same for all the priority mode (40 STX) where I guess it should be lower for lower modes

**Screenshots**

![Screenshot 2024-03-13 at 14 49 41](https://github.com/hirosystems/explorer/assets/5749437/47451ae1-e65b-45af-a030-1299322b7e14)

**Comment by andresgalante** [comment]
@BLuEScioN can you take a look at this and see if there is a bug please 🙏

**Comment by andresgalante** [comment]
hey @pradel this seems ok now, have you been able to reproduce it again?
