### ISSUE TITLE
Implement Nakamoto bannner/splash-screen

### ISSUE THREAD

**Issue by sabbyanandan** [hirosystems/explorer#1522]
As we prepare for the Nakamoto Testnet activation (March 25th, 2024), we want to proudly highlight the Nakamoto value prop and the Explorer-centered goodies via a banner or splash-screen, which the users can read, acknowledge or optionally ignore.

The copy & CTAs are likely similar to: https://www.figma.com/file/zQt1ia4SlVM8t6c0jmFWEy/Platform-Working-File?type=design&node-id=2030-1686&mode=design&t=z7jLOHRgR2mRNwBo-0, but more Explorer-themed UX.

**Comment by eugeniadigon** [comment]
Here's the design for the Nakamoto pop-up banner:

![Nakamoto Testnet Modal](https://github.com/hirosystems/explorer/assets/78865845/f17d56ef-aaf1-4697-9e02-ed669288a87a)


Design → https://www.figma.com/file/31q1g27k69z1yXb6r6vrRD/Stacks-Explorer-Working-File?type=design&node-id=6489%3A13480&mode=dev&t=oqRGweEls5VofEwB-1

Component (to reuse for future announcements) → https://www.figma.com/file/31q1g27k69z1yXb6r6vrRD/Stacks-Explorer-Working-File?type=design&node-id=6656%3A7595&mode=dev&t=oqRGweEls5VofEwB-1


Note: "Learn more about Nakamoto Testnet ↗" will link to an announcement blog post, still WIP
