### ISSUE TITLE
Update status bar component

### ISSUE THREAD

**Issue by eugeniadigon** [hirosystems/explorer#1541]
- Update color scheme (dark status bar goes on light mode, white status bar goes on dark mode, to create better contrast and attention to it)
- Create two types: one for `info/notice`, one for `performance`
- Create two hierarchies so they're not competing when we have two bars. `primary` always goes on top of the page, above the header, and `secondary` goes on the header, above the page title. Hierarchy should be decided by a) importance and/or b) duration (shortest lived one should be secondary)

Figma Component: https://www.figma.com/file/31q1g27k69z1yXb6r6vrRD/Stacks-Explorer-Working-File?type=design&node-id=7431%3A40146&mode=dev&t=E0Yiv3jqLIxZNHqL-1

Mock up preview:
![statusbar-lightmode](https://github.com/hirosystems/explorer/assets/78865845/255ae210-38e2-4299-bbbf-0ed1b2d1441b)
![statusbar-darkmode](https://github.com/hirosystems/explorer/assets/78865845/1e2190e0-97b9-4ff1-b10f-31bafa58633d)
![statusbar-mobile](https://github.com/hirosystems/explorer/assets/78865845/26a561d4-fa29-498b-a1f7-bddf920e2d7f)

*Related https://github.com/hirosystems/explorer/issues/1432

**Comment by He1DAr** [comment]
Thank you @eugeniadigon. It can be tricky to differentiate between primary vs short-lived status bars. Right now, we get status updates from statuspage.io and we keep them up until they're resolved + occasional custom messages that we manually display. Also wondering how the secondary status bar would look like in other pages aside from home?

**Comment by He1DAr** [comment]
So from the explorer's perspective, they're all the same, and the order would be based on the status release timestamp. We don't know in advance how long it will be displayed unless it's a custom message. Even for some custom messages, we keep them up until a certain goal is achieved, such as all miners updating to the new version, etc.

**Comment by eugeniadigon** [comment]
Got it, thanks for the explanation Heidar

I think we need to differentiate then what's a **status bar** (from statuspage.io) from what's a **manual/comms bar** (the ones we handle via CMS as I understand). Usually the latter will always be "info" bars, since the warnings are already triggered from status.

Could we perhaps work on a logic where, a manual/comms bar will always appear on top position:

<img width="1322" alt="Screenshot 2024-06-21 at 14 07 22" src="https://github.com/hirosystems/explorer/assets/78865845/932b2526-2520-4021-b071-70f1d662b30c">

------

**unless** a status bar comes up, in which case, it would be moved to secondary position (and only shown on homepage), until the status bar is finished:


<img width="1281" alt="Screenshot 2024-06-21 at 14 10 19" src="https://github.com/hirosystems/explorer/assets/78865845/0b858525-7d07-448c-8616-0edbe76b7b10">

And if there are multiple status bars, they will appear stacked.

Would this be easy to implement or is this adding too much unnecessary complexity?

**Comment by He1DAr** [comment]
@eugeniadigon can you elaborate more on the multiple status bars case? maybe an extreme case with 2 status page bars and 2 CMS bars? (likely won't happen but just to clarify the logic)

**Comment by eugeniadigon** [comment]
> @eugeniadigon can you elaborate more on the multiple status bars case? maybe an extreme case with 2 status page bars and 2 CMS bars? (likely won't happen but just to clarify the logic)

I added some examples + edge cases here, and simplified a bit the logic of when the "bottom" bar appears: https://www.figma.com/design/31q1g27k69z1yXb6r6vrRD/Stacks-Explorer-Working-File?node-id=8623-66090&t=bIXsNIGJbLzlj2Yp-1

Let me know what you think
