### ISSUE TITLE
My Stacks balance disappeared

### ISSUE THREAD

**Issue by Warlordsnftx** [hirosystems/explorer#1546]
**Describe the bug**

Transaction ID 
Address SP36X3EM1CM87H312Q614FBBF3H6CZHTDK9TGGD29
Block#  
Time stamp

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots or consol.log to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem here:  
I saved my STX airdrops for the past year but now I don't see my STX, and there is nothing in the transaction history.
Please help

![stx1](https://github.com/hirosystems/explorer/assets/156831744/d8ed97c9-0224-418e-827e-69523978c2b0)
![stx2](https://github.com/hirosystems/explorer/assets/156831744/44214a8d-507d-42b5-9b90-44576508385f)

**Comment by andresgalante** [comment]
This isn't an Explorer issue.

Please ask for community support on the #support channel in [Discord](https://discord.gg/FdhdMUrZ).
