### ISSUE TITLE
My Stacks balance disappeared #1546

### ISSUE THREAD

**Issue by Warlordsnftx** [hirosystems/explorer#1547]
I saved my STX airdrops for the past year but now I don't see my STX, and there is nothing in the transaction history.
Please help...

Address SP36X3EM1CM87H312Q614FBBF3H6CZHTDK9TGGD29
![stx2](https://github.com/hirosystems/explorer/assets/156831744/8f2a0c76-3f13-4622-a03d-a4298494cb0e)
![stx1](https://github.com/hirosystems/explorer/assets/156831744/9e152b3f-604c-4728-adda-b5ed11571ff4)

**Comment by andresgalante** [comment]
This isn't an Explorer issue.

Please ask for community support on the #support channel in [Discord](https://discord.gg/FdhdMUrZ).
