### ISSUE TITLE
Search results widget doesn't show the correct number of tx

### ISSUE THREAD

**Issue by andresgalante** [hirosystems/explorer#1549]
The search preview doesn't show the correct number of tx, for example:

<img width="854" alt="image" src="https://github.com/hirosystems/explorer/assets/1832037/96cdd7d4-e5dc-4c07-8198-0f4019e6243a">

0x7e45b979faa97fdcfba6ee6edc85206825ae5cc39bca77d46c4a49b2763e85ba

**Comment by csgui** [comment]
Just adding more detail. When searching by `block_hash`, the number of transactions is always `1`. However, when searching by `block_height`, the number of transactions is displayed correctly.

For instance` block_hash: 0x7e45b979faa97fdcfba6ee6edc85206825ae5cc39bca77d46c4a49b2763e85ba` and `block_height: 137843`.

**Comment by andresgalante** [comment]
I'll close this one since we are working on an improved serach
