### ISSUE TITLE
Explorer shows error on addresses with no transactions

### ISSUE THREAD

**Issue by CharlieC3** [hirosystems/explorer#1550]
**Describe the bug**
When visiting a valid address, the Explorer will show an error if there are no transactions.
[Example address](https://explorer.hiro.so/address/STGZXM8SYXW1GZ46MRSX6QKQX839C9NPJ0BM5KQ9?chain=testnet).

![Screenshot 2024-04-02 at 4 59 29 PM](https://github.com/hirosystems/explorer/assets/2747302/13ca677a-2816-4332-9553-08b38d8ef678)

This can potentially cause some confusion and make a user think there is a problem with the address when there isn't.
Ideally, the Explorer would be able to determine if it is a valid address and would instead show no transactions instead of an error.

**Comment by eugeniadigon** [comment]
Thanks for flagging, Charlie

I added an empty state on the Address ID page:
https://www.figma.com/file/31q1g27k69z1yXb6r6vrRD/Stacks-Explorer-Working-File?type=design&node-id=7717%3A61388&mode=design&t=WSfTEAv7qSq5xBMC-1

![Address-ID - Empty state](https://github.com/hirosystems/explorer/assets/78865845/b60a83aa-37e8-4f6d-9cc5-5d8e4cf5bf42)
