### ISSUE TITLE
Implement "Need Support?" page

### ISSUE THREAD

**Issue by sabbyanandan** [hirosystems/explorer#1551]
**Context**: 
https://docs.google.com/document/d/1BbOXsuikpHlaI9ChjrUlltbpPAmgnOafnWEeqEC8B74/edit#heading=h.efs7ggobb664

With that context,

0: Implement the support page and have it render at https://explorer.hiro.so/support

1: Swap the current "Community Support" link with "Need Support?" (as the label) and the link pointing to https://explorer.hiro.so/support

2: Remove "Submit bug or feature request"; it is already included in the support page. That is sufficient.

**Comment by eugeniadigon** [comment]
Design mockup pending

**Comment by eugeniadigon** [comment]
Related https://github.com/hirosystems/explorer/issues/1480

**Comment by eugeniadigon** [comment]
Figma link: https://www.figma.com/file/31q1g27k69z1yXb6r6vrRD/Stacks-Explorer-Working-File?type=design&node-id=7492%3A66570&mode=dev&t=eHaS1nGj2AtHTgRN-1

Mock up:

![Support](https://github.com/hirosystems/explorer/assets/78865845/c3b7cdba-d193-488c-b086-11d800f14081)

**Comment by andresgalante** [comment]
This one is done :)
