### ISSUE TITLE
The transaction is not completed even after 24 hours. Please help.

### ISSUE THREAD

**Issue by napool707** [hirosystems/explorer#1552]
**Describe the bug**

Transaction ID : 0x58aadf590d38be2d7bd0746d15d44e9e571b24eadc4982e341a8d4d377ebe80b
Address : SP38T4KH2CN1BH76FZJYBK88N802WSCG9ZW9WTJZE
Block#  : 

Time stamp

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots or consol.log to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem here: 
![#1](https://github.com/hirosystems/explorer/assets/151032448/f9bd8877-4688-454b-9b95-7273d14ab4ba)
![#2](https://github.com/hirosystems/explorer/assets/151032448/3bec4f29-9ede-4b7a-9304-e9ba7cca5e27)

**Comment by napool707** [comment]
I am not yet familiar with using XVERSE WALLEET. Please help me perform the following steps.

**Comment by andresgalante** [comment]
This isn't an Explorer issue.

Please ask for community support on the #support channel in [Discord](https://discord.gg/FdhdMUrZ).
