### ISSUE TITLE
stx

### ISSUE THREAD

**Issue by maiklvalkiv** [hirosystems/explorer#1553]
У мене виникла проблема з переводом STX
вони нікуди не прийшли,допоможіть будь ласка
![Screenshot_20240331-155512](https://github.com/hirosystems/explorer/assets/166013962/33100056-c918-4672-95ee-a1f71dd68ea3)

**Comment by andresgalante** [comment]
This isn't an issue in the Explorer, for support please contact the community in Discord.

https://discord.gg/pAWE3Hgu
