### ISSUE TITLE
Devnet URL overflows in network dropdown

### ISSUE THREAD

**Issue by eugeniadigon** [hirosystems/explorer#1562]
When opening the Explorer from platform's Devnet, the URL overflows from the dropdown:

<img width="553" alt="Screenshot 2024-04-12 at 10 28 13" src="https://github.com/hirosystems/explorer/assets/78865845/2620c927-f9a7-4000-9475-e4bd26402a78">

------
I suggest widening the dropdown and/or showing the URL in two lines (but no more than two lines)

<img width="1110" alt="Screenshot 2024-04-12 at 11 03 42" src="https://github.com/hirosystems/explorer/assets/78865845/9ae1f485-594f-4a11-b281-83a8ea73ef76">

**Comment by andresgalante** [comment]
This is a bug, lets do it now instead of waiting for the redesign

**Comment by BLuEScioN** [comment]
@eugeniadigon 

Widening the dropdown doesn't solve the problem and allowing the text to wrap to two lines before adding an ellipsis overcomplicates things.

I suggest just adding an ellipsis.

I also added the ability to see the full text on hover using the title attribute



![Image](https://github.com/hirosystems/explorer/assets/20312835/9aacee0a-9800-4a32-841a-54bd9def156f)



![Image](https://github.com/hirosystems/explorer/assets/20312835/0e9023f9-6317-472d-88ab-67e8065ba4a6)
