### ISSUE TITLE
Pending Stacks Withdrawal/Transfer

### ISSUE THREAD

**Issue by Dannithegreat** [hirosystems/explorer#1565]
Hello, Good day.
I made a withdrawal/ Transfer of my stacks over 6 hours ago but it's showing sending and check the explorer, I saw my transaction is pending.

0x747c028117477609cca128e63cdc6515dceeb2424d2b2fd997d00ff3019554bc
That's the transaction ID

**Comment by andresgalante** [comment]
Thanks for the help @314159265359879 

I'll close this issue since it isn't a problem with the Explorer
