### ISSUE TITLE
Block Time Formatting Error

### ISSUE THREAD

**Issue by BowTiedDevOps** [hirosystems/explorer#1568]
**Describe the bug**
The formatting of the current block time is off, also, the time decreases instead of increasing. Explorer transaction: https://explorer.hiro.so/txid/0xcca440c87ea96f1c18e7f22d95bdf5ad9a286f401a082a018aad57792baf6a10?chain=testnet

Transaction ID: 0xcca440c87ea96f1c18e7f22d95bdf5ad9a286f401a082a018aad57792baf6a10
Address: ST168N23S4414935CQ37376FXRXTBZ5K7KBD69KD8
Block#: Unanchored - 2586618 (Bitcoin), 152419 (Stacks)
Time stamp: Broadcasted at 7:16:08 PM 4/16/2024 GMT +2

**To Reproduce**
Open a pending transaction and scroll down to the block times.

**Expected behavior**
The time to be pretty formatted (HH:MM:SS), and go up instead of down.

**Screenshots**
![image](https://github.com/hirosystems/explorer/assets/157840260/e2579a25-f7d4-4ffe-98c5-49260bad9168)
![image](https://github.com/hirosystems/explorer/assets/157840260/cab2b550-e734-445a-b00f-0fb4840817f1)

**Desktop (please complete the following information):**
 - OS: Debian Linux
 - Browser Google Chrome
 - Version: OS - 13, Chrome - 121.0.6167.184 (Official Build) (64-bit)

**Comment by andresgalante** [comment]
Hi @BowTiedDevOps, thanks for the report. I need help understanding the bug. 

The time displayed is the elapsed time that the block took to confirm. Is that off?


![Image](https://github.com/hirosystems/explorer/assets/1832037/6b1ee147-2ef3-4f57-b7d9-1226a4f11932)

**Comment by BowTiedDevOps** [comment]
Hi @andresgalante! As I can see in your attached screenshot, the time is properly formatted now. This issue refers to the section with elapsed time that the blocks took to confirm, but it applies to the elapsed time since the last confirmed block (in your image, it is `14:26`). As you can see, in my screenshots it was formatted as `0-1:0-33:0-26`, and it was also going down instead of up (second picture is taken after the first, and it was `0-1:0-33:0-9`). I'm not sure what caused it, as I see it's normal now.

**Comment by andresgalante** [comment]
strange, I'll keep an eye on this and reopen it if I can reproduce it
