### ISSUE TITLE
Error displayed on empty wallet

### ISSUE THREAD

**Issue by 314159265359879** [hirosystems/explorer#1571]
**Describe the bug**
On the latest version of explorer.hiro.so "Unknown error" is displayed
https://explorer.hiro.so/address/SP1VNFEKRK804ZDTQ6QAK8GMKPP0SND40F0Q4F0E6?chain=mainnet
![image](https://github.com/hirosystems/explorer/assets/33360391/e7cc0370-b538-4de1-b83b-a9a812e3c6fe)

This is on the old Hiro explorer still used by ALEX:
https://explorer.alexlab.co/address/SP1VNFEKRK804ZDTQ6QAK8GMKPP0SND40F0Q4F0E6?chain=mainnet
![image](https://github.com/hirosystems/explorer/assets/33360391/7f9f5d0e-4627-4718-a6aa-6dd821e29158)

Transaction ID n.a.
Address SP1VNFEKRK804ZDTQ6QAK8GMKPP0SND40F0Q4F0E6
Block#  n.a.
Time stamp n.a.

I believe this can be reproduced with any fresh address. I think showing "no transactions found" is more appropriate than "unknown" error, and something went wrong. 

a user who looks at an address like this should be made aware of the fact that it is an address that doesn't have any history. In this case they think it can't be loaded but there may still be history or balance.

**Comment by andresgalante** [comment]
Thanks @314159265359879 

This is a known issue, I'll close it since it's duplicated here https://github.com/hirosystems/explorer/issues/1550
