### ISSUE TITLE
We are not receiving tokens after wrapping transfer to Stacks Chain

### ISSUE THREAD

**Issue by rovert1** [hirosystems/explorer#1582]
**Describe the bug**
A token bridged from xlink stopped on the stack chain

Transaction ID     0xbc2cffbdcd7dd9310c3f3bb3f83859af55954e512014f81849bc1bc10f94d289
Address        SP1PD82M81JRER33HCEJ3Y7Q3Y4BRZGQCT4CS8YQZ
Block#  none
Time stamp   오후 9:21:43 2024. 4. 4.

**To Reproduce**

**Expected behavior**
Bridge from xlink >> Sent successfully but no tokens come in

**Screenshots**
If applicable, add screenshots or consol.log to help explain your problem.

![20240420_121359](https://github.com/hirosystems/explorer/assets/167595281/f917f849-baa9-4746-99bb-f25b789b7dff)
![20240420_121507](https://github.com/hirosystems/explorer/assets/167595281/5317e699-2842-44b3-8da3-516ad84e20d9)
![20240420_121530](https://github.com/hirosystems/explorer/assets/167595281/90b80133-4686-4b7b-9224-165c6b5108da)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] windows 10 pro (OS Build  19043.1826)
 - Browser [e.g. chrome, safari] chrome   (123.0.6312.124)

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem here: 
usdt Send
from-  Transaction Hash: 0xce1cf02a48b9e9cee624d140b24ecd0ee6e94bbf476f54982c3d25b74e7c6730
from   0x364c3d952415e865B9307006fFBcC2EF9AeFe747 
to   0xfd9F795B4C15183BDbA83dA08Da02D5f9536748f

xlink wrapping

receive susdt
to - id:  0xbc2cffbdcd7dd9310c3f3bb3f83859af55954e512014f81849bc1bc10f94d289
by         SP321XXFYGSHQ244879VPVEZJ8BXKY71KE3DMXJN4

![20240420_121359](https://github.com/hirosystems/explorer/assets/167595281/b0499715-7074-4468-ae52-43132df699a3)
![20240420_121507](https://github.com/hirosystems/explorer/assets/167595281/d35dcc3d-a4c9-4c94-a956-d8c8f9cd211b)
![20240420_121530](https://github.com/hirosystems/explorer/assets/167595281/2ba461a8-82b1-4658-9b00-9a0f3df38a4f)

**Comment by andresgalante** [comment]
This isn't an issue in the Explorer, for support please contact the community in Discord.

https://discord.gg/pAWE3Hgu
