### ISSUE TITLE
Please help us

### ISSUE THREAD

**Issue by Yurii999Yura** [hirosystems/explorer#1583]
**Describe the bug**

Transaction ID 
Address SP1C5M9V9TNZECN1Y51VHRMSES4QGPZS0V54MG2X
Block#  0xc62018254ff339503882f9b98b86c8c9ffdca8bd0e5467fc544835456251180e
Time stamp  17:38:34 15.04.2024
Transaction ID 0x35173b9dfb7799741fa7aa074cce1b5cfbb10b4d24075ccce324c3e57bc888b5

I sent my STX to the STACKS chain
to my binance account and haven't received it for 6 days 
what's the problem?
THANK YOU

**Screenshots**
If applicable, add screenshots or consol.log to help explain your problem.
![image](https://github.com/hirosystems/explorer/assets/137002434/b1a16249-7493-4ec3-8bb2-3437766d997c)
![photo_5271549882114628956_y](https://github.com/hirosystems/explorer/assets/137002434/b00fe885-5765-4009-8c69-7695bc3bebd1)

**Desktop (please complete the following information):**
 - OS
 - Browser chrome

**Additional context
Add any other context about the problem here:

**Comment by andresgalante** [comment]
This isn't an issue in the Explorer, for support please contact the community in Discord.

https://discord.gg/pAWE3Hgu
