### ISSUE TITLE
Hey, I was swaping stx to btc, my stx went out, but btc never came back. 

### ISSUE THREAD

**Issue by and422** [hirosystems/explorer#1589]
**Describe the bug**

Transaction ID 
Address 
Block#  
Time stamp

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots or consol.log to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem here:

**Comment by andresgalante** [comment]
This isn't an issue in the Explorer, for support please contact the community in Discord.

https://discord.gg/pAWE3Hgu
