### ISSUE TITLE
hey, i was swaping yesterday stx to btc and my stx went out, bu btc never came back

### ISSUE THREAD

**Issue by and422** [hirosystems/explorer#1590]
**Describe the bug**

Transaction ID 0x52d5e9e228fa29673cc1176d55edb2fbae803f95a0f949fb1f01dfa70db813d0
Address 35oynig9E261cunf4wKyofkHK7GYHPSFjE
Block#  0x3d5cc19ea34fcac97c886e347e34bcdda330ad147da4a79efca917ebd1514c8b
Time stamp 2:02:36 AM 4/23/2024

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots or consol.log to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem here:

**Comment by andresgalante** [comment]
This isn't an issue in the Explorer, for support please contact the community in Discord.

https://discord.gg/pAWE3Hgu
