### ISSUE TITLE
 Ordinals and Stacks NFTs not showing in Leather

### ISSUE THREAD

**Issue by DeeList** [hirosystems/explorer#1591]
The following inscriptions and STX NFTs are failing to appear in Leather:

https://api.hiro.so/ordinals/v1/inscriptions/a77c2fda458fc67028cb444b3b3fdcdf36b168d89ceb7286630d2fc76b21a714i476/content

https://api.hiro.so/ordinals/v1/inscriptions/fc7e21fc4e8140100f5913a0e0d6ce1675b73298ba97de65ef0130169369f3dci421/content

Examples of more STX NFT Collectibles that do not display:

SPQ5CEHETP8K4Q2FSNNK9ANMPAVBSA9NN86YSN59.stxstone
SP1CE3NQXDKCJ2KEFFGCVFA5C196S9F0RRX93HY87.pizza-ninjas-on-sothebys
SP25W1B7YX3F20S598J4EXEE9HZ0XHY6PNVTT6FA3.trajan-endorse-v0_1_0

These are reported issues to Leather for reference:
https://github.com/leather-wallet/extension/issues/5236#
https://github.com/leather-wallet/extension/issues/5302

<img width="1152" alt="hiro2" src="https://github.com/hirosystems/explorer/assets/132958967/243d0d0e-be97-4dcb-84ad-933879a0321f">

![nft](https://github.com/hirosystems/explorer/assets/132958967/bc5e433b-e47f-4e59-ba84-d9ae7ebd1f54)

**Comment by andresgalante** [comment]
Is this a wallet issue?

**Comment by DeeList** [comment]
Thanks, Andres. I've forwarded your comment.

**Comment by brandonmarshall-tm** [comment]
Perhaps we should split the Ordinals & Stacks issues into their own individual issues @DeeList?

Regarding the Stacks NFT issues, it looks to be more of an explorer issue.

For example I can see this Stacks NFT in my collections on Gamma: https://stacks.gamma.io/collections/pizza-ninjas-on-sothebys/2

But not in Hiro Explorer: https://explorer.hiro.so/token/SP1CE3NQXDKCJ2KEFFGCVFA5C196S9F0RRX93HY87.pizza-ninjas-on-sothebys?chain=mainnet

**Comment by brandonmarshall-tm** [comment]
Adding additional example of a Stacks NFT not showing in Hiro:

https://api.hiro.so/metadata/v1/nft/SP2XMGYYTA1KRBKBYJHTW8CFWB2QYZKZE4BMHG3PJ.honorary-mojo/26
https://stacks.gamma.io/collections/honorary-mojo/26

**Comment by markmhendrickson** [comment]
@DeeList let's split this issue into two for the [Ordinals API](https://github.com/hirosystems/ordinals-api) and [Stacks Blockchain API](https://github.com/hirosystems/stacks-blockchain-api) repos specifically, since it seems like we're dealing with missing data from each of these APIs?

The explorer would fail to show them (just as the wallet fails to show them) if it also can't retrieve data from the relevant API. So this wouldn't be an explorer issue per se.

**Comment by brandonmarshall-tm** [comment]
Here is another user report, basically none of these are displaying in Leather and also not displaying correctly in Hiro (but do display correctly on Gamma)

https://explorer.hiro.so/address/SP2QP89JZACDW214Q5H2N3WJWXV5N5GKMA7HNPZ41?chain=mainnet
https://stacks.gamma.io/fortnakamoto.btc

**Comment by brandonmarshall-tm** [comment]
Created a new Stacks-specific issue for this: https://github.com/hirosystems/explorer/issues/1634

**Comment by markmhendrickson** [comment]
@brandonmarshall-tm it may be best to file all Hiro data-related issues in [their API repo](https://github.com/hirosystems/stacks-blockchain-api/), since the wallet and explorer both pull from it?

**Comment by brandonmarshall-tm** [comment]
Cross-posted to https://github.com/hirosystems/stacks-blockchain-api/issues/1982

**Comment by brandonmarshall-tm** [comment]
I think this issue can be resolved! The only NFTs not showing are ones not following SIP-016 standard, but the main ones that were previously missing (like Nakamojo and Project Indigo) are displaying now.

**Comment by DeeList** [comment]
There are some older NFTs and newer like MOJO and Stacking DAO NFTs that still do not display in Leather.


<img width="258" alt="nfts" src="https://github.com/hirosystems/explorer/assets/132958967/13d884d1-3f9a-4e4f-a0e3-54b1e31773dd">

**Comment by DeeList** [comment]
[New issue opened Stacks-Blockchain-API](https://github.com/hirosystems/stacks-blockchain-api/issues/2004)
