### ISSUE TITLE
Fix missing/static data on blocklist

### ISSUE THREAD

**Issue by BLuEScioN** [hirosystems/explorer#1603]
The # of txs in a burn block is inaccurate because currently we can only determine this if we query for ALL stx blocks in a burn block, which would be very expensive. We are waiting on the API team to add the stx transactions for a btc block to the burnblock endpoint 
https://github.com/hirosystems/stacks-blockchain-api/issues/1960

You can also see that the average block time given is hardcoded right now. The API team just finished adding average block times per time interval and per block. So we can update the code to use the available data now.
https://github.com/hirosystems/stacks-blockchain-api/pull/1963
https://github.com/hirosystems/stacks-blockchain-api/pull/1962

![Image](https://github.com/hirosystems/explorer/assets/20312835/6c275f0b-c517-4796-b0c2-97f5aa705684)
Thi

![Image](https://github.com/hirosystems/explorer/assets/20312835/d522a047-f5c9-41da-8b92-4d37ee54d77e)

**Comment by zone117x** [comment]
Sounds like issue https://github.com/hirosystems/stacks-blockchain-api/issues/1981 ? Which should be resolved if using the latest beta version of the client library.

**Comment by smcclellan** [comment]
Closing as the above comment seems to fix the issue. A new stable client release will come soon.
