### ISSUE TITLE
Modify "STX supply" wording on homepage stat bar

### ISSUE THREAD

**Issue by eugeniadigon** [hirosystems/explorer#1619]
<img width="308" alt="Screenshot 2024-05-09 at 15 51 50" src="https://github.com/hirosystems/explorer/assets/78865845/2b9455f5-32e2-431a-a86b-00133124d44a">

We should remove the `(% is unlocked)` text on the homepage, since that number is not related to stacking, and using "unlocked" as wording can cause confusion.

Context:
> the explorer home page is showing the total liquid stx divided by the year 2050 estimated supply: STX Supply: 1.46B / 1.82B, 80.25% is unlocked -- these numbers come from the /extended/v1/stx_supply endpoint. this is unrelated to stacking/pox and unrelated to stx locked from stacking/pox. IIRC the term unlocked was used here because stx become liquid from both mining and stx unlocking on a vesting schedule.
> if you want to show STX locked from stacking/pox then use the /v2/pox endpoint values current_cycle.stacked_ustx and total_liquid_supply_ustx.

I propose we modify that box to be:

<img width="298" alt="Screenshot 2024-05-09 at 15 55 13" src="https://github.com/hirosystems/explorer/assets/78865845/26e1c05a-8be5-4b03-930d-b972167ef857">

**Comment by 314159265359879** [comment]
instead of "1.82B total supply" a more accurate description would be "1.82B expected total supply in 2050"
