### ISSUE TITLE
Location data view for the Signer Dashboard

### ISSUE THREAD

**Issue by saralab** [hirosystems/explorer#1621]
Include a Signer location map on the Signer Dash to show the publicly available Signers. 
<img width="1421" alt="Screen Shot 2024-05-10 at 1 27 53 PM" src="https://github.com/hirosystems/explorer/assets/264896/15560f09-dd78-4138-9dca-b8b8d1d8e82e">

The source for this data will be from the crawler @zone117x is working on that will be updated once every day.

**Comment by eugeniadigon** [comment]
> Is this enough info to get started on the designsHappy to meet to discuss.?


Thanks for researching this Nick, I started working on the design, let's review on the next weekly
