### ISSUE TITLE
Charisma (CHA) token metadata refresh request

### ISSUE THREAD

**Issue by r0zar** [hirosystems/explorer#1647]
Requesting a token metadata refresh for Charisma fungible token.

SP2D5BGGJ956A635JG7CJQ59FTRFRB0893514EZPJ.dme000-governance-token

https://explorer.hiro.so/txid/0x290c36921ad381c678fdb899afef196d9fbd911ed60c2e43f0df5cbab9fe805a?chain=mainnet

**Comment by andresgalante** [comment]
@rafaelcr can you take care of this one please 🙏

**Comment by rafaelcr** [comment]
Done ✅
