### ISSUE TITLE
Option to remove $ price info

### ISSUE THREAD

**Issue by aryzing** [hirosystems/explorer#1678]
The btc / stx price indicator can be a bit of a distraction. Would be great to be able to hide the price feed on the top right of the page, as well as all the $ equivalents sprinkled throughout the UI.

**Comment by eugeniadigon** [comment]
Thanks for the recommendation! We'll take it in account for new improvements

**Comment by andresgalante** [comment]
Hi @aryzing, I am curious why it is distracting and distracting from what?

**Comment by aryzing** [comment]
@andresgalante the explorer seems more of a technical tool to get info on blocks, signers, transactions, contracts, and other technical insights on Stacks. I'm not sure the $ data is really relevant for day to day operations with the explorer, though I understand some users may want to have it, which is why I'm suggesting a toggle of some sort. 

Would be fine too if there was a whole new page with price history, volume, and other economic indicators. Having a mix of techincal and economic data in the same place doesn't make sense for all use cases.

Using mempool.space as reference,

- BTC price is not displayed anywhere 
- Amounts can be toggled b/w $, BTC, sats

**Comment by andresgalante** [comment]
Thanks for the clarification @aryzing 

We'll consider it
