### ISSUE TITLE
Desktop notifications

### ISSUE THREAD

**Issue by andresgalante** [hirosystems/explorer#1679]
For any section of the Explorer which contains an operation, provide an option to receive a desktop notification once an operation completes.

**Comment by eugeniadigon** [comment]
> For any section of the Explorer which contains an operation, provide an option to receive a desktop notification once an operation completes.

What do you mean with operation? a transaction?

**Comment by andresgalante** [comment]
Yeah, whenever a tx changes status, we can trigger a notification

**Comment by ginny-d** [comment]
@BLuEScioN , here are some mock ups to add the browser notifications feat to the UI:

Let me know what you think!

https://www.figma.com/design/31q1g27k69z1yXb6r6vrRD/Stacks-Explorer-Working-File?node-id=9012-75005&t=Fsn3jdLfaj3acarp-1

<img width="1440" alt="Tx-ID" src="https://github.com/user-attachments/assets/b11df4c1-2ff0-4a86-816a-5424a387c0c5">
<img width="1440" alt="Hover" src="https://github.com/user-attachments/assets/8759eb32-3e84-4bef-8eed-4a0436091176">
<img width="1440" alt="Notifications ON" src="https://github.com/user-attachments/assets/e14be2c9-8965-4cae-bf17-4a91d3479bf1">
