### ISSUE TITLE
Transaction events not shown

### ISSUE THREAD

**Issue by badonyx** [hirosystems/explorer#1705]
Events are not getting shown on the transaction page.

Example: https://explorer.hiro.so/txid/0x183afb503463bf3e3357d446f0c06096eb0f1c5d8b6677c7c5706f0575b41f81?chain=mainnet

<img width="928" alt="Screenshot 2024-07-02 at 10 38 54 AM" src="https://github.com/hirosystems/explorer/assets/110633279/f8dd841f-5a0d-43f6-8091-7ef2e13b3a64">

**Comment by andresgalante** [comment]
I can't reproduce it:

<img width="914" alt="image" src="https://github.com/hirosystems/explorer/assets/1832037/7f3b4a2a-68bc-4aa1-8cdf-ea692c2f23f5">

**Comment by badonyx** [comment]
Seems to be working again.
