### ISSUE TITLE
Disable, cache or lazy load `stxPrice` endpoint.

### ISSUE THREAD

**Issue by LNow** [hirosystems/explorer#1707]
`stxPrice` endpoint is very slow and makes whole explorer unusable.
Why do we have to wait sometimes almost a minute to see the data that were downloaded in fraction of that time?
<img width="1728" alt="image" src="https://github.com/hirosystems/explorer/assets/829210/96e15cae-6389-4462-8388-6b699d0457ba">
<img width="1728" alt="image" src="https://github.com/hirosystems/explorer/assets/829210/55c22d10-b5ba-4a0c-9e01-8e06cd5989e7">
<img width="1728" alt="image" src="https://github.com/hirosystems/explorer/assets/829210/e52bf53f-ee8d-4001-a034-8a59102270f2">

Please disable this endpoint, cache it properly or lazy load it instead of slowing down whole UI.

**Comment by andresgalante** [comment]
@He1DAr Would you mind taking a look at this one please?

**Comment by He1DAr** [comment]
Consolidated requests to trigger one request per day, will still be somewhat problematic in cases where there's a list with many transactions from different days. We'll need a batch endpoint to fully resolve this.
