### ISSUE TITLE
Incoming token transfers not displayed on wallet with token balances

### ISSUE THREAD

**Issue by 314159265359879** [hirosystems/explorer#1709]
This address has token balances but no transaction history of how the tokens got in the wallet. 

https://explorer.hiro.so/address/SP29H5FH57AZVJSBWHCTJB5ATS2ZAH9SXN1XJDNK?chain=mainnet
![image](https://github.com/hirosystems/explorer/assets/33360391/30afd866-20bc-419f-a727-346f86c0fe6a)

Transaction ID n.a.
Address SP29H5FH57AZVJSBWHCTJB5ATS2ZAH9SXN1XJDNK
Block#  n.a.

Expected: Transaction history to display the incoming token transfers.

**Comment by andresgalante** [comment]
@smcclellan, would you be okay with taking a look at this? The API is returning no tx

**Comment by BLuEScioN** [comment]
The API is returning no txs. 

https://api.mainnet.hiro.so/extended/v2/addresses/SP29H5FH57AZVJSBWHCTJB5ATS2ZAH9SXN1XJDNK/transactions

returns a 404 with 

{
    "errors": "Address not found"
}

I think this task should be investigated from the API's side first
