### ISSUE TITLE
zststx rewards token

### ISSUE THREAD

**Issue by cmorel27** [hirosystems/explorer#1717]
**Describe the bug**
A clear and concise description of what the bug is.  I received 12.4k of a token called zststx in my leather wallet. Below is the transaction and block #. Is this a scam?

Transaction ID : 0x0ed32844429ff6c233115d8edf25237f2d199da492b4023e979db7f7a382c36aAddress 
Block# 849788
contract:   SP32Z0ZT2KS49B3ERXNG002NWTDC9BA2SYT1EPSS0.zststx

**Comment by andresgalante** [comment]
This isn't an Explorer issue.

Please ask for community support on the #support channel in [Discord](https://discord.gg/FdhdMUrZ).
