### ISSUE TITLE
Feedback on 3.0 Block View

### ISSUE THREAD

**Issue by saralab** [hirosystems/explorer#1721]
1. STX Icon + STX Blocks 
At first glance when you see the [Blocks View under the 3.0 Testnet](https://explorer.hiro.so/blocks?chain=testnet&api=https://api.nakamoto-1.hiro.so), it can be misleading to see only the first STX Block within the BTC Block to have the STX icon next to it. At first I presumed the rest of the blocks in the list were transactions within the STX block [#121443](https://explorer.hiro.so/block/0xa617d0247c3c7c45ed3ce556d34533f10cc634a49b108daff53cc013a3169395?chain=testnet&api=https://api.nakamoto-1.hiro.so). 
Update this view to include STX icon next to all the STX Blocks. 
<img width="1241" alt="Screenshot 2024-07-08 at 11 42 16 PM" src="https://github.com/hirosystems/explorer/assets/264896/9659beba-74e4-4958-90a6-4cc835b38d05">

2. The first BTC block in the list shows the expanded view of the STX blocks and the following BTC blocks are collapsed and show the total STX blocks count. When I click on the BTC block, I expected it to expand in the same screen , instead it takes me to a new screen with the detailed block view. 
Update this to expand/collapse the STX Blocks within the  BTC block in the same screen  
<img width="1225" alt="Screenshot 2024-07-08 at 11 55 03 PM" src="https://github.com/hirosystems/explorer/assets/264896/746dbbf9-97d1-4a72-9c4b-e427c52c9a43">

<img width="1397" alt="Screenshot 2024-07-08 at 11 48 08 PM" src="https://github.com/hirosystems/explorer/assets/264896/a1932c7e-60a2-4ab4-b22c-e2537868585f">

**Comment by eugeniadigon** [comment]
Thanks for the feedback, Sarala

Here are a couple of comments from Design:

1) I recommend against adding an STX icon next to every block. It can look repetitive and redundant:

<img width="1440" alt="Blocks" src="https://github.com/hirosystems/explorer/assets/78865845/e513fd73-1a22-48dd-bc8e-94513c396f19">
-

Instead, I suggest adding the STX icon next to the first and the last Block of the string, and colouring the circles in purple, as a more minimal visual hint:

<img width="1440" alt="Blocks-1" src="https://github.com/hirosystems/explorer/assets/78865845/730aa7fb-85a7-483d-92bc-6fee43c5a13c">

-
2) Engineering can give more context and confirm why this works this way. My understanding is that the reason is to improve performance.

**Comment by BLuEScioN** [comment]
I agree having a STX icon for each dot is a little overwhelming. I would even go as far as to say just making the dots all purple  after the first one is enough visual communication to tell that evreything else is a STX block, too.

I'll add my 2 cents about #2. 

Yes, we are only populating the first btc block with stx blocks for performance reasons. We are intentionally trying to NOT make additional requests to the API as well as make sure we are not hitting the API request limit. 

We can add the click functionality in order for the user to be able to load stx blocks for the btc block, and only load the stx blocks when the user clicks to expand the btc block. However, is there a specific use case where users will be using this page to inspect multiple btc blocks for stx blocks?

**Comment by andresgalante** [comment]
In the default view, we should at least see the first and last STX blocks within each BTC block; otherwise, the list of BTC blocks provides no valuable information.

**Comment by ginny-d** [comment]
Re:

> The first BTC block in the list shows the expanded view of the STX blocks and the following BTC blocks are collapsed and show the total STX blocks count. When I click on the BTC block, I expected it to expand in the same screen , instead it takes me to a new screen with the detailed block view.
Update this to expand/collapse the STX Blocks within the BTC block in the same screen

If we expand the view on the same page we would have hundreds (if not thousands?) of STX blocks on a string showing up, and the scroll would be significantly long. This is why the initial proposal was to open on a new page, which also gives us the ability to generate a specific URL to share/link to a specific set of STX block strings ([which would be this page](https://www.figma.com/design/31q1g27k69z1yXb6r6vrRD/Stacks-Explorer-Working-File?node-id=7589-52715&t=z1hx27yf5qZ3l8eM-1)). If we expand the string on blocks on the Blocks page, we'd lose this.

@Sarala Is there a strong use case for why we'd need to show the full list of STX blocks of a given BTC blocks on the Blocks page?

------
If we decide to move forward with this, I'd suggest loading 10 or 20 blocks at a time, and having a button for "load # more blocks". I'll prepare a mock-up once I hear back with more details

**Comment by BLuEScioN** [comment]
@ginny-d 
 One issue I think will come up with the way that we are showing the first and last block is that if we add functionality to load blocks, then it's possible for the block count badge to disappear, and that's the only link the ui to go to the block page. What if just include the range of stx blocks included in the btc block somewhere else so we can avoid this? Perhaps we can make it additional information that is shown once the user hovers over the block count badge? (edited)

**Comment by ginny-d** [comment]
> One issue I think will come up with the way that we are showing the first and last block is that if we add functionality to load blocks, then it's possible for the block count badge to disappear, and that's the only link the ui to go to the block page. What if just include the range of stx blocks included in the btc block somewhere else so we can avoid this? Perhaps we can make it additional information that is shown once the user hovers over the block count badge

I see what you mean. However, I still think that adding a 'load more blocks' feature to this view may not be beneficial, as with Nakamoto we'll have hundreds or thousands of STX blocks. I find it difficult to think of a scenario where users would find value in scrolling through a long list of blocks in this limited view.

Instead, I propose creating a separate page dedicated to displaying the set of STX blocks within a BTC block. We could also make the BTC block number itself a clickable link to this new 'set of STX blocks' page.

**Comment by ginny-d** [comment]
Here are the revised designs with the "Load more" button:

https://www.figma.com/design/31q1g27k69z1yXb6r6vrRD/Stacks-Explorer-Working-File?node-id=9149-70259&t=y1qgeQLnpHD1NJBg-1

<img width="1440" alt="Blocks" src="https://github.com/user-attachments/assets/6af98321-4306-424b-803e-728e73764d24">

**Comment by andresgalante** [comment]
Thank you for all the changes and the discussion here 🙏 

@ginny-d I'd like to have the information about the reminding blocks, would it be possible to keep the "+123 blocks" somewhere?

And, to simplify implementation, it'd be better to make all BTC blocks the same as the first with 10 STX blocks per BTC block

What do you think?

**Comment by BLuEScioN** [comment]
Thanks @ginny-d for the design. Will have this up today.

I do think it's good to keep the "+X blocks" in the pill, too, as well as making all the btc blocks the same

**Comment by ginny-d** [comment]
> Thanks @ginny-d for the design. Will have this up today.
> 
> I do think it's good to keep the "+X blocks" in the pill, too, as well as making all the btc blocks the same
> 
> Also, do we really need the button to go to the blocks page? The link is also embedded in the btc block height and hash

I don't think we absolutely need the link, but as it is, it's not super obvious. We can wait until we see if there's feedback around it or a strong request for it.



Some feedback:
- On **Blocks** page, the first "+1 block" is on black, while the others are purple (interactive):
<img width="264" alt="Screenshot 2024-08-05 at 14 35 44" src="https://github.com/user-attachments/assets/8e4112da-13c6-423f-9795-0369897cbb50">
<img width="261" alt="Screenshot 2024-08-05 at 14 35 34" src="https://github.com/user-attachments/assets/958c25ee-37f2-46c0-9d11-064d3fc3d0cc">

- There has been a regression with the BTC icon displaying small in the STX block page:
<img width="437" alt="Screenshot 2024-08-05 at 14 36 29" src="https://github.com/user-attachments/assets/a0674e31-29bf-419e-be47-7d84aaf1e0a3">

**Comment by andresgalante** [comment]
This was shipped
