### ISSUE TITLE
Remove email capture on the Stacks Explorer

### ISSUE THREAD

**Issue by max-crawford** [hirosystems/explorer#1723]
We are migrating to a new email service provider in the month of July. You can learn more about that decision [here](https://www.notion.so/hiropbc/Email-Migration-Iterable-Klaviyo-046d303307ef4b3fb3486e519da06b0e).

One thing this migration means is that we need to replace all email capture forms in order to push email data to the new system. After discussion with @eugeniadigon, we are agreed that the best approach for the Stacks Explorer is to simply remove the email capture altogether, and we can re-add it later after we roll out v2 of the Stacks Explorer.

**Comment by eugeniadigon** [comment]
@max-crawford Is there a deadline you need this by?

**Comment by max-crawford** [comment]
Anytime before July 30th is good. If it happens after that, any users who subscribe will not be added to our database.
