### ISSUE TITLE
Correcting the assignment of Signer key from Blockdaemon to Chorus One

### ISSUE THREAD

**Issue by shaktistacks** [hirosystems/explorer#1746]
Hi @andresgalante 

Can you please change the following on the [signer page of the explorer](https://explorer.hiro.so/signers?chain=mainnet)

Signer PubKey:
0x02254a34747123978819f2a90506f76cb057fe3fbff6d8721a0d9cf8e9412d0e60

Has been incorrectly assigned to [Blockdaemon](https://www.blockdaemon.com/), Can you please change that to[ Chorus One](https://chorus.one/) ? 

Chorus One STX Address: SP2A2HGHMS3EQYRS8E0ACQ64DMS3P6C57A6VBE45V 
Signer pubkey:  0x02254a34747123978819f2a90506f76cb057fe3fbff6d8721a0d9cf8e9412d0e60

For Blockdaemon, the correct entry will be
STX Addresses : SP21D6BW36TSGWAZS8K4JAJVTNXWKQN9G3TH5MG6A(need to add this address)
Signer Pubkey:  03a541c1ec2cfb32da48cfadf439c9b2f27d166bbffa18a178c7a6a0d54cfa7813(Already included as a StackingDAO Pool)

Thanks!

**Comment by andresgalante** [comment]
Hi @shaktistacks yeap, we'll do it today

**Comment by BLuEScioN** [comment]
@shaktistacks 

I had this for BlockDaemon (StackingDAO pool)
 '0x03a541c1ec2cfb32da48cfadf439c9b2f27d166bbffa18a178c7a6a0d54cfa7813': {
    poolOperator: 'SP4SZE494VC2YC5JYG7AYFQ44F5Q4PYV7DVMDPBG.stacking-pool-signer-blockdaemon-v1',
    name: 'Blockdaemon (StackingDAO)',
  }
  Is SP21D6BW36TSGWAZS8K4JAJVTNXWKQN9G3TH5MG6A supposed to replace SP4SZE494VC2YC5JYG7AYFQ44F5Q4PYV7DVMDPBG.stacking-pool-signer-blockdaemon-v1? 
  And just to clarify there is no BlockDaemon signer outside of its staking pool with StackingDAO, right?

**Comment by shaktistacks** [comment]
@BLuEScioN 

its not suppose to be replaced actually,  you can keep the stackingdao pool as is, but there's another pool that is operated by blockdaemon with the same signer i.e.

STX Address: SP21D6BW36TSGWAZS8K4JAJVTNXWKQN9G3TH5MG6A
Signer Key:  0x03a541c1ec2cfb32da48cfadf439c9b2f27d166bbffa18a178c7a6a0d54cfa7813

**Comment by BLuEScioN** [comment]
I don't think it's possible to have 2 signers with the same signing key. That doesn't make much sense. Are you sure BlockDaemon has two signers, and if so that they have the same signing key?

**Comment by shaktistacks** [comment]
@BLuEScioN you're correct on that, so lets remove the other blockdaemon that has the * as that has the wrong Signer key

0x02254a34747123978819f2a90506f76cb057fe3fbff6d8721a0d9cf8e9412d0e60 belongs to Chorus One actually, this is their second signer
