### ISSUE TITLE
Hiro Explorer - With 5 sec block times, let's add the date to the explorer page rather than days, months, years ago...

### ISSUE THREAD

**Issue by kurtgrela** [hirosystems/explorer#1824]
With 5 sec block times, let's add the date to the explorer page rather than showing txn times as days, months, years ago...

**Is your feature request related to a problem? Please describe.**
Explorer (https://explorer.hiro.so) displays an unconventional days, months and years ago to show time and the person relies on the hoover over to the see the exact date and time.

**Describe the solution you'd like**
Add date and time to explorer rather than hoover over.

**Describe alternatives you've considered**
None

**Additional context**

**Comment by andresgalante** [comment]
On Satcks, Mainnet is not Nakamoto 3.0 ready, and it doesn't have fast blocks.

there is a new view for blocks for 3.0 that you can preview in Nakamoto testnet https://explorer.hiro.so/blocks?chain=testnet&api=https://api.nakamoto.testnet.hiro.so but it still shows the relative time.

We'll take this feedback of using absolute time stamps for the redesign we are working on.

**Comment by andresgalante** [comment]
Hi @kurtgrela, if you're okay with it, I'll go ahead and close this issue. Feel free to reopen it if you have any more comments.
