### ISSUE TITLE
Hiro Explorer - Export as CSV button exports txns on screen - why not export all?

### ISSUE THREAD

**Issue by kurtgrela** [hirosystems/explorer#1825]
**Is your feature request related to a problem? Please describe.**
My address has 750+ txns.  With 30 txns every time I click the 'load more txns" button (https://explorer.hiro.so/), I need to press it 25 times to get all my txns and for the export to csv button to get the data.

**Describe the solution you'd like**
Either add a button at the bottom of the explorer to "load all txns" rather than "load more txns", reconfigure the export button to export all txns, and/or add page numbers at the button and allow people to choose the display 25, 50, 100, 250, 500, and/or All - (Not sure why 30 was selected.)

**Describe alternatives you've considered**
Or is there an easier way to get the same data?

**Additional context**

**Comment by andresgalante** [comment]
Hi @kurtgrela, this is a known limitation and something we need to work on. You can use FastStx to get a CSV https://fatstx.github.io/transactions
