### ISSUE TITLE
Filter not showing after loading more transactions

### ISSUE THREAD

**Issue by obycode** [hirosystems/explorer#1828]
**Describe the bug**
When filtering transactions, if I click "Load more transactions", the filter is still in place, but the UI no longer shows it, which could be confusing.

**To Reproduce**
1. Go to https://explorer.hiro.so/transactions?chain=testnet&api=https://api.nakamoto.testnet.hiro.so
2. Click on 'Filters' and select 'Tenure change'
3. Click 'Load more transactions
4. Note that the filter is no longer showing

**Expected behavior**
The UI should continue to show the active filter.

**Screenshots**
![filter](https://github.com/user-attachments/assets/83f38006-165f-4920-9063-cda1ca1e4336)

**Desktop (please complete the following information):**
 - OS: macOS 14.6
 - Browser: Safari
 - Version: 18.0

**Comment by BLuEScioN** [comment]
https://github.com/hirosystems/explorer/pull/1835
