### ISSUE TITLE
Fixing Signer list on explorer: Multiple signer for one Partner

### ISSUE THREAD

**Issue by shaktistacks** [hirosystems/explorer#1838]
Hi @andresgalante 
Xverse is running two signers
 
signer 1 pubkey: 0x02877ce29ba35458b827a6ea18510b9058ae4c30e2c33d288f2982c13497caec6e
signer 2 pubkey: 0x0302328212d5e430a8a880f8e2365a8f976ee50490ff030c106866c0b789eae91a

Signer 1 address: SP3WEKWTCJ2FXTMAQK674GHEWTJKPP6KFH0D38T7S
Signer 2 address: SP3WEKWTCJ2FXTMAQK674GHEWTJKPP6KFH0D38T7S

Signer 1 Stacked amount: 117697539673412 ustx
Signer 2 Stacked amount: 2475531962270 ustx

Pool operator address for both signers: SPXVRSEH2BKSXAEJ00F1BY562P45D5ERPSKR4Q33

Hiro API is always showing the following which is wrong:
"pooled_stacker_count": 0  for Signer 1
"pooled_stacker_count": 5998 for signer 2

Can we have this fixed in explorer? there's only one signer listed under xverse with no associated addresses

**Comment by andresgalante** [comment]
@BLuEScioN is this done?
