### ISSUE TITLE
Add Nakamoto Mainnet Modal Announcement

### ISSUE THREAD

**Issue by elenananana** [hirosystems/explorer#1870]
**Describe the solution you'd like**
Add Nakamoto 3.0 Modal for Naka activation. It should be up for a week. 

**Additional context**
Copy:

Nakamoto Activation
### Nakamoto 3.0 is live on Stacks Mainnet
[Image]
![Image](https://github.com/user-attachments/assets/054233b9-188e-48cf-b41e-e8e9503cdf51)

- Button Copy: Experience Fast Blocks and Bitcoin Finality
- Button Link: Takes you to the Explorer

- Secondary Copy: Learn more about Nakamoto on Mainnet
- Secondary Copy Link: Stacks Foundation Announcement

**Comment by BLuEScioN** [comment]
@elenananana Shouldn't mainnet be the selected dropdown item in the image/ui?

**Comment by andresgalante** [comment]
Nick, the image is not ready yet, Ginny will have it tomorrow

**Comment by ginny-d** [comment]
@BLuEScioN Please use this image:

![Image](https://github.com/user-attachments/assets/cff2c1f5-5490-40f5-b906-884f321b740e)

Mock up:

![Image](https://github.com/user-attachments/assets/80345051-c268-4b11-9e1a-ff04f62fc62a)
