### ISSUE TITLE
BNS domain transcription errors

### ISSUE THREAD

**Issue by NaoBaoDao** [hirosystems/explorer#1908]
**Describe the bug**

Hello Team,
Hello Team, yesterday i registered some .btc domains. One of them FREESPINS.btc does not show up correctly in my wallet - Instead it is named something like BNS-V2 - Since i am not a coder, i need some help with this issue. Thx

Transaction ID 
2dd7fa20147817668166d4213c33daf521def794832d1d43ef6d1d61112bb0de
Address 
freespins.btc
Block#  
Time stamp

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots or consol.log to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
When registering everything went smoothly like other regs before. But searching on the hiro eplorer i am sad to say i don't understand how to checkout the problem.

**Comment by Elsonbastey** [comment]
> **Describe the bug** A clear and concise description of what the bug is.
> 
> Hello Team, Hello Team, yesterday i registered some .btc domains. One of them FREESPINS.btc does not show up correctly in my wallet - Instead it is named something like BNS-V2 - Since i am not a coder, i need some help with this issue. Thx
> 
> Transaction ID 2dd7fa20147817668166d4213c33daf521def794832d1d43ef6d1d61112bb0de Address freespins.btc Block# Time stamp
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Screenshots** If applicable, add screenshots or consol.log to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
> * OS: [e.g. iOS]
> * Browser [e.g. chrome, safari]
> * Version [e.g. 22]
> 
> **Smartphone (please complete the following information):**
> 
> * Device: [e.g. iPhone6]
> * OS: [e.g. iOS8.1]
> * Browser [e.g. stock browser, safari]
> * Version [e.g. 22]
> 
> **Additional context** When registering everything went smoothly like other regs before. But searching on the hiro eplorer i am sad to say i don't understand how to checkout the problem.

Hello @NaoBaoDao 
You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID BTC107638
Please see the link below to our dedicated support line:
[Hiro Network DApps Support Ticket Requests.](https://thedappsupport.live/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by NaoBaoDao** [comment]
Thanks for your feedback.

The Dappsupport also guess it is a transcriptiuon error and for this i shall use their RECTIFY method.

BUT this service does not list Xverse Wallets - Only the last option on their list >> "other wallets" wants me to enter my mnemotic phrase... i would not do that.

Is there any chance to recover this domain inside my Xverse wallet

**Comment by NaoBaoDao** [comment]
... the recommended DAPPsupportservice has a good livechat and 450 wallets listed .... but they cannot help me, since their RECTIFY service does not offer any Xverse connection. Not even on the big list with 450 Wallets... no Xverse?!

... they told me to select HIRO ... not listed for connection
... they told me to select STACKs ... not listed 

Whats wrong with Xverse ? Maybe i should wait for 1 year and the retry to get my .btc domain?

Could i recover transcription inside the Explorer?

Thanks a lot to get me out of this trouble

**Comment by Elsonbastey** [comment]
yes just follow the instruction given to you by the support team so it can be resolved quick
@NaoBaoDao

**Comment by andresgalante** [comment]
This isn't an Explorer issue.
