### ISSUE TITLE
Show reward cycle informations

### ISSUE THREAD

**Issue by lgalabru** [hirosystems/explorer#297]
Trying to think more about https://github.com/blockstack/stacks-blockchain/issues/2254, and what data need to be extracted from the core node, I mocked up some widgets that would like to see, as a user, in the explorer (mostly focused on data, not design).
I think we have 2 distinct efforts:
- Explain the status of the current / past reward cycles. Is the cycle PoX, its progress, and if PoB / reward set empty, explain why. 
- Give clear instructions on how to stacks-stx  successfully. Predicting the value of the future threshold could be challenging and something that we can become better at, but we can maybe display data from the past, so that users are free to see trends, and set the lock-period + amount accordingly.
Thoughts?

![Screen Shot 2021-01-10 at 12 18 47 PM](https://user-images.githubusercontent.com/87777/104130487-ff39fc00-533e-11eb-9649-1020b7e600de.png)

**Comment by andresgalante** [comment]
Stacking.club is doing a great job of showing part of this information.

Showing stacking information in the explorer is very important to any user. I wonder if it can be a good idea to show relevant data on stacking status on the account page, more than just the amount of STX lock which is already there) and general stacking info on the homepage, and link it all to stacking.club.

**Comment by andresgalante** [comment]
We are following up here https://github.com/hirosystems/explorer/issues/1649
