### ISSUE TITLE
Show consensus information

### ISSUE THREAD

**Issue by lgalabru** [hirosystems/explorer#321]
Following up on https://github.com/blockstack/explorer/issues/297, in a similar vein, we should try to be as transparent as possible on our leader election process, so trust can be built with miners.

What's our take on giving some real estate in block pages?
Again, the UI and colors are not the right ones, but as a miner, I think that's the kind of data that would love to see. 

![Screen Shot 2021-01-15 at 1 09 35 PM](https://user-images.githubusercontent.com/87777/104762978-3f302300-5733-11eb-8926-4df1741a8f60.png)

Thoughts?

**Comment by aulneau** [comment]
@lgalabru this is so helpful! I love these kinds of contributions 👍 

I would be so happy to implement this. It really depends on if/how much of this data is available for me to consume and display :) if it is ready, do let me know, otherwise once it's implemented in the node/api I'll get started.

**Comment by lgalabru** [comment]
For inspiration
https://tbtc.bitaps.com/2006717

**Comment by markmhx** [comment]
cc @xanbots since he may be interested in this for https://stxmining.club/ as well

**Comment by xanbots** [comment]
Thanks Mark. We already pull this information in for the mining monitor.

We'll have an API others can plug into as well, if that's at all useful to anyone else here.

**Comment by andresgalante** [comment]
This is a great idea. As we work on the blocks page we can take inspiration from the OnStacks Explorer

**Comment by chresko** [comment]
We may come back to this issue later.
