### ISSUE TITLE
Annotate known addresses (e.g. exchanges)

### ISSUE THREAD

**Issue by kyranjamie** [hirosystems/explorer#339]
**Feature request**

Would be really cool to keep a list of known addresses and annotate these within the explorer; primarily exchanges.
I think most have 1 deposit address and use memo to differentiate depositors, rather than an address per user, so this should make it pretty doable.

**Comment by aulneau** [comment]
Yeah this sounds great, curious how we'd uncover this info?

**Comment by kyranjamie** [comment]
Think it'll just become apparent over time. We know `SPX8T06E8FJQ33CX8YVR9CC6D9DSTF6JE0Y8R7DS` is Kucoin.

**Comment by andresgalante** [comment]
Examples from Etherscan are:
https://etherscan.io/address/0xaa13543ef348879aa5adb3aa5dc4a1665863670d
https://etherscan.io/address/0xf3ae5d769e153ef72b4e3591ac004e89f48107a1

**Comment by friedger** [comment]
Here is a list of transaction types that includes labels for known addresses:
https://github.com/FatStx/FatStx/blob/main/src/bo/XactnTypes.js
