### ISSUE TITLE
Provide explanatory information on pending transaction page

### ISSUE THREAD

**Issue by kantai** [hirosystems/explorer#340]
There have been a number of issues reported about "long pending transactions", where the transaction itself turned out to have a too-high nonce. For example, if a user submits a transaction from an account A, where the next expected nonce for A is `1`, but the transaction sets `2`, the transaction will be accepted to the mempool, but it will _never_ be mined until a transaction with nonce `1` is broadcasted and mined. This behavior is expected, and allows users to submit multiple pending transactions before the first transaction is mined.

However, something that would help users is some more information on the explorer about nonces.

For example, if a pending transaction has a nonce that wouldn't be accepted, the pending transaction page on the explorer could display a message like:

"This transaction's nonce is higher than the next expected nonce for this account, this transaction will not be mined until the nonce is incremented by another transaction"

**Comment by markmhx** [comment]
I've modified this title to include even broader explanatory information about pending transactions, inclusive of nonce guidance but also other factors detailed here: https://forum.stacks.org/t/transactions-in-mempool-best-practices-and-known-issues/11659

We could essentially organize the information found in that forum post into a long-standing FAQ for linking from a pending transaction page. E.g.:

> Waiting for this transaction to be confirmed? Multiple factors affect the speed at which transactions are confirmed or otherwise remain pending. [Learn more](#)

**Comment by markmhx** [comment]
Another consideration here is that the underlying BTC block production may be slow and the pending transaction page could indicate whether its extended timing is related to that (per [a suggestion](https://discord.com/channels/621759717756370964/752876353572962314/844211817101787187) by @diwakergupta in Discord).

**Comment by markmhx** [comment]
Another idea here from https://github.com/hirosystems/explorer/issues/621 is that we display "the block time that a transaction was originally broadcast so that folks could have a better understanding of where they are in the 256 block pending window".

**Comment by chresko** [comment]
Closing this as it's a dup of transaction status work.
