### ISSUE TITLE
Transaction time "in X minutes"

### ISSUE THREAD

**Issue by agraebe** [hirosystems/explorer#343]
I observed that some transactions will be updated in the background (without a page refresh) and show a "in X minutes" timestamp, after being processed:

<img width="733" alt="Screen Shot 2021-01-23 at 11 31 02 AM" src="https://user-images.githubusercontent.com/1671228/105612307-1251c080-5d70-11eb-9d84-53a5a99e8b14.png">

**Comment by andresgalante** [comment]
This one should be fixed. I'll close it
