### ISSUE TITLE
Add high-level network statistics

### ISSUE THREAD

**Issue by markmhx** [hirosystems/explorer#345]
The Explorer may be a good place for a section with high-level network statistics for the purpose of helping people gauge overall network activity and health.

Possible stats for display per day, month, year, etc:

- Total transaction volume
- Total STX volume
- Total addresses with STX holdings
- Total fungible and non-fungible tokens held on network
- Total smart contracts deployed
- Total unique smart contracts executed
- Total usernames registered via BNS

This came up when meeting with @ades5.

**Comment by aulneau** [comment]
I agree completely, however this won't be possible to show in the explorer until it's exposed via the api / core node.

**Comment by GinaAbrams** [comment]
Came here to add something like this only to see the issue created already. 🙌🏼 Looking forward to this when possible! 😁

**Comment by friedger** [comment]
Total smart contracts deployed: https://stacks-node-api.mainnet.stacks.co/extended/v1/tx?type=smart_contract filtered by tx_status === "success"

**Comment by andresgalante** [comment]
@He1DAr I really like this idea. Does the API currently provides this data?

**Comment by andresgalante** [comment]
@rafaelcr If we wanted to implement this, do we have this data from the API?

**Comment by rafaelcr** [comment]
@andresgalante we have all the data necessary to calculate those stats but don't have the endpoints yet. We're tracking that effort here: https://github.com/hirosystems/stacks-blockchain-api/issues/1130
