### ISSUE TITLE
Ability to display whole JSON data

### ISSUE THREAD

**Issue by lgalabru** [hirosystems/explorer#346]
The explorer is a really neat product, and we need to pay attention to the real estate used for different fields.
I would love to be able to exclusively use the explorer for debugging stuffs, and having a button `View JSON` on the transaction and the block page, where we just the whole json returned by the API would be incredibly useful IMO.

**Comment by andresgalante** [comment]
Hi @lgalabru what do you mean by debugging, what would you be debugging?

I want to understand it to see if we can provide a better tool in the Explorer rather than raw JSON information

**Comment by andresgalante** [comment]
We'll close this issue for now since a json can be viewed from the inspector network tab. If we see other users ask for it we'll reconsider this feature.
