### ISSUE TITLE
List types not shown correctly in tx details

### ISSUE THREAD

**Issue by friedger** [hirosystems/explorer#353]
**Describe the bug**
Function arguments and tx result is not shown correctly, e.g. for https://explorer.stacks.co/txid/SP1K1A1PMGW2ZJCNF46NWZWHG8TS1D23EGH1KNK60.boom-nfts?chain=mainnet

**Expected behavior**
Show list of uints as a list
Show list of tuples as a list 

**Screenshots**
![Screenshot from 2021-01-29 10-26-35](https://user-images.githubusercontent.com/1449049/106257202-82eb5800-621c-11eb-9c06-6bef7f34f148.png)

**Comment by friedger** [comment]
List of responses are shown as `[object Object]
https://explorer.stacks.co/txid/0xdc5503a93c219823303fedcc0dd637cc7f10f66a246b06d37e5d4bc502b6d897?chain=testnet
![Screenshot from 2021-02-22 09-14-08](https://user-images.githubusercontent.com/1449049/108680589-59a5ab00-74ee-11eb-8918-f9d40c8aded3.png)

**Comment by andresgalante** [comment]
This is still an issue, here is an example on mainet

https://explorer.stacks.co/txid/0xd474a789d7cf292b8eb58720969bd52e5d6c40a992af52009f082b1058592d8c?chain=mainnet

**Comment by andresgalante** [comment]
This should be fixed
