### ISSUE TITLE
Add filters to the transaction list on the homepage

### ISSUE THREAD

**Issue by muneeb-ali** [hirosystems/explorer#355]
Is there a feature already in the works for this?

**Comment by diwakergupta** [comment]
As a workaround, you can go to the Transactions page and filter by `contract-deploy`s:

<img width="1181" alt="Screen Shot 2021-01-31 at 9 36 47 AM" src="https://user-images.githubusercontent.com/15990/106387472-e950b180-63a7-11eb-919e-c3e141be6342.png">

**Comment by muneeb-ali** [comment]
That works! Didn't see the filters on the main page but they are on the transactions page.

**Comment by andresgalante** [comment]
I'll rename this task to represent the improvment

**Comment by andresgalante** [comment]
While doing this we can revisit the tx list, which at the moment is the wrong abstraction.
