### ISSUE TITLE
Switch modal should respect custom network

### ISSUE THREAD

**Issue by friedger** [hirosystems/explorer#360]
**Describe the bug**
I am using stacks-local-dev with the explorer. When the switch network appears and asks whether to switch to testnet, my settings of the network to localhost:3999 is overwritten and I am seeing the state of the public testnet, not of my local network.

**Comment by friedger** [comment]
Furthermore, txs are not found

**Comment by Eshwari007** [comment]
This seems to be yet an issue
cc @fbwoolf

**Comment by fbwoolf** [comment]
> This seems to be yet an issue
> cc @fbwoolf

The switch network modal has been removed so how is this still an issue?

**Comment by Eshwari007** [comment]
Custom network model did not work hence I marked the issue as not resolved.If the issue is related ONLY to the switch network modal then its fixed but switching to custom network modal it isnt

**Comment by andresgalante** [comment]
@He1DAr You've worked on the network list, is this fixed?

**Comment by andresgalante** [comment]
This is fixed
