### ISSUE TITLE
# of total addresses with positive STX balances

### ISSUE THREAD

**Issue by louiseivan** [hirosystems/explorer#369]
**Overview** 
Currently, we have 21 Telegram Communities and 52 Meetup Groups in more than 30 countries. Overall, the Stacks ecosystem has more than 50,000 dedicated community members. We're planning to give the community an OKR for 2021 to accelerate the growth of STX.  

**Is your feature request related to a problem? Please describe.**
It was always hard to measure a community's impact. A clear definitive goal on what success looks like is needed and we think the # total Stacks Addresses w/ positive STX balances is one way to measure their attribution.

**Describe the solution you'd like**

- Display the **total number of addresses** with positive STX balances
- Display the **# of TVL** with Stacking
- Display the **total number of transactions processed lifetime** 

**Additional context**
You can see how other projects use this as a sign of adoption within the crypto space. Adding some social proofs below:
- https://defipulse.com/ - For TVL, adding it in the explorer's API will make it easier to integrate as well. 
- https://twitter.com/XVGhulk/status/1360970529377812487

**Comment by andresgalante** [comment]
This could be considered as an addition to the high-level information described here https://github.com/hirosystems/explorer/issues/345

**Comment by andresgalante** [comment]
Closing it in favor of #345
