### ISSUE TITLE
BNS registrations in explorer 

### ISSUE THREAD

**Issue by GinaAbrams** [hirosystems/explorer#372]
Would it be possible to add name registrations to the explorer? Ideally, there would be a link to the bitcoin hash data as well - maybe linking out to an independent bitcoin block explorer.

**Comment by aulneau** [comment]
This will eventually happen, but we are blocked on the atlas/bns work that needs to happen. Once that is done and live, we'll be able to have a really tight integration with BNS :)

**Comment by andresgalante** [comment]
Things to do for this task are:

- [ ] Display the BNS name on the account page
- [ ] Link that BNS name to the tx page where it was minted
- [ ] The tx page will have block height information
