### ISSUE TITLE
Change display of coinbase tx item if it's related to unlocking event

### ISSUE THREAD

**Issue by aulneau** [hirosystems/explorer#377]
Some addresses are now displaying coinbase transactions because they are a participant of that transaction via an unlocking event. In the case where an address has a coinbase transaction in its list, but it is not the miner, we should determine what kind of event is associated with them and render the correct component for that event in place of the coinbase transaction.

**Comment by markmhx** [comment]
Is this an example of such a transaction? https://explorer.stacks.co/txid/0x2f079994c9bd92b2272258b9de73e278824d76efe1b5a83a3b00941f9559de8a?utm_source=stacks-wallet&chain=mainnet

This one showed up in the desktop wallet with "0 STX", which caught my eye a user was screen sharing with me.

**Comment by aulneau** [comment]
@markmhx that is from the genesis block. I believe that tx is what seeded all balances in stacks 2.0

**Comment by markmhx** [comment]
I see, that makes sense. Should we also hide this 0 STX genesis block transaction from view (or simply label it specially?) in both the explorer and wallet? It seems a tad confusing / suggests something funky is going on.

**Comment by aulneau** [comment]
It's a larger issue around how to display token transfers from contract calls. I don't think we should hide any data, but I do think having more details showing would be helpful

**Comment by markmhx** [comment]
Makes sense, I've split out this possible enhancement here: https://github.com/blockstack/explorer/issues/383

**Comment by GinaAbrams** [comment]
Just to add to this, it's a bit hard to discover specific unlock transactions on a more granular basis when clicking the coinbase transaction to double check that an unlock happened. Would be awesome if we could make that more clear too 🙏
