### ISSUE TITLE
Display rewards on coinbase transactions

### ISSUE THREAD

**Issue by aulneau** [hirosystems/explorer#378]
Currently the API does not include any reward data for coinbase transactions outside of associating them with a given address. The explorer shows this data in the balance card of an address that has any miner rewards. 

Once the API exposes these reward events on the individual coinbase transaction response, we can display them on that page in the explorer.

Additionally, we should display a _note_ if the coinbase is associated with a block height <= currentHeight + 100, stating that it takes 100 blocks for the rewards to "mature".

**Comment by andresgalante** [comment]
We'll take a look at this after Nakamoto, I'll close it for now
