### ISSUE TITLE
Show tuple values in function call arguments

### ISSUE THREAD

**Issue by yknl** [hirosystems/explorer#393]
Currently the contract function call page does not expand tuples supplied as args to the call.

![image](https://user-images.githubusercontent.com/29081231/109034126-526cd180-7695-11eb-92b3-a58467177f99.png)

Would be great to have this displayed.

**Comment by aulneau** [comment]
@yknl can you elaborate, the tuple is expanded below isn't it? A bit confused :)

**Comment by yknl** [comment]
My mistake, I think it's the memo "list" that's not being expanded.

**Comment by andresgalante** [comment]
This issue is duplicated here https://github.com/hirosystems/explorer/issues/353
