### ISSUE TITLE
link stacks block from transaction page

### ISSUE THREAD

**Issue by psq** [hirosystems/explorer#396]
on a page such as https://explorer.stacks.co/txid/0x5c23a937cc3c7928706f6c35d040dee3f64874cce8d8a0592d3239dcfba27d16?chain=mainnet, you can see that the transaction was included in block 5040.

it would nice is the block was clickable to bring you directly to https://explorer.stacks.co/block/0xe0740ab523da0410ebb3b86714fba320b9ffc1748f596ae5def502ff8d51169e?chain=mainnet

Instead, you have to find the block manually from the blocks page

I don't know whether blocks are shown in other places, but it would also be nice to consistently make them clickable...

As a bonus, it would be nice if typing `5040` in the search box would find that block

**Comment by andresgalante** [comment]
related to https://github.com/hirosystems/explorer/issues/805
