### ISSUE TITLE
Automatically update balance for address upon state change

### ISSUE THREAD

**Issue by markmhendrickson** [hirosystems/explorer#398]
I've noticed that the transactions for an address update automatically without a page refresh (e.g. transaction changes from pending to confirmed). However, the balance on the right-hand side doesn't appear to do so in tandem but only updates upon page refresh. This causes the various data points to get out of sync a bit and cause momentary confusion.

<img width="286" alt="Screen Shot 2021-03-01 at 09 44 39" src="https://user-images.githubusercontent.com/28991/109472776-d72f6500-7a72-11eb-9d7b-0948267dc21f.png">

**Comment by andresgalante** [comment]
Can we implement websockets to add this feature?

**Comment by shamim-io** [comment]
Hi @andresgalante and @markmhx,

I was considering the possibility of incorporating the `useEffect` hook in the frontend code in case there is a slight delay in the API response. Please correct me if my understanding is incorrect.

Additionally, it would be greatly appreciated if you could assist me in replicating the issue on my own system.

Thank you both for your support.

**Comment by andresgalante** [comment]
thanks @shamim-io for offering to help!

to reproduce it you can get testnet STX from the faucet and send a transaction on test net
