### ISSUE TITLE
"Holdings" card formatting breaks with very high balance

### ISSUE THREAD

**Issue by jasperjansz** [hirosystems/explorer#400]
![image](https://user-images.githubusercontent.com/25477905/109637305-eb479500-7b4c-11eb-8ed1-f26ef11f9180.png)

Link: https://explorer.stacks.co/address/SP31596TY1N33159BQCVEC9H16HP0KQ2VTD140157?chain=mainnet

**Comment by andresgalante** [comment]
We are rethinking the address page in a way that will address this issue. I'll close it for now.
