### ISSUE TITLE
Link to related API endpoint

### ISSUE THREAD

**Issue by kyranjamie** [hirosystems/explorer#401]
Would be really helpful if the explorer contained a link to the currently selected API endpoint. A developer feature, but one that'd be useful.

So, for this tx: https://explorer.stacks.co/txid/0x3b173266db2c8815b0f600ba6cc90fa3c689dc6ade63feb5831aa19172050c38?chain=mainnet

There'd be a link to:
https://stacks-node-api.blockstack.org/extended/v1/tx/0x3b173266db2c8815b0f600ba6cc90fa3c689dc6ade63feb5831aa19172050c38

**Comment by andresgalante** [comment]
Developers can see this in the inspector. I'll close it for now and if we get new requests for this feature we'll reopen it.
