### ISSUE TITLE
Show delegate-stack-stx event on address page

### ISSUE THREAD

**Issue by agraebe** [hirosystems/explorer#403]
I'm looking at this account https://explorer.stacks.co/address/STBB835X9NGMHWSH5E767X420GYCAV3WD12P5JJH?chain=testnet

<img width="1262" alt="Screen Shot 2021-02-24 at 3 49 25 PM" src="https://user-images.githubusercontent.com/1671228/109081912-e51e6800-76b7-11eb-99fe-c2a314624cd0.png">

It shows that only the `delegate-stx` method was called (for 200k stx). This method only delegates tokens but does not lock them up. A delegator would need to run `delegate-stack-stx` for that. The explorer view seems not to distinguish between delegated and stacked tokens.

**Comment by zone117x** [comment]
> showing all transactions (or other activity) that concern a given address in views such as this one (and not just those signed by the address directly)

I'm not sure we'd want this behavior. It would allow for a mild spam attack where someone could write a `spam.clar` contract that could be called with a bunch of victim addresses, over and over, making their wallet or explorer address page only display useless/spam txs.

I think we'd want implement this behavior on a case-by-case basis, for example this delegated stx situation.

**Comment by markmhx** [comment]
@zone117x Couldn't someone do this regardless by sending me 0.000000001 STX a bunch of times?

**Comment by zone117x** [comment]
@markmhx yeah you're right, only difference is the cost. Spam detection heuristics sound a bit tricky but could work.

**Comment by agraebe** [comment]
> we've confirmed that both delegate-stx and delegate-stack-stx were called for this address, and as such, the Explorer is properly displaying the "Stacked amount (locked)" value of 200,000 STX here?

Yes, we did. The only thing that was missing (and reasoned this issue to be opened in retrospect) was that the `delegate-stacl-stx` call wasn't on the account holder page. The call is done by the delegator and showing up there.

**Comment by aulneau** [comment]
Just a note, this is really referencing a larger issue that we have:

Events that are related to a given address are not currently displayed on their pages. This is no different than showing when an address has received STX from a `send-many` type contract. I personally think it's important to find a way to display these, even with the potential spam vectors. 

> I'm not sure we'd want this behavior. It would allow for a mild spam attack where someone could write a spam.clar contract that could be called with a bunch of victim addresses, over and over, making their wallet or explorer address page only display useless/spam txs.

This seems to be more of a UX problem. For example we could collapse all events from a given contract, allow pagination, expanding, searching, allow filtering, etc. It seems to be a separate (but important) issue. Token spam will be real too. I can mint 1 billion NFTs and send them all to you, but I don't think that means we should not display or give the ability to view all related events for an address.

See these related issues: https://github.com/blockstack/explorer/issues/383 #373 https://github.com/blockstack/explorer/issues/386 #365 #364

**Comment by friedger** [comment]
Note, that delegate-stack-stx and other functions can be called by smart contracts like pool-tool or xverse-pool. Therefore, handling the locking events better is not only about the `delegate-stack-stx` contract call, but more on any tx that emits the lock event.

**Comment by friedger** [comment]
Is it done? Where? @chresko

Can I deprecate this page https://fast-pool-ui.vercel.app/u/SPHDQQJACBCFQ1YE6A3JXDCNQW0GTGC7ZKYPF1Z8
