### ISSUE TITLE
Pox address conversion for delegation calls

### ISSUE THREAD

**Issue by agraebe** [hirosystems/explorer#407]
The Explorer converts the `pox_addr` params for stacking contract calls but not yet for delegation calls. It would be great to enable the conversion for:
- `stack-aggregation-commit`
- `delegate-stack-stx`
- `delegate-stack`

**Comment by agraebe** [comment]
@muneeb-ali noted that in addition to the methods above, the explorer also doesn't show addresses that stack using BTC transactions

As for delegation calls: showing the reward address would make it possible to review if a delegation integration works as expected, which is critical because the testnet doesn't pay out rewards (another signal integrators would look for when reviewing).

cc @markmhx would be great if this issue could be reviewed in one of your upcoming planning sessions.

**Comment by diwakergupta** [comment]
> which is critical because the testnet doesn't pay out rewards (another signal integrators would look for when reviewing).

@agraebe can you clarify the "testnet doesn't pay out rewards" part?

**Comment by agraebe** [comment]
I was under the impression that testnet rewards wouldn't be paid out, **but I was wrong**. This cURL shows rewards going out to testnet stackers:

```shell
curl -X GET 'https://stacks-node-api.testnet.stacks.co/extended/v1/burnchain/rewards'
```

For this issue, it means there's another signal integrators have that they can look for. But, it would be great to show the decoded BTC address in the explorer for quick checks, too.

**Comment by markmhx** [comment]
Is this a fairly nice-to-have enhancement for the moment given integrators have this other signal available? Or does it have urgency despite that availability?

**Comment by agraebe** [comment]
Considering the alternative probably a medium priority
