### ISSUE TITLE
Contract address -> STX Balance -> Show QR Code

### ISSUE THREAD

**Issue by unclemantis** [hirosystems/explorer#408]
Page not found when clicking on the QR icon. Not sure if this is a bug. I have no reason to deposit directly into a contract address but if this is a bug, perhaps the Show QR Code icon should be removed? Example below.

![image](https://user-images.githubusercontent.com/718701/111253954-6e0b2e00-85ea-11eb-9b68-abd9009b7c16.png)

**Comment by andresgalante** [comment]
This is fixed
