### ISSUE TITLE
Remove dependency on legacy explorer api

### ISSUE THREAD

**Issue by aulneau** [hirosystems/explorer#410]
Related https://github.com/blockstack/stacks-blockchain-api/issues/515

We want to decommission the 1.0 explorer api, however the new explorer is using that api to fetch the total amount locked for a given address in order to calculate the percentage an address has unlocked. I'd say we have a few options:

- Use a static data export and have the explorer use that as its source of truth for the total amount locked (like we currently do for the static unlocking schedule)
- The 2.0 API can include this data (and unlocking schedule data) in its response for a given address
- Remove the "percentage" view and and reference to the total original amount locked (I think this would create confusion)

Open to any other ideas.

**Comment by markmhx** [comment]
Let's re-open https://github.com/hirosystems/devops/issues/666 to decommission the legacy Explorer API once this new API is incorporated.
