### ISSUE TITLE
Add product headers to all api requests

### ISSUE THREAD

**Issue by aulneau** [hirosystems/explorer#413]

**Comment by markmhx** [comment]
Related: https://github.com/blockstack/stacks-wallet/issues/700 https://github.com/blockstack/stacks-wallet-web/issues/1094

**Comment by markmhx** [comment]
I'm reopening this so that @Eshwari007 can QA that all API requests include the intended headers.

**Comment by Eshwari007** [comment]
@markmhx Kindly provide more information on the API request and the intended headers to be tested.

**Comment by Eshwari007** [comment]
Notes:

Environment:Stacks Web Wallet

Use case:


- Validating all the API calls(headers) in Dev tools for web wallet is accurate.
- Mostly the API call as attached and also on all the links in web wallet page is calling the accurate version of the API call.

- Developer tool>Network>XHR is where we can find the API call requests.

**Comment by Eshwari007** [comment]
API testing passed in Web Wallet.
<img width="370" alt="Screen Shot 2021-06-09 at 10 04 04 AM" src="https://user-images.githubusercontent.com/38872890/121379145-c31cbe80-c911-11eb-8bf9-ec1977544340.png">

**Comment by andresgalante** [comment]
@He1DAr hasn't this been done already?

**Comment by He1DAr** [comment]
> @He1DAr hasn't this been done already?

yep
