### ISSUE TITLE
[sandbox] (optional uint) shown as uint

### ISSUE THREAD

**Issue by friedger** [hirosystems/explorer#414]
**Describe the bug**
A contract has a parameter of type `(optional uint)`, but the transaction is sent as `uint`.

**To Reproduce**
1. On testnet, use contract `ST2PABAF9FTAJYNFZH93XENAJ8FVY99RRM4DF2YCW.boom-pool-nfts-v1` function `delegate-stx`
1. enter stacker: ST2PABAF9FTAJYNFZH93XENAJ8FVY99RRM4DF2YCW, amount: 100, until-burn-ht: 10000000
1. click "call function"
2. confirm in stacks web wallet 
3. see error BadFunctionArguments

node response:
```
{"error":"transaction rejected","reason":"BadFunctionArgument","reason_data":{"message":"TypeError(OptionalType(UIntType), UIntType)"},"txid":"4d05aefb7c94f64341e6996b023c46a04150fe516cb16cbe5f873014e82014a2"}
```
**Screenshots**

![Screenshot from 2021-03-23 08-55-25](https://user-images.githubusercontent.com/1449049/112113024-941a6a80-8bb6-11eb-9db3-719d0499616e.png)

`until-burn-ht` shown as `uint`
![Screenshot from 2021-03-23 09-04-43](https://user-images.githubusercontent.com/1449049/112113267-e22f6e00-8bb6-11eb-8e8c-98d490941cfd.png)

**Additional Context**
Contract deployment: https://explorer.stacks.co/txid/ST2PABAF9FTAJYNFZH93XENAJ8FVY99RRM4DF2YCW.boom-pool-nfts-v1?chain=testnet

Line 68:
![Screenshot from 2021-03-23 09-04-17](https://user-images.githubusercontent.com/1449049/112113176-c7f59000-8bb6-11eb-87e5-5723c6ddc069.png)

**Comment by andresgalante** [comment]
@obycode is this still a thing on the sandbox?

**Comment by obycode** [comment]
You can use this contract on testnet for a simple reproducer: 
ST1SJ3DTE5DN7X54YDH5D64R3BCB6A2AG2ZQ8YPD5.nearby-magenta-termite
