### ISSUE TITLE
Display warning message in testnet mode when testnet has problems

### ISSUE THREAD

**Issue by markmhx** [hirosystems/explorer#417]
We should display this message on address and transaction pages at least, since users who are expecting for transactions to confirm there may be confused about why they're taking so long when testnet is down or having difficulties.

We could link to http://status.test-blockstack.com/ as well.

Perhaps this message could be shown based on when the last Stacks chain tip height was seen? E.g. if it was more than an hour ago?

**Comment by abhinavk9757** [comment]
I request to be assigned to this issue.

Approach: In case any API call on https://api.testnet.hiro.so/ results in a 404 or 5xx error, I propose displaying a snackbar message indicating that the Testnet might be experiencing downtime.

**Comment by abhinavk9757** [comment]
@markmhx 
I took a different approach and implemented a basic functionality.
Details in the PR - https://github.com/hirosystems/explorer/pull/1165.
Will need your input on the visuals and availability logic in order to finalize the development.
