### ISSUE TITLE
Better UI on showing transferred amount (specially when send-to-many used) 

### ISSUE THREAD

**Issue by cryptopanter** [hirosystems/explorer#427]
**Problem** : When many transactions are sent from an adress, e. x. Pool rewards, you as a user should dig deep to find your relevant tx and transferred amount!!.. That's really confusing for newcomers to find out how much they have been paid!

**Requested feature**: Making it more accessible to see tx fee, amount, balance after each received stx transaction

**Comment by zone117x** [comment]
This is effectively blocked on the API which currently doesn't easily expose stx transfer amounts for certain types of transactions. It's in development, tracked here: https://github.com/blockstack/stacks-blockchain-api/issues/369

**Comment by cryptopanter** [comment]
Thanks for your reply... I took a look at the provided link but it was hard for me to confirm if that is the same problem as i mentioned here!... Anyway, i would be satisfied to see it is already under the focus

**Comment by andresgalante** [comment]
This should be fixed now
