### ISSUE TITLE
use `atomFamilyWithQuery` in place of react-query and useSWR

### ISSUE THREAD

**Issue by aulneau** [hirosystems/explorer#465]
Currently we use two main tools for fetching data, react-query and useSWR. We should refactor all data fetching away to use `jotai/query`, which is an abstraction on top of react-query and jotai. This will give us the ability to use all the refetching features of react query but also create derived atom state with that data.

Here is a helpful example of the new `query.ts` atom we need to create and use in the explorer
https://github.com/pmndrs/jotai/discussions/412

This is what we're currently using the stacks-wallet-web https://github.com/pmndrs/jotai/discussions/535

**Comment by aulneau** [comment]
this will be resolved by https://github.com/blockstack/explorer/pull/469

**Comment by beguene** [comment]
closing as we are moving away from atomFamilyWithQuery.
