### ISSUE TITLE
Don't show empty token balances

### ISSUE THREAD

**Issue by 617a7aa** [hirosystems/explorer#494]
**Is your feature request related to a problem? Please describe.**

I've used multiple versions of the Nothing token (as one of the devs) and it's really annoying seeing empty token balances on my address in the explorer. It's useless seeing what tokens I have none of. 

**Describe the solution you'd like**

Hide empty token balances like in the web wallet.

**Additional context**

<img width="337" alt="Screenshot 2021-07-28 at 18 56 50" src="https://user-images.githubusercontent.com/67651251/127387433-221ad863-42e4-443d-8850-6aebb8bb5575.png">

**Comment by andresgalante** [comment]
Maybe adding a toggle to hide 0 balance tokens would give the users the option to opt in for this feature.
