### ISSUE TITLE
Filter in explorer

### ISSUE THREAD

**Issue by Eshwari007** [hirosystems/explorer#501]
The filter as designed in Figma various to the one that we currently have in :https://explorer-git-feat-microblocks-blockstack.vercel.app/transactions
Creating this ticket for the purpose of tracking and confirmation 
<img width="670" alt="Screen Shot 2021-08-03 at 4 48 11 PM" src="https://user-images.githubusercontent.com/38872890/128085896-730831a5-378b-4269-9841-ecdcdd8eaf18.png">
<img width="518" alt="Screen Shot 2021-08-03 at 4 48 20 PM" src="https://user-images.githubusercontent.com/38872890/128085900-fa3c2e1e-c13f-494c-860d-aac63f039ec1.png">
 between the design and actual state

**Comment by andresgalante** [comment]
I'll close this issue for now since we won't work on it
