### ISSUE TITLE
Display decimal points as indicated by FT standard (SIP 010)

### ISSUE THREAD

**Issue by timstackblock** [hirosystems/explorer#506]
There seems to be decimal issues with the Stella token it displays as 3.703703671 in the web wallet and displays 3,703,703,671.00 in the Explorer.

Since the wallet displays the wrong total users can send more than they have in the wallet example my wallet says 3.70 tokens but I can send 30000000.

Please see the address  here https://explorer.stacks.co/address/ST297VG59W96DPGBT13SGD542QE1XS954X4ZSWW2J?chain=testnet

<img width="387" alt="Screen Shot 2021-08-05 at 4 39 24 PM" src="https://user-images.githubusercontent.com/49165468/128418916-18d01c21-cbf7-4618-aa5b-a755dd21d106.png">

<img width="397" alt="Screen Shot 2021-08-05 at 4 39 06 PM" src="https://user-images.githubusercontent.com/49165468/128418931-b4b89b48-28dc-4db3-818c-0485daf52867.png">

<img width="448" alt="Screen Shot 2021-08-05 at 5 10 46 PM" src="https://user-images.githubusercontent.com/49165468/128421906-1ba262e3-6cdc-4220-8595-559af3373b52.png">

<img width="514" alt="Screen Shot 2021-08-05 at 5 10 51 PM" src="https://user-images.githubusercontent.com/49165468/128421896-5d7bbde6-4b11-4919-9787-d6b574985c64.png">

**Comment by markmhx** [comment]
[Reported as a need for Friedger Pool in Discord.](https://discord.com/channels/621759717756370964/824628945982849055/891014837763735572)

**Comment by markmhx** [comment]
I'm moving this to the backlog since it keeps coming up as confusing for folks.
