### ISSUE TITLE
Fix private testnet usage

### ISSUE THREAD

**Issue by dorucioclea** [hirosystems/explorer#517]
Can the explorer run in a private testnet environment ? 

I currently run a private testnet for development purposes. When I try to see a smart contract deployment transaction, it shows it when searching for it but I can't reach the transaction/deployment details page ever. 

This is more of a question: Does the explorer support private testnet at the moment ?

**Comment by markmhx** [comment]
By "private", do you mean on your localhost? Are you installing and running this repository locally, or using "Add a network" from explorer.stacks.co?

Note: I'm unable to select "Add a network" right now on so we may have a (related) bug:

![image](https://user-images.githubusercontent.com/28991/130402740-7f539ac6-97ea-4113-95e6-40737aeb065f.png)

**Comment by andresgalante** [comment]
This is fixed
