### ISSUE TITLE
Remove warning in extension when deploying a contract

### ISSUE THREAD

**Issue by friedger** [hirosystems/explorer#524]
**Describe the bug**
A warning about insecure transaction is shown in the extension pop-up when I try to deploy a contract in the sandbox.

**To Reproduce**
Go to sandbox and deploy a contract using Hiro wallet 2.15.2

**Expected behavior**
Use deny mode and do not show the warning.

**Comment by markmhx** [comment]
@jasperjansz I presume the integration change here is simply not to display a warning for contract deploys in particular?

**Comment by jasperjansz** [comment]
hey @friedger it's my understanding a contract deploy can call functions of other contracts and make transfers. Is that the case?

**Comment by friedger** [comment]
Correct

**Comment by markmhx** [comment]
In that case, I suppose we just need to modify the Explorer integration to use "deny" mode.
