### ISSUE TITLE
Prevent unpruned transactions from showing twice on address page (pending and failed)

### ISSUE THREAD

**Issue by markmhx** [hirosystems/explorer#534]
@GinaAbrams spotted a case in which a StacksPunks [failed transaction](https://explorer.stacks.co/txid/0x97f179fa59640e682f46bb2b89420e0b160046a6dd3d62273b12160612bd9d68) with the wrong nonce was showing up twice on the sender's [address page](https://explorer.stacks.co/address/SP1T07GK9H4M0WP4N1DSSA7NJ7GNTQZ0GBZM0GAR2?chain=mainnet), once as failed and one as still pending (over 20 hours):

![image](https://user-images.githubusercontent.com/28991/132842226-af163948-5d87-4a3b-8c00-4886a277199a.png)

By now, the pending transaction instance has disappeared from the address page entirely, leaving just the failed one.

At the time, @aulneau noticed that the transaction showed up as still in the mempool per this query: https://stacks-node-api.mainnet.stacks.co/extended/v1/tx/mempool?limit=200&offset=300

But it returned a different value (presumably failed) with this query: https://stacks-node-api.mainnet.stacks.co/extended/v1/tx/0x97f179fa59640e682f46bb2b89420e0b160046a6dd3d62273b12160612bd9d68

@zone117x noted that "the tx appears to have gone through several re-orgs and ended up not marked "pruned" in the mempool table, even though it has a (canonical=true && microblock_canonical=true) entry. probably a missing mempool prune line in one of the re-org code paths.."

We may need to fix this issue API-side or figure out a way to handle the discrepancy between these two queries better on the client-side to prevent dual listings (one with misleading info to suggest the transaction is still pending) from showing up again for other transactions.

[See discussion on Discord](https://discord.com/channels/621759717756370964/803293319328170024/885190167973998643)

**Comment by markmhx** [comment]
Another example reported [here](https://github.com/blockstack/stacks-wallet/issues/916), with the same transaction appearing as pending and in microblock:

![image](https://user-images.githubusercontent.com/28991/133403579-c209ce75-40fc-49ff-b7d6-20407a967295.png)

**Comment by fbwoolf** [comment]
@markmhx it seems like this one might be resolved with api fixes?

**Comment by markmhx** [comment]
Yep I'll take it off our board.
