### ISSUE TITLE
Auto-detect paste event, and implicitly add https protocol, if missing  

### ISSUE THREAD

**Issue by Eshwari007** [hirosystems/explorer#549]
As an user whom copy paste url,it seems to be cumbersome when its pasted into the url section when an user is adding a new network modal.
If the user did not add https:// to the url header,an error is thrown.It would be nice to have a http:// hardcoded in the url section
<img width="447" alt="Screen Shot 2021-09-21 at 2 36 24 PM" src="https://user-images.githubusercontent.com/38872890/134228316-900836de-79f8-448b-ab23-a1ba645ec6be.png">

**Comment by kyranjamie** [comment]
Would you then have the opposite problem if the user _has_ copied an address with the protocol?

**Comment by markmhx** [comment]
I'd recommend we simply detect upon submission if the URL value as an `http` or `https` prefix, and if not, add `https` automatically. That way the user doesn't have to deal with pre-filled values and benefits from protocol inclusion flexibility on entry.

**Comment by fbwoolf** [comment]
We do provide an error message and I would think most users will copy/paste?

**Comment by Eshwari007** [comment]
Yes,I would assume most users will copy and paste only the url .
However,if the url is missing https header,it does thrown an error as of now.
