### ISSUE TITLE
Display of Stacks transaction size in bytes

### ISSUE THREAD

**Issue by cryptopanter** [hirosystems/explorer#554]
I think it would be nice if we have Stacks tx size item on explorer like all Bitcoin block explorers. 
This can easily give users and devs idea of how much size they are dealing with in the network and how much in bytes both Stacks block and its transactions inside occupy. 
More transparent, more insightful, more inspiring!

**Comment by markmhx** [comment]
Thanks for the suggestion!

**Comment by albydeca** [comment]
Hi all, trying to resurrect this as I believe it is a great feature!

**Comment by andresgalante** [comment]
@rafaelcr do we have this information on the API?

**Comment by rafaelcr** [comment]
@andresgalante we do 👍
For example, you can find keys for `execution_cost_read_length` and `execution_cost_write_length` here: https://stacks-node-api.mainnet.stacks.co/extended/v1/tx/0x0153a41ed24a0e1d32f66ea98338df09f942571ca66359e28bdca79ccd0305cf

**Comment by andresgalante** [comment]
This is a good first issue but it'll need design help to be ready to execute

**Comment by friedger** [comment]
Byte size is supposed to be shown on https://stxmempool.com
The other dimensions are more interesting I think.

**Comment by friedger** [comment]
https://github.com/stxmempool/stxmempool

**Comment by chresko** [comment]
Byte size is a good idea. Thanks.

**Comment by friedger** [comment]
I disagree, byte size is not really relevant for stacks.
