### ISSUE TITLE
Displaying the status and transaction ID in explorer

### ISSUE THREAD

**Issue by bogachevanton** [hirosystems/explorer#558]
#528 
#552 

I propose to change the mechanics of displaying the status and transaction ID. Now, due to non-rigid fields, the text display **floats** and **waves** are obtained when scrolling in the explorer. I attach a video where I added a straight red line, which shows how the status text moves in front of it, then after it.

**Suggestion:** to make a separate field for the status, a separate field for the transaction ID with clear boundaries.
Remove the separator in the form of a dot between them (in the dark theme, this separator is now gone, since it is not painted white)

I am attaching a screenshot, which clearly shows which field I am talking about at the moment.

[Screenshot](https://a.radikal.ru/a07/2109/0d/d158dedecae4.png)
[Video](https://radikal.ru/video/SZDZ2th3BPl)

**Comment by markmhx** [comment]
We plan on standardizing the UX for transactions in general across the two wallets and explorer sometime in Q4. I've added this idea to a relevant milestone so we can visit these considerations as soon as we kick off that work. Thanks for the input 🙏

**Comment by bogachevanton** [comment]
Thanks Mark for the answer. I am always glad to help with something.

**Comment by chresko** [comment]
Dup of transaction status work. Closing.
