### ISSUE TITLE
Link to related ecosystem resources

### ISSUE THREAD

**Issue by markmhendrickson** [hirosystems/explorer#559]
It'd be helpful to link to related data visualization resources in the ecosystem (e.g. from the homepage) so users have an easy path to them, at least until we incorporate similar functionality on the explorer itself directly:

- https://stacksdata.info/
- https://www.stxstats.co/
- https://stacksonchain.com/
- Stacks Dataverse from Novum Insights (in preparation for launch)

**Comment by andresgalante** [comment]
I'd also add to this list stacking.club

**Comment by andresgalante** [comment]
@eugeniadigon, should we consider this for the new design? if so lets close it

**Comment by eugeniadigon** [comment]
> @eugeniadigon, should we consider this for the new design? if so lets close it

I'd be weary of this. I'd only link to very reliable and relevant resources. All links quoted above are now unused, broken, or replaced, and we don't want this to become another thing to maintain on our side.
