### ISSUE TITLE
Fix "View schedule" for addresses with unlocking tokens

### ISSUE THREAD

**Issue by andresgalante** [hirosystems/explorer#561]
This is a regression, the "view schedule" button isn't working here:

https://explorer.stacks.co/address/SP2HR7KFZA9XF6YK33M83JVKB7FZA5G5XAQJ24T31?utm_source=stacks-wallet&chain=mainnet

Inspecting the code it looks like it's not even a link

![](https://cdn.discordapp.com/attachments/803293319328170024/895387632660545556/Screen_Shot_2021-10-06_at_16.10.16.png)

**Comment by fbwoolf** [comment]
@andresgalante the code is here and is called by an `onClick` function `handleOpenUnlockingScheduleModal`: https://github.com/blockstack/explorer/blob/91578e08528b06b1b52bb2ce9eac18c555b01278/src/components/balances/stx-balance-card.tsx#L160

**Comment by andresgalante** [comment]
Is this issue Done?

**Comment by fbwoolf** [comment]
This is done but it hasn't been released yet.

**Comment by fbwoolf** [comment]
I will close the issue. @He1DAr if you link the issue in your PR when you merge it the issue will automatically close.
