### ISSUE TITLE
Changing filter on transactions shows Not Found page

### ISSUE THREAD

**Issue by friedger** [hirosystems/explorer#568]
**Describe the bug**
When I change the filter on the transactions page, the https://explorer.stacks.co/transactions?chain=mainnet shows "Not found"

**To Reproduce**
1. Go to https://explorer.stacks.co/transactions?chain=mainnet
2. Click on fitler, click on coinbase
3. See error

**Expected behavior**
Show filtered list of transactions

**Screenshots**

![Screenshot from 2021-10-19 08-30-07](https://user-images.githubusercontent.com/1449049/137855666-b89c7a21-f348-49f9-97aa-4fd8756a757c.png)

**Console log:**
```
Error: [Jotai Query Toolkit] no query key was found for atomFamilyWithInfiniteQuery/["transactions/CONFIRMED",30,"token_transfer","smart_contract","contract_call",null], is it an atomFamilyWithInfiniteQuery atom?
    _t index.js:698
    c use-transactions-list-state.ts:25
    K tabbed-transaction-list.tsx:35
    React 8
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
react_devtools_backend.js:2528:25
    overrideMethod react_devtools_backend.js:2528
    React 5
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
  ```

**Comment by andresgalante** [comment]
This has been fixed
