### ISSUE TITLE
Add "Tokens" section to Explorer, similar to Etherscan and other explorers

### ISSUE THREAD

**Issue by wbnns** [hirosystems/explorer#579]
**Is your feature request related to a problem? Please describe.**
It's challenging to reference the current assets available on Stacks, easily from one place. It would be helpful if it was possible to reference the currently deployed assets/tokens, similarly to how you can on other Blockchain explorers.

**Describe the solution you'd like**
Add a link to the top navigation bar, "Tokens" that enables to you track tokens on Stacks, similarly to how you can on Etherscan: https://etherscan.io/tokens

Another example from the Celo network: https://explorer.celo.org/tokens

**Describe alternatives you've considered**
A community managed Google sheet might be a stop-gap to consider in the interim, so that people know what all assets are deployed on Stacks, and where to interact with them (e.g. Arkadiko, ALEX, StackSwap, etc.)

**Additional context**
Moon.

**Comment by andresgalante** [comment]
Thanks for the suggestion. I'll close this one in favor of https://github.com/hirosystems/explorer/issues/1088
