### ISSUE TITLE
Contract page is broken

### ISSUE THREAD

**Issue by aulneau** [hirosystems/explorer#583]
When trying to view this page: https://explorer.stacks.co/txid/SP2C2YFP12AJZB4MABJBAJ55XECVS7E4PMMZ89YZR.arkadiko-stacker-v1-1?chain=mainnet it always renders the missing or broken page view:

<img width="1840" alt="Screen Shot 2021-11-01 at 7 19 42 AM" src="https://user-images.githubusercontent.com/11803153/139670420-321ee27a-f402-483f-9fe6-77d32685705a.png">

**Comment by markmhx** [comment]
I'm getting a similarly broken experience:

<img width="1324" alt="image" src="https://user-images.githubusercontent.com/28991/165748902-3181f4c9-684d-48ad-9182-1a66ff9fa985.png">

**Comment by diwakergupta** [comment]
BTW, I see the page render correctly for a second before it's replaced by the above screen. Do we know if it's impacting just this one contract or others too? Wondering if we should revisit the P3 prioritization.

Further, when I hover on the "X" under "Add a network", I get a weird, large circular shadow (see screenshot below):

<img width="871" alt="Screen Shot 2022-04-28 at 9 31 32 AM" src="https://user-images.githubusercontent.com/15990/165763969-ffe0e7ea-86cc-4666-a584-cc3f4000f95a.png">

**Comment by markmhx** [comment]
> Do we know if it's impacting just this one contract or others too? 

Unclear at this point. I haven't seen reports for other contracts personally.

> Wondering if we should revisit the P3 prioritization.

Agreed. Upgrading to P2 since this is blocking / critical functionality for at least some users (to view their desired contracts)

**Comment by andresgalante** [comment]
This has been fixed
