### ISSUE TITLE
Add staging environment to Segment

### ISSUE THREAD

**Issue by fbwoolf** [hirosystems/explorer#584]
We need to add a staging environment to Segment so we can test changes w/out corrupting production metrics data being collected.

**Comment by markmhx** [comment]
@fbwoolf mind t-shirting this one?

**Comment by markmhx** [comment]
To be clear on this one though, currently are we getting _just_ production data into Segment or both production _and_ staging into Segment as the same?

**Comment by andresgalante** [comment]
@chresko are you using Segment?
