### ISSUE TITLE
Question on Visible data on Explorer-Segment

### ISSUE THREAD

**Issue by Eshwari007** [hirosystems/explorer#585]
User is testing segment feature in Explorer which is live in Production (Mainnet)
Am able to view each transaction id and also user personal STX address,recall we dont want any PII data exposed
Do advise if this should be masked or a bug
<img width="1179" alt="Screen Shot 2021-11-02 at 8 43 24 PM" src="https://user-images.githubusercontent.com/38872890/139970859-41e92d9a-21a5-4771-b17f-0b5fd03086c4.png">
<img width="1301" alt="Screen Shot 2021-11-02 at 8 44 16 PM" src="https://user-images.githubusercontent.com/38872890/139970861-83e3b44b-5007-452d-a2aa-c679e66f966a.png">
 cc @markmhx @fbwoolf

**Comment by fbwoolf** [comment]
@Eshwari007 in the explorer this is just the address of the page you are viewing. It isn't associated with you as a user.

**Comment by fbwoolf** [comment]
I will close this bc this is expected. Thanks for checking!
