### ISSUE TITLE
Add option for downloading transactions in CSV

### ISSUE THREAD

**Issue by Weirdcoin** [hirosystems/explorer#589]
It will help to update the portfolio with the transactions. Or filling information into a tax program who doesn't support the Stacks explorer.

Example from https://etherscan.io/
![image](https://user-images.githubusercontent.com/94184050/142777261-d501c28f-fb9f-446b-883e-b4779331fdb6.png)

**Comment by markmhx** [comment]
Good idea!

**Comment by Weirdcoin** [comment]
Thanks! To help you in the right direction with this. I would like to share some info from a online tax program. This shows which fields are required to upload as information. This is just a example form Koinly. But i'm sure these fields would be the same for other tax programs.

Source: https://help.koinly.io/en/articles/3662999-how-to-create-a-custom-csv-file-with-your-data

[Koinly Custom CSV - Advanced deposit, withdrawal, mining, trade.xlsx](https://github.com/hirosystems/explorer/files/7586250/Koinly.Custom.CSV.-.Advanced.deposit.withdrawal.mining.trade.xlsx)

![image](https://user-images.githubusercontent.com/94184050/142982848-c8be428a-5c34-420a-a963-f0ef1dea60d0.png)

![image](https://user-images.githubusercontent.com/94184050/142983065-4892602c-cdc2-4efe-87f3-b0431a25d1f4.png)

Adding optional fields woud be much appreciated. These are the one's that i thinks should be possible.
Fee Amount
Fee Currency 
Label, Description
TxHash

**Comment by jslusser** [comment]
I also want this feature.  I am preparing my 2021 taxes and my crypto accountant is trying to reconcile my CoinTracking account - we are now working on the Hiro wallet.  The accountant wants a CSV file of the transactions and I just learned from Hiro support that it is not currently possible 😕, so I'm adding my comment here today.

**Comment by sjwhitely** [comment]
+1 - two request from users in past week to have access to transaction history for 2020 and 2021 taxes

**Comment by Weirdcoin** [comment]
While still waiting. Someone in the Stacks Discord gave me information how to download transaction data from the transactions on Stacks. I hope this might be of use for you all. For me it turned out well. Only NFT transactions might not be recognized by you tax program/ portfolio tracker.

https://fatstx.github.io/transactions

**Comment by markmhx** [comment]
We've gotten another request for a tax-related download feature via email support.

**Comment by markmhx** [comment]
cc @314159265359879 for reference in tax-related support inquiries for the wallet
