### ISSUE TITLE
Confirmed (microblock) transactions vanishing and reappearing on the explorer

### ISSUE THREAD

**Issue by 314159265359879** [hirosystems/explorer#590]
**Describe the bug**
Confirmed transactions on the explorer frontpage are changing. Sometimes it shows transactions confirmed in microblocks and than it does not. See added video.

Transaction ID 
n.a.

**To Reproduce**
1. Go to explorer.stacks.co
2. See error

**Expected behavior**
I would only expect the confirmed transactions to change when a new block is mined. or when microblock confirmations are added, but they would remain visible. Why do they vanish and than reappear?

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Additional context**
See video:
https://user-images.githubusercontent.com/33360391/142851693-16dfb1ac-bceb-4303-9dad-57ecd8396963.mp4

**Comment by 314159265359879** [comment]
Is this related to this: https://github.com/hirosystems/stacks-wallet-web/issues/1930 ?

**Comment by beguene** [comment]
@314159265359879 It seems related to #1930

**Comment by 314159265359879** [comment]
Users are experiencing this issue again today. Seems more frequent at the moment.

**Comment by markmhx** [comment]
@beguene Should we revisit this now that the three issues you link from https://github.com/hirosystems/stacks-wallet-web/issues/1930#issuecomment-1011055425 have been resolved?

**Comment by beguene** [comment]
@markmhx Yes we can review this. It's not really related to #1930. Here it's more about microblocks transactions and their inclusion in a microblock: microblocks transactions in a microblock are not 'confirmed' transactions, so you can't always be ensure they stay the same.

**Comment by markmhx** [comment]
@314159265359879 have you seen this recently?

**Comment by 314159265359879** [comment]
No I have not seen this recently. It looks fixed with the items addressed in #1930.

**Comment by markmhx** [comment]
Thanks! You mean that https://github.com/hirosystems/stacks-wallet-web/issues/1930 is no longer showing up as a problem either?

**Comment by 314159265359879** [comment]
> Thanks! You mean that [hirosystems/stacks-wallet-web#1930](https://github.com/hirosystems/stacks-wallet-web/issues/1930) is no longer showing up as a problem either?

Indeed. I think the fixes for the issues mentioned at the end of this post may have done the trick: https://github.com/hirosystems/stacks-wallet-web/issues/1930#issuecomment-1011055425
