### ISSUE TITLE
Can't copy contract source code with the correct formatting

### ISSUE THREAD

**Issue by LNow** [hirosystems/explorer#592]
**Describe the bug**
It is impossible to copy contract code or part of the contract code with the correct formatting.

**To Reproduce**
1. Open any contract call or contract deployment transaction eg. https://explorer.stacks.co/txid/SP2C2YFP12AJZB4MABJBAJ55XECVS7E4PMMZ89YZR.arkadiko-swap-v2-1
2. Scroll down to the `Source code`
3. Select whole contract code or just part of it, copy and paste into any editor
4. We end up with something like this:
```clojure
(
define-read-only
 
(
shutdown-not-activated
)
  
(
and
     
(
not
 
(
unwrap-panic
 
(
contract-call?
 .arkadiko-dao get-emergency-shutdown-activated
)
)
)
     
(
not
 
(
var-get
 swap-shutdown-activated
)
)
  
)
)

```

**Expected behavior**
Code should be copied with correct formatting (new lines and indentation)

**Comment by andresgalante** [comment]
I'll close this issue since if you copy and paste it as plain text instead of rich format on a notepad or on your code editor (like vscode) it'll respect lines and indentations.

**Comment by obycode** [comment]
I think the problem returned after the addition of line numbers. There is no way to highlight just the code without also highlighting the line numbers.

![image](https://user-images.githubusercontent.com/1473715/194385214-0f3e40bf-96fc-423c-b263-e635ed48d209.png)

**Comment by andresgalante** [comment]
This should be fixed now
