### ISSUE TITLE
Make contract source code section wider and add word-wrap feature

### ISSUE THREAD

**Issue by LNow** [hirosystems/explorer#593]
**Is your feature request related to a problem? Please describe.**
I don't like that contract source code section is narrow as it doesn't display whole source code because of that.
Moreover I don't know if something is hidden in the right part of this section until I try to scroll it to the right.

Example: https://explorer.stacks.co/txid/0x4d78fe328be831db1b68e50c4eab7fc57c328af5f441d40238436893d1b8ee28?chain=mainnet

**Describe the solution you'd like**
I would like source code section to be much wider and in addition to that I would love to have a `word wrap` option I could toggle to see immediately if some code is "hidden" or not.

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by andresgalante** [comment]
This is done
