### ISSUE TITLE
Simplify various 404 designs for transactions

### ISSUE THREAD

**Issue by sleepiJoe** [hirosystems/explorer#594]
Different errors being generated on this explorer page:
https://explorer.stacks.co/txid/SPZW30K9VG6YCPYV4BX4V1FT0VJ66R1Q01W9DQ1W.city-collection-mia?chain=mainnet
![image](https://user-images.githubusercontent.com/94863769/144521733-6e81a241-a801-4a4a-bbc2-1222162ae3f2.png)
![image](https://user-images.githubusercontent.com/94863769/144522184-2476ea46-0f40-466d-853f-b7349741c3f7.png)
![image](https://user-images.githubusercontent.com/94863769/144522285-445f1403-161e-4133-b9ce-f89abf287376.png)

Wasn't able to catch it as har file.

**Comment by markmhx** [comment]
I'm moving to design so we can review these three versions and perhaps simplify.
