### ISSUE TITLE
NFT purchase should show the total amount spent in explorer

### ISSUE THREAD

**Issue by timstackblock** [hirosystems/explorer#598]
**Describe the bug**
When I purchase an NFT it isnt clear in the explorer when looking at my address how much I spent in total on the transaction. Is it possible we can add total cost of transaction somewhere. i would like to be able to see how much I am spending clearly with each transaction/NFT purchase in the explorer.

**Comment by timstackblock** [comment]
I can see this in Etherscan for NFT purchases on the Ethereum network, would be a nice add on our explorer

**Comment by andresgalante** [comment]
@timstackblock Can you include a screenshot and a link to how Etherscan looks like please?

**Comment by fbwoolf** [comment]
@timstackblock I'm curious about this too, if you can, would you mind adding a screenshot of what you mean before you are out? It might be something I can take on as I move over to work on the explorer.
