### ISSUE TITLE
Custom fee for contract deploy in explorer via Sandbox is broken

### ISSUE THREAD

**Issue by Eshwari007** [hirosystems/explorer#600]
- Testing explorer on mainnet
- Noticed that when user tries to deploy a contract using the sandbox
- User tries to input `Custom `fee estimate
- User intentionally used a low fee which will throw validation error
- User received the validation error that the tx will fail
- User then tries to input a different `custom` fee value,validation error doesn't goes away
- User selects the fee dropdown and notices only `custom` option is visible as well
- Adding video recording of the issue

https://user-images.githubusercontent.com/38872890/145887126-e6abe6fc-fe21-44df-8902-12b062504714.mov

**Comment by markmhx** [comment]
@Eshwari007 Mind retesting this to see if it's still an issue?

**Comment by Eshwari007** [comment]
> @Eshwari007 Mind retesting this to see if it's still an issue?

@markmhx The issue mentioned above is no longer reproducible. Will close the ticket.
