### ISSUE TITLE
src/components/tx-events: getTicker returns unique abbreviation that may not match actual token symbol

### ISSUE THREAD

**Issue by wbnns** [hirosystems/explorer#603]
Context: https://github.com/hirosystems/explorer/blob/397eaaa3ca858e64dfd38af0d39e58b6176ab5fa/src/components/tx-events.tsx#L20

Hello. 👋  We've been in the process of integrating Wrapped Bitcoin (xBTC) with a large crypto exchange, and there was some confusion between our teams because in some places in the explorer, Wrapped Bitcoin is referenced as `WBI` (the symbol defined in our contract is `xBTC`); they thought there might be two different tokens intermingling with one another. I also noticed in another case that a user in one of the communities was asking why the symbol for Wrapped Bitcoin is WBI. We were concerned there might have been an issue with the initialization of the contract / symbol, however, it seems the above reference may be the reason.

So just wanted to open this issue to see what people's thoughts on a practical solution might be, and if it's possible to give precedence to the symbol defined in the deployed contract, as opposed to creating a unique ticker that might not match.

**Additional info**

Contract:
SP3DX3H4FEYZJZ586MFBS25ZW3HZDMEW92260R2PR.Wrapped-Bitcoin

**Comment by andresgalante** [comment]
Related to https://github.com/hirosystems/explorer/issues/1088

**Comment by andresgalante** [comment]
This should be fixed since we are using lunar crush now
