### ISSUE TITLE
parseFloat makes quantities / referenced amounts confusing to end users and integrators

### ISSUE THREAD

**Issue by wbnns** [hirosystems/explorer#604]
**Describe the bug**
The use of parseFloat in the explorer is confusing to integrators and end users because it gives an incorrect perception of the amount being transferred, and the balance of holdings.

Reference # 1, e.g. balance of USDA is not $330,891,881.00:

<img width="340" alt="image" src="https://user-images.githubusercontent.com/1130872/146533798-9329fd4d-63e2-4447-b834-42999891810d.png">

Link to explorer:
https://explorer.stacks.co/address/SPWVN0HJ5RJJWXPAP5JFNZ9Q0V68TVSS1WSG45X6?chain=mainnet

Reference # 2, e.g. this is not a transfer of $11B USD

<img width="768" alt="image" src="https://user-images.githubusercontent.com/1130872/146534327-64ef609e-1447-4358-9e17-b1989530e7d3.png">

Link to explorer:
https://explorer.stacks.co/txid/0x8e8773bf0693a9ba7543eb2bef58634e91d8fc49cc0c2a5132c391843cf7acc6?chain=mainnet

**Expected behavior**
Explorer should take decimals into account for token (`get-decimals`).

**Comment by philipdesmedt** [comment]
+1 - seen this confusion often with Arkadiko users (for all FTs, including USDA and DIKO)

**Comment by wbnns** [comment]
Related: #402

**Comment by fbwoolf** [comment]
Related: #506

**Comment by wbnns** [comment]
@fbwoolf Thanks!

**Comment by wbnns** [comment]
@fbwoolf :raised_hands:

**Comment by fbwoolf** [comment]
Hoping to release this to production today! 🙌

**Comment by fbwoolf** [comment]
@wbnns this should be live now.
