### ISSUE TITLE
my STX stuck in explorer stacks please someone help me

### ISSUE THREAD

**Issue by tarpeeksi** [hirosystems/explorer#605]
My 98STX stuck in the network

I send 98 STX to my binance wallet but it didnt came. It was a month ago can someone help me?

Transaction ID=0x632a40c4a0b0028dd0133e665a3bdfdfdac10daa8cc4538bf96d8071289f8255
Sender Address=SP3NW0HC8WDS4MA3DHWNFV7VCZCS6NNR8JXREH5MP
Recipient=SP1P72Z3704VMT3DMHPP2CB8TGQWGDBHD3RPR9GZS
Block Height=#38331
Block Hash=0x6ae04059c25ebeaf8942ee02414572707e90b01bd8522e31311e8c8a0f7bf8cf

**Comment by fbwoolf** [comment]
The txid you listed has been confirmed: https://explorer.stacks.co/txid/0x632a40c4a0b0028dd0133e665a3bdfdfdac10daa8cc4538bf96d8071289f8255?chain=mainnet

**Comment by tarpeeksi** [comment]
but it didn't came to my binanance acc

**Comment by fbwoolf** [comment]
Sounds like an issue on their end? Here is the tx data: https://stacks-node-api.mainnet.stacks.co/extended/v1/tx/0x632a40c4a0b0028dd0133e665a3bdfdfdac10daa8cc4538bf96d8071289f8255

**Comment by danicatalin** [comment]
Hi I have a pending transaction of 98.70 STX with the ID 0x5ae76e54831a4dd005db5e785c005f2bfc2c26eec1615613b13a7047203439e7 I have been almost 24 hours. It is that after giving the button to send the STX I have an error, but the STX that I wanted to send have been removed from the wallet and it puts me pending and goes around.If you can check please, you would be very pleased.

**Comment by danicatalin** [comment]
Hi I have a pending transaction of 98.70 STX with the ID 0x5ae76e54831a4dd005db5e785c005f2bfc2c26eec1615613b13a7047203439e7 I have been almost 24 hours. It is that after giving the button to send the STX I have an error, but the STX that I wanted to send have been removed from the wallet and it puts me pending and goes around.If you can check please, you would be very pleased.

**Comment by danicatalin** [comment]
97,80 STX
