### ISSUE TITLE
Display an account nonce 0 instead of leaving it blank

### ISSUE THREAD

**Issue by 314159265359879** [hirosystems/explorer#606]
**Please review the existing enhancement issues at the link below before creating a new one to ensure you do not create a duplicate request.** 

**Is your feature request related to a problem? Please describe.**
At ALEX a lot of people new to testing on STX are helping out. Currently a popular work around requires changing the nonce manually to their account nonce. Most of the time it is 0 but this is not very clear because the field is blank until it becomes 1 or higher.

**Describe the solution you'd like**
Show a "0" instead of a blank space. 

Account nonce =0 is displayed like this now:
![image](https://user-images.githubusercontent.com/33360391/146672538-1874ab52-4042-4cfa-b3a9-7509f1bdf596.png)

Account nonce >1 is displayed like this
![image](https://user-images.githubusercontent.com/33360391/146672545-447ac516-9ffb-441f-b712-089b452d7050.png)

**Comment by Hero-Gamer** [comment]
Great suggestion!!
