### ISSUE TITLE
Replace default 524 error page

### ISSUE THREAD

**Issue by fbwoolf** [hirosystems/explorer#608]
We need a better error page when the api is having issues so the user encounters better ux.

Current default shown:
![Screen Shot 2021-12-21 at 12 00 25 PM](https://user-images.githubusercontent.com/6493321/146977250-ec58ec43-37ac-4835-a85a-b8e502279fb0.png)

**Comment by andresgalante** [comment]
@beguene This should be better now that we are doing client-side rendering, right?

**Comment by beguene** [comment]
Yes this would almost never happen after we migrate to full client-side because we will be serving a pre-rendered page first without any api call on the back-end.

**Comment by andresgalante** [comment]
I'll close it then, thanks!
