### ISSUE TITLE
Negative balance shown

### ISSUE THREAD

**Issue by friedger** [hirosystems/explorer#611]
**Describe the bug**
The balance for this account is shown as -1.4.. STX:
https://explorer.stacks.co/address/SPFP0018FJFD82X3KCKZRGJQZWRCV9793QTGE87M?chain=mainnet

**To Reproduce**
1. Go to '[SPFP0018FJFD82X3KCKZRGJQZWRCV9793QTGE87M](https://explorer.stacks.co/address/SPFP0018FJFD82X3KCKZRGJQZWRCV9793QTGE87M?chain=mainnet)'

**Expected behavior**
I expected the amount to be 0.000009 STX

**Screenshots**
![Screenshot from 2021-12-26 23-04-48](https://user-images.githubusercontent.com/1449049/147421220-2bbb2aa0-39bb-40b4-ad13-dc15e7b15e73.png)

**Additional context**
The last three txs were sponsored txs where the sender had set a fee. The sponsor had set the same fee in addition.

**Comment by aulneau** [comment]
This is really an API bug cc @rafaelcr

**Comment by rafaelcr** [comment]
Looks like this bug is a symptom of https://github.com/hirosystems/stacks-blockchain-api/issues/857
