### ISSUE TITLE
Transferring STX

### ISSUE THREAD

**Issue by gam1977** [hirosystems/explorer#617]
Hi:
I was trying to transfer 1213.6238 STX from my Kucoin Wallet to my Hiro Wallet.  The transaction was pending for a couple of days when it was showing as int he process of receiving.  I could see the pending transaction and now the transaction is no longer pending and I no longer see the pending transaction on the block train.

My HIro wallet address it was sent to is: SP6HF5KMZ3TA7YF2NBTH8ZH4VJN2JREAQN23V9XH

The TxHash is: a1327411d23991e6d084ad9b4712bd81a9359bd357378156ffd7655fc69093da

Here is a picture of the Withdrawal details:
 
![STX Withdrawal Details](https://user-images.githubusercontent.com/97860269/149687137-0b31b738-e4f8-4309-aab9-f66ca732621c.jpg)

Please let me know what is going on here and why I am not seeing the STX appear in my Hiro wallet.

Thanks for your help!

Garrett

**Comment by kyranjamie** [comment]
https://explorer.stacks.co/address/SP6HF5KMZ3TA7YF2NBTH8ZH4VJN2JREAQN23V9XH?chain=mainnet

It looks like the tx is pending only 3 hours ago. Give it a couple of hours, and it should appear in anchor block.
