### ISSUE TITLE
Show nonces on (pending) transactions viewing an address in the explorer

### ISSUE THREAD

**Issue by 314159265359879** [hirosystems/explorer#622]
**Is your feature request related to a problem? Please describe.**
I have been troubleshooting a lot to help new users with trouble getting their transactions processed. On rare occasions transactions get send with the wrong nonce or a gap has dropped due to a transaction dropping from the mempool. 
At the moment you have to click the individual transactions that have been processed and that are pending to see the nonce they were send with.

**Describe the solution you'd like**
a crude mockup:

![image](https://user-images.githubusercontent.com/33360391/150611909-0825122c-37be-4490-b172-feded7fa6c04.png)

By displaying it here you have all the nonces in sight and you can easily see nonces are as expected. The nonce can be displayed small and/or obscured (light grey on black/white) as most users will not need it. It does not need a prominent place.

**Describe alternatives you've considered**
n.a.

**Comment by Hero-Gamer** [comment]
Agree having Nonce in the Explore tx history overview page will help in support trouble shooting
I'd also suggest displaying the fee. 

And I would further suggest both nonce and fee be added to Hiro wallet Activity itself, so all tx (or the key ones) have Nonce and fee used. This will support quicker diagnose and action taken to fix clogged wallets. 

Look forward to hearing your thoughts.
