### ISSUE TITLE
Explorer displays MillionSTX as ThousandSTX

### ISSUE THREAD

**Issue by sleepiJoe** [hirosystems/explorer#625]
**Describe the bug**

Address: SP1P72Z3704VMT3DMHPP2CB8TGQWGDBHD3RPR9GZS

**To Reproduce**
1. Go to [this wallet](https://explorer.stacks.co/address/SP1P72Z3704VMT3DMHPP2CB8TGQWGDBHD3RPR9GZS?chain=mainnet)
2. See error

**Expected behavior**
Normally it should show as 8.015.897,57 STX.

**Screenshots**
![image](https://user-images.githubusercontent.com/94863769/150688563-3d3b1120-3796-4bb8-a16d-f519f844eacc.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version v97

**Additional context**
NA

**Comment by fbwoolf** [comment]
This is what I see:

<img width="1250" alt="Screen Shot 2022-01-23 at 11 47 56 AM" src="https://user-images.githubusercontent.com/6493321/150691214-d3231088-a878-440e-a1b7-9b6c585dcda7.png">

**Comment by sleepiJoe** [comment]
> This is what I see:

Which browser do you use? Because in Firefox it's displayed correctly, then in Chrome not.

**Comment by fbwoolf** [comment]
That screenshot is taken from Chrome.

**Comment by sleepiJoe** [comment]
@fbwoolf 

html:
`<div class="css-1bw9tv8"><span style="user-select:all" class="css-fyja9i"><span class="css-18td2fn">8</span><span class="css-1ydounk">.<!-- -->037</span><span class="css-12g23ss">STX</span></span><span style="user-select:none" class="css-ks4f0t">Total balance</span></div>`

Some js loaded from explorer.stacks.co breaks the originally delivered html code into the above example.

**Comment by LunarPunks** [comment]
> **Describe the bug** A clear and concise description of what the bug is.
> 
> Address: SP1P72Z3704VMT3DMHPP2CB8TGQWGDBHD3RPR9GZS
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to [this wallet](https://explorer.stacks.co/address/SP1P72Z3704VMT3DMHPP2CB8TGQWGDBHD3RPR9GZS?chain=mainnet)
> 2. See error
> 
> **Expected behavior** Normally it should show as 8.015.897,57 STX.
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/94863769/150688563-3d3b1120-3796-4bb8-a16d-f519f844eacc.png)
> 
> **Desktop (please complete the following information):**
> 
> * OS: Windows 10
> * Browser chrome
> * Version v97
> 
> **Additional context** NA

Is this your wallet?
