### ISSUE TITLE
refactor: remove modal recoil state and introduce redux

### ISSUE THREAD

**Issue by He1DAr** [hirosystems/explorer#635]
### QA:
All modals should be working exactly like the current state.

**Comment by Eshwari007** [comment]
Testing the changes via https://explorer.staging.blockstack.xyz/

**Comment by Eshwari007** [comment]
@He1DAr tested the explorer issue with https://explorer.staging.blockstack.xyz/transactions?chain=testnet and also mainnet
Drilled down to several contracts, Function calls, collectibles, and deployment details.
Cross compared with existing mainnet /testnet explorer -all looks good.
