### ISSUE TITLE
All the filters are not working in Explorer

### ISSUE THREAD

**Issue by Eshwari007** [hirosystems/explorer#639]
User is testing Explorer prior to  Pr merge to main  :https://github.com/hirosystems/explorer/issues/635
User noticed the issue where none of the filter selection on explorer works
Attaching screen video for perusal

https://user-images.githubusercontent.com/38872890/153066962-f1ffe04e-3db2-42a1-97ba-e44e8773f66a.mov

**Comment by fbwoolf** [comment]
@He1DAr it looks like the filtering is tied to the query key so this issue will be part of the overall data fetching refactor ...or we can kill filtering temporarily and address after. Like the search bar, there is a lot of code handling this that can likely be refactored/removed.

https://github.com/hirosystems/explorer/blob/261cdc55f9a1a5e676602e13f80b915e3edcc70f/src/store/transactions.ts#L47

![Screen Shot 2022-03-29 at 4 01 25 PM](https://user-images.githubusercontent.com/6493321/160706552-b797d0bd-b5c8-48c6-a9ae-a1ab1de47a00.png)
