### ISSUE TITLE
[devnet] Problem connecting wallet to sandbox

### ISSUE THREAD

**Issue by obycode** [hirosystems/explorer#648]
**Describe the bug**
I am running devnet and connecting to the local devnet explorer. When I try to connect my wallet, it seems to work, then a different address appears to be connected. See video.

After some experimentation, I tried signing out of the wallet, clearing the cache, and relaunching devnet and found that instead of this problem, after connecting the wallet, the sandbox never loaded, then after a delay, I get "This page is missing" (appears to be the same problem as #647).

https://user-images.githubusercontent.com/1473715/154149183-b82f7a33-71cc-423c-8cdf-96c3d72555c3.mov

**To Reproduce**
Start devnet, for example, clone https://github.com/hirosystems/stacks-billboard and then run `clarinet integrate`, then open http://localhost:8000/sandbox/deploy.

**Expected behavior**
I expect to be able to properly login to the devnet explorer sandbox and call a function.

**Comment by LunarPunks** [comment]
I have similar problem with all my contracts,  did you find any solution?

**Comment by fbwoolf** [comment]
@markmhx I've been reproducing these devnet issues over the weekend, it seems like @He1DAr's work on refactoring the network mode state (which touches the sandbox code) may resolve many of these. I can check all these again once that work is ready to see if we can close these. If anything, it will be easier to fix these once that work is done.

**Comment by markmhx** [comment]
@fbwoolf Sounds good. Is there a PR for that work we can link here?

**Comment by fbwoolf** [comment]
> @fbwoolf Sounds good. Is there a PR for that work we can link here, and if not, can we open a WIP one?

This is work @He1DAr has done on a branch I see but there is no PR up yet.

**Comment by He1DAr** [comment]
> 

i

**Comment by He1DAr** [comment]
> @fbwoolf Sounds good. Is there a PR for that work we can link here, and if not, can we open a WIP one?

It's not ready yet.

**Comment by LunarPunks** [comment]
?

**Comment by He1DAr** [comment]
We're working on a larger PR to [refactor network state across the explorer](https://github.com/hirosystems/explorer/pull/681/files) that could potentially fix this issue.

**Comment by andresgalante** [comment]
This one should be fixed
