### ISSUE TITLE
Show fee paid by sponsor for sponsored transactions

### ISSUE THREAD

**Issue by markmhendrickson** [hirosystems/explorer#655]
Currently it appears we show just "0 STX" and don't indicate additionally the amount paid by the sponsor (nor the address of the sponsor), which could be used by testing by developers at the very least:

<img width="376" alt="image" src="https://user-images.githubusercontent.com/28991/156330317-302774e6-8029-477b-847a-9a109e2a50ea.png">

**Comment by larrysalibra** [comment]
The explorer properly shows the fee paid by sponsor only once it's confirmed in a microblock or block - it's not showing the sponsor address.

**Comment by 314159265359879** [comment]
This has been fixed, the actual fee (paid by the sponsor) is displayed now. but the grey background isn't displayed anymore in light mode the "sponsored" label hence disappears. Reported here: https://github.com/hirosystems/explorer/issues/1317

https://explorer.hiro.so/txid/0xc2fc1c40ff4728bed552b6b3dbd051da0b0b75f5ac48d8ca9b325ee8d990faad?chain=mainnet
![image](https://github.com/hirosystems/explorer/assets/33360391/a771b2bf-e1b7-4f00-a841-8c9c1cd16a85)

![image](https://github.com/hirosystems/explorer/assets/33360391/0ed86f97-5de9-436d-b258-97e438110267)
