### ISSUE TITLE
Lots of API requests to '/extended/v1/tx/[object%20Object]' being made

### ISSUE THREAD

**Issue by CharlieC3** [hirosystems/explorer#658]
**Describe the bug**
Hiro's Explorer seems to make about 40k requests to the `/extended/v1/tx/[object%20Object]` API path every day.
These requests are now being blocked at the firewall level since they weren't resolving anyways, but we should still figure out why the Explorer is making so many requests to this invalid endpoint.

**Expected behavior**
All requests from the Explorer to the API should be valid (save for reasonable incompatibilities between various Explorer and API versions).

**Comment by CharlieC3** [comment]
cc @He1DAr @asimm241

**Comment by markmhx** [comment]
@aulneau Thanks for this context. Is your sense that the wallet no longer exhibits this request behavior?

**Comment by andresgalante** [comment]
@He1DAr can you check is this is relevant, please?
