### ISSUE TITLE
Refactor search bar

### ISSUE THREAD

**Issue by He1DAr** [hirosystems/explorer#666]
The search bar is one of the pain points we have in the code base, it's currently managed by 18 legacy recoil atoms and it's challenging to work around it.

**Comment by He1DAr** [comment]
@Eshwari007 @timothycarambat This pr refactors the whole search logic (home search bar and header search bar), it also eliminates `recently viewed` items. We need a quick look at the search functionality (tx, block, address).

**Comment by Eshwari007** [comment]
> @Eshwari007 @timothycarambat This pr refactors the whole search logic (home search bar and header search bar), it also eliminates `recently viewed` items. We need a quick look at the search functionality (tx, block, address).

@He1DAr Can we start testing the explorer or in any test app to test the changes above?

**Comment by He1DAr** [comment]
@Eshwari007 Yep, I deployed explorer staging.

**Comment by Eshwari007** [comment]
@timstackblock At times staging can intermittently have 404 is because of nginx or cloudflare (not code related)
@He1DAr is working with Charlie on the fix, posting the findings here just in case you are having similar issues.

**Comment by Eshwari007** [comment]
Test passed.
Moving to Done
