### ISSUE TITLE
Empty Post Conditions on Failed TXs

### ISSUE THREAD

**Issue by sjwhitely** [hirosystems/explorer#667]
3/18/22: Transactions are failing for unique users for not meeting post conditions, but there are no specified post-conditions the contracts. 

**For example**
Link: [](https://explorer.stacks.co/txid/0xdffc2a800a745257ac4b0485d238f3c76d99b2bca2b9d1212fd3d79de54ede43?chain=mainnet)

Transaction ID: 0xdffc2a800a745257ac4b0485d238f3c76d99b2bca2b9d1212fd3d79de54ede43
Address: SP1E96ZEVJ2N8814H1YV121G7FEKY0A4MEEQ04G45
Block#  52637
Time stamp 3/17/22

**Comment by sjwhitely** [comment]
2 others with same issue:
[](https://explorer.stacks.co/txid/0x20238a00c73f636db649ba7218b6a75aa7ef04895a9db9b7b5b6afeb0b09798a?chain=mainnet)

[](https://explorer.stacks.co/txid/0x949096fedb2ef180a2e2c9170016c0b574a5cf0a5971394ed8abeaf15b55c712?chain=mainnet)

**Comment by andresgalante** [comment]
@markmhx I'd like to get this issue into next week's planning, if in fact the wallet is broadcasting transactions in a wrong way we should fix it right away

**Comment by fbwoolf** [comment]
Do we know if these are all coming from the same app?

**Comment by friedger** [comment]
Mostly from Hiro stacks-wallet-web

**Comment by markmhx** [comment]
I'm closing this out in favor of the wallet issue, which appears the one we need to resolve: https://github.com/hirosystems/stacks-wallet-web/issues/2301

Let's report further instances of this behavior there.
