### ISSUE TITLE
Explorer support for Devnet

### ISSUE THREAD

**Issue by Eshwari007** [hirosystems/explorer#677]
The user has set up Devnet environment using clarinet and docker.

The user notices that upon searching for an address in explorer locahost that supports devnet address, the user is not able to retrieve the address the very first time.
The user is only able to retrieve the address info upon waiting for a few minutes
The user also notices that the browser url yet points to mainnet when the user is searching for an address in devnet

Attaching screenshots for perusal:

<img width="696" alt="Screen Shot 2022-03-31 at 1 35 59 PM" src="https://user-images.githubusercontent.com/38872890/161119708-37f271bb-13eb-4d63-a55c-9e7bdc43891c.png">

**Comment by markmhx** [comment]
> The user is only able to retrieve the address info upon waiting for a few minutes

What happens exactly before these few minutes pass? Does the Explorer load on localhost but then searching for the address times out or something?

A video here may be helpful for illustration.

**Comment by fbwoolf** [comment]
I think this is a duplicate issue and can likely be closed in favor of: https://github.com/hirosystems/explorer/issues/647

There are several issues regarding devnet being broken in the explorer, see also: https://github.com/hirosystems/explorer/issues/648
