### ISSUE TITLE
Blank explorer screen for non STX tx

### ISSUE THREAD

**Issue by Eshwari007** [hirosystems/explorer#678]
The user was testing Release/2022 04 04 timid tiger #2348
User send a STX token, MIA token, and Wrapped nothing token between two accounts
The user notices upon selecting the non STX token activity -user receives a brief blank screen on explorer
However, the explorer is working fine for SYX tx

Attaching the video for perusal

https://user-images.githubusercontent.com/38872890/161603976-ef151cb5-ffeb-4ace-876a-4603c5579c6e.mov

**Comment by markmhx** [comment]
Is the Explorer simply taking awhile to load the transaction page here?

**Comment by Eshwari007** [comment]
> Is the Explorer simply taking awhile to load the transaction page here?

Yes @markmhx ,the explorer eventually loads but it does take a while to load with a few sec of blank white screen for FT tx Vs no blank white screen for STX tx in explorer view

**Comment by markmhx** [comment]
@He1DAr Do you have any initial suspicions on what could be causing this slowness?

**Comment by andresgalante** [comment]
Hi @GinaAbrams this should be fixed, I'll close it
If you still believe the issue is relevant, please feel free to reopen it.
