### ISSUE TITLE
Show considered but not mined transactions

### ISSUE THREAD

**Issue by jcnelson** [hirosystems/explorer#682]
**Is your feature request related to a problem? Please describe.**
The Stacks blockchain node, when run with the mock miner enabled, will emit an event stream for transactions the mock miner considers but does not mine.  If a pending transaction is considered but not mined in the current canonical chain tip, the explorer should show this information, so the user can at least know that their transaction will not likely be picked up in the next block.

**Describe the solution you'd like**
The explorer should show when a pending transaction was considered but rejected by the mock miner.

**Describe alternatives you've considered**
Running a node and watching the debug logs and/or capturing and manually auditing events to figure this out.

**Additional context**
When the mempool is congested, a user needs to know what they need to do to get their transaction mined.  If we can tell them what's stopping their current transaction, then they can take steps on their end to fix it themselves.

**Comment by Hero-Gamer** [comment]
Just wondering @jcnelson is this why we (the users) see nonce gaps, that the users end up having to fill those nonce gaps later? 

See an example of Nonce gap here in Discord wallet channel I recently communicated to the Hiro team: https://discord.com/channels/621759717756370964/745197302255321108/965602837788762133

Or is what you are talking in this post about a completely different issue I'm just butting into the wrong discussion? if so sorry!

**Comment by jcnelson** [comment]
This is something unrelated.  This is about showing users whether or not their transactions are potentially-mineable right now (recall that the mempool will accept chains of transactions up to 25 nonces in the future, meaning that not all transactions in the mempool are mineable right away).

**Comment by Hero-Gamer** [comment]
Appreciate the explanation! <3
