### ISSUE TITLE
Reduce the docker image size

### ISSUE THREAD

**Issue by lgalabru** [hirosystems/explorer#685]
**Is your feature request related to a problem? Please describe.**
Building a docker image of this repo is leading to a huge image - around 1gb, when we apparently only have a few kb of assets. 

**Describe the solution you'd like**
Getting a tighter, 100mb image would be great. Deployment speed is a feature, so this would lead to better UX/DX on Devnet/Testnet/Mainnet.

**Comment by lgalabru** [comment]
The resulting docker image is now around 3 gb - we did a x3 on the size in a few months, the `clarinet integrate`'s DX is getting pretty bad when the explorer is getting updated.
@CharlieC3 is there anything we could do to help with this issue?

**Comment by CharlieC3** [comment]
@lgalabru we can definitely take a look.

**Comment by deantchi** [comment]
this is complete

**Comment by sabbyanandan** [comment]
💥 — nicely done, @deantchi! Curious, how much did we reduce in size? The `latest` [tag is about 1G](https://hub.docker.com/r/hirosystems/explorer/tags); this change probably hasn't pushed yet, maybe.

**Comment by deantchi** [comment]
@sabbyanandan the new image uncompressed comes out to be 1.36gb.  The `latest` tag is 1gb compressed and I just pulled it down and uncompressed is 3.19gb.
