### ISSUE TITLE
Add Google Analytics 4 script to explorer site

### ISSUE THREAD

**Issue by tprebz** [hirosystems/explorer#692]
Google is forcing a transition to Analytics 4 in July 2023. Marketing would like to start our transition now so we have a good body of year over year data in GA4 before the GA3 cutoff arrives. 

Segment has rudimentary support for GA4, but it does not support all the native GA4 features at this time. 

The GA4 tracking script can sit alongside Segment so that any systems that draw from the Segment data will still have explorer pageview data.

The GA4 script is as follows and should be placed in the &lt;head&gt; of each page on the site:

```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-NB2VBT0KY2"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-NB2VBT0KY2');
</script>```

**Comment by andresgalante** [comment]
This has been merge to prod
