### ISSUE TITLE
Add x-api-key header to avoid rate limiting

### ISSUE THREAD

**Issue by He1DAr** [hirosystems/explorer#703]
See relevant info [here](https://github.com/hirosystems/devops/issues/932#issuecomment-1127893730) from @zone117x

**Comment by zone117x** [comment]
If possible, it would be ideal if this change could also be made alongside a change where client-side API requests are no longer made. I'm not familiar enough with nextjs or w/e else to know how difficult that would be.

The Explorer is a major source of API traffic, and ideally it would keep the API key private.

**Comment by fbwoolf** [comment]
Note, the linked repo is private. The key and endpoint are to remain private during testing.

**Comment by zone117x** [comment]
Any status update on this?

**Comment by fbwoolf** [comment]
For reference, there is an open PR in the wallet for the work: https://github.com/hirosystems/stacks-wallet-web/pull/2461

**Comment by beguene** [comment]
Thanks @fbwoolf !
@andresgalante I will look into it today
