### ISSUE TITLE
All testnet transactions showing as 'Not found' in Explorer regardless of state

### ISSUE THREAD

**Issue by wbnns** [hirosystems/explorer#705]
**Describe the bug**

![2022-05-09-20:11:03](https://user-images.githubusercontent.com/1130872/167489790-d21b8e59-fcb8-444f-8f8c-3989ffe6b99f.png)

To replicate:

+ Change Stacks Explorer to testnet
+ Broadcast a transaction on testnet or look up a previously confirmed transaction on testnet using Stacks wallet
+ Use Stacks wallet link to check state
+ No matter what, transaction will show as 'Not found'

Expected behavior:

+ Should be able to query transactions on testnet using the Explorer, they should be found

**Comment by LunarPunks** [comment]
Can you show a screenshot showing the url and one with network tab dropdown showing?

**Comment by wbnns** [comment]
Ahhh, thank you. I see in the Network tab that uBlock Origin prevents the Explorer from loading because of Sentry. Closing this issue and apologies for the false alarm.

**Comment by Eshwari007** [comment]
Thank you @wbnns ,great that you were able to figure the issue out. I was going to ping you in regards to this as explorer under testnet is working for me.
