### ISSUE TITLE
Custom error template in explorer

### ISSUE THREAD

**Issue by Eshwari007** [hirosystems/explorer#707]
The issue will be revisited after Explorer's refactor as currently, all errors will be 404 or 500s which is the default error page for nextjs. This bug will be retested after explorers refactor in the coming weeks.

https://user-images.githubusercontent.com/38872890/167911752-4618dc2b-d3f2-4396-874d-2961f595edeb.mov

**Comment by markmhx** [comment]
This seems like expected behavior to me in that the transaction selected on mainnet doesn't indeed exist on testnet, so when the user switches networks, it _should_ show a 404?

**Comment by Eshwari007** [comment]
@markmhx This is a regression as priorly it showed 'Transaction is not found' when a user selects from mainnet to testnet on a tx.
@andresgalante requested the ticket to be created so that we can re-test upon explorer refactor.
