### ISSUE TITLE
There is a ( ' ) apostrophe before the owner and recipient address in the transfer contract call arguments when viewing tx explorer.

### ISSUE THREAD

**Issue by albrtctm** [hirosystems/explorer#729]
**Describe the bug**
In the transfer contract call arguments, you guys will see ( ' ) apostrophe before the owner and recipient address.
- Clicking on the href will redirect the user to a wrong link because of the apostrophe.

Transaction ID : 0x1fdf27f8e302c24d2a43e734090f7821bd3076230cadd674b7088b03b6c3f194
Address: SP9227STGNCZPRTP2T2G3S02M7XB5ENAQB1J82FA
Block#:  58596
Time stamp: 24 days ago

**To Reproduce**
1. Go to to gamma or byzantion
2. Click on on any of your NFT's
3. Proceed on transfer
4. Fill out the transfer form, any address will do
5. Finally, check the tx explorer

**Expected behavior**
There should no ( ' ) apostrophe before the owner and recipient address when viewing the transfer contract call arguments.

**Screenshots**
<img width="918" alt="Screen Shot 2022-05-27 at 3 06 36 PM" src="https://user-images.githubusercontent.com/98573314/170649051-8ded8842-1292-4480-b5fb-59932a4f7e81.png">
<img width="314" alt="Screen Shot 2022-05-27 at 3 06 50 PM" src="https://user-images.githubusercontent.com/98573314/170649080-0603fb6b-88e0-4dd0-88f8-11fd6f6cc313.png">

**Desktop (please complete the following information):**
 - OS: Mac OS 12.4 (21F79)
 - Browser: Chrome
 - Version 102.0.5005.61 (Official Build) (x86_64)

**Additional context**
None.

**Comment by He1DAr** [comment]
The extra `'` is coming from the API response https://stacks-node-api.stacks.co/extended/v1/tx/0x1fdf27f8e302c24d2a43e734090f7821bd3076230cadd674b7088b03b6c3f194
