### ISSUE TITLE
Stx not sending

### ISSUE THREAD

**Issue by Mustansar5** [hirosystems/explorer#734]
Hello dear team i have sent my STX token to other wallet its been 30minuts but i still have not received my tokens in my wallet there is still pending even i have paid Higher Fee

Transaction ID 0x377b1fd6bb4ef4760c4d1fbc81e99d31a8d3ca723cfff4f2958e9543e1b6ba37
Address SP2R309V8FY2PQB4A8PWZY5E4EAWP3XAJE5PARJW0
Block#  pending 
Time stamp
Pending 
*
![Screenshot_20220528-202427](https://user-images.githubusercontent.com/106446224/170836573-fcd0feaf-8acf-4fc6-b5bb-22dad973e718.png)

 - Device: [Tecno Spark5 pro]
 - version [10]
 - Browser [Xverse Wallet]

**Comment by beguene** [comment]
Closing as the tx was finally cancelled https://explorer.stacks.co/txid/0x377b1fd6bb4ef4760c4d1fbc81e99d31a8d3ca723cfff4f2958e9543e1b6ba37?chain=mainnet
