### ISSUE TITLE
Not possible to input a list in the Explorer sandbox contract interface

### ISSUE THREAD

**Issue by 314159265359879** [hirosystems/explorer#739]
**Describe the bug**
I can't input a list `(list u1 u1 u1)` it instead errors with "please enter a number" with no possibility to go to the sign screen. 

Transaction ID 
N.A.

**To Reproduce**
1. Go to Sandbox, login and input SPSCWDV3RKV5ZRN1FQD84YE1NQFEDJ9R1F4DYQ11.newyorkcitycoin-core-v2
2. Click on 'mine-many'
![image](https://user-images.githubusercontent.com/33360391/171057356-ec8ca86f-713e-4fd3-b1c2-a2d2a2b75ea0.png)

3. Enter a list input such as: (list u1 u1 u1)
![image](https://user-images.githubusercontent.com/33360391/171057187-3cee7f68-b000-44e4-943e-aed2d823a083.png)

**Expected behavior**
I would like to call the function with a list and sign it. 

**Screenshots**
see above

**Comment by whoabuddy** [comment]
Noting that this was resolved in a recent release, just double-checked on testnet to confirm:

![Screenshot from 2023-01-12 06-34-29](https://user-images.githubusercontent.com/9038904/212080650-fe72f563-c42c-4f1b-9a2d-9aed405023cc.png)

I didn't test it all the way through sending the tx but you can access the testnet version of MIA mining here:

`ST1H1733V5MZ3SZ9XRW9FKYGEZT0JDGEB8WRH7C6H.miamicoin-core-v2`
