### ISSUE TITLE
Confirmed in anchor block

### ISSUE THREAD

**Issue by kaipil1s** [hirosystems/explorer#741]
I sent my stacks to binance but it hasn't showed yet. Transaction shows "confirmed in anchor block". What does this mean?

**Comment by Hero-Gamer** [comment]
> I sent my stacks to binance but it hasn't showed yet. Transaction shows "confirmed in anchor block". What does this mean?

It means the tx is settled. But even if it shows confirmed in anchor block, it might still take time for Binance to process that money in their internal system. Should be fairly quick tho on their side I'd imagine.
