### ISSUE TITLE
List all the /v2 api endpoints used and replace them with a '/extended/v1' endpoint

### ISSUE THREAD

**Issue by beguene** [hirosystems/explorer#757]
'extended/v1' api endpoint is more performant while /v2 endpoint is a RPC endpoint which is slower. This will help prevent RPC congestion.

example done here https://github.com/hirosystems/explorer/issues/586 to replace the account /v2 fetch with a /v1 nonce fetch

**Comment by diwakergupta** [comment]
To be clear, when you say v1, you really mean `/extended/v1` endpoints?

**Comment by beguene** [comment]
Yes I meant `extended/v1`. I updated the issue for clarity.

**Comment by beguene** [comment]
There are no other v2 endpoints to refactor beside the one already done here https://github.com/hirosystems/explorer/pull/760
Closing.
