### ISSUE TITLE
"distribute" (send-many) tx does not show in tx history in Explorer

### ISSUE THREAD

**Issue by Hero-Gamer** [hirosystems/explorer#775]
Hi Team, 

- At ALEX Defi, there is a reward distribution tx to many many users, called "**distribute**" contract (it sends $ATALEX token to users), this tx is **shown in Hiro web wallet** you can see it under Activity tab. 
<img src="https://user-images.githubusercontent.com/92864860/177356823-1663ae7e-90ae-4263-92bc-33e7e1002235.png" width="280px" />

- But in the Explorer tx history of the **RECEIVER'S WALLET** (i.e. the Alex user), **neither the "distribute" tx nor the "auto ALEX Transfer" are shown.** 
https://explorer.stacks.co/txid/0x8e8c70f7524523e995952ac00b3898903a5b80493d6a44c3c62f1fea8d600583?chain=mainnet

- This confuses users a lot, as they think did not receive any reward when they look at the tx history in the Explorer, when in fact they did receive. 

_Apparently might be due to:_
So, the explorer uses **/transactions**
While the web wallet uses **/transactions_with_transfers**

Is there something can be done about this?

Tagging wallet team awareness: @markmhx @fbwoolf

**Comment by beguene** [comment]
Thanks @Hero-Gamer. Yes indeed in the wallet we use the new api endpoint /transactions_with_transfers which includes this info, but the explorer is still using /transactions.

cc: @andresgalante to prioritize.

**Comment by beguene** [comment]
Related PR from the wallet 
https://github.com/hirosystems/stacks-wallet-web/pull/1747

**Comment by He1DAr** [comment]
This is a good opportunity to refactor tx list components, this part has multiple levels of nesting and abstractions that are making it hard to update. It also has a lot of dead code that we need to get rid of.
