### ISSUE TITLE
Nonces nolonger showing on pending transactions when viewing an address and its history?

### ISSUE THREAD

**Issue by 314159265359879** [hirosystems/explorer#778]
**Describe the bug**
Nonces not showing anymore for pending transactions on an address. 

This improvement was rolled out some time ago and I enjoyed it a lot when troubleshooting issues for users. https://github.com/hirosystems/explorer/issues/622#event-6661631170

**To Reproduce**
1. Go to any address with pending transactions
2. nonces not shown here:
![image](https://user-images.githubusercontent.com/33360391/177850628-c0b8f181-48cf-4259-b893-abd58856131b.png)

**Expected behavior**
I would expect it to show something like this:
![image](https://user-images.githubusercontent.com/33360391/177851123-e2e2d2a9-45e4-4ee5-8bb4-26bd65d44b96.png)

source: https://github.com/hirosystems/explorer/pull/624#issuecomment-1130420295

**Desktop (please complete the following information):**
n.a.

**Smartphone (please complete the following information):**
n.a.

**Comment by 314159265359879** [comment]
Hero Gamer says sometimes it shows other times it does not, and sometimes a refresh resolves it. I tried refresh several times before posting this but had no success. Is it possible some explorer servers are using an older version then others?

**Comment by Hero-Gamer** [comment]
I looked at a random pending tx in the mempool, I can confirm refreshes does change whether it displays the Nonce "n" or not. 

- **Example tx under this address:**
https://explorer.stacks.co/address/SP3KPRE6KAQSSK3189X58SJQRNPF5JSM03WMD5RSB?chain=mainnet

- **First search "n" appears.** 
<img src="https://user-images.githubusercontent.com/92864860/177882169-149a1e8a-f4d2-45f0-b0ce-baf07bc32ef3.png" width="700px" />

- **Exact same pending tx after a few refreshes, the "n" disappears.**
<img src="https://user-images.githubusercontent.com/92864860/177882267-c6cf2a0f-43e3-401f-aaa7-3a6c8667558e.png" width="700px" />

**Comment by beguene** [comment]
Thanks @Hero-Gamer and @314159265359879 we will look into it.

**Comment by dartman10** [comment]
At this time, I notice nonce values are displayed for pending transactions.  However, nonce is not displayed on anchored transactions.  If this is intentional, may I request to keep nonce value even for anchored?  Thanks.

**Comment by 314159265359879** [comment]
@dartman10 this is intentional, atleast my reasoning when I requested the feature was that:
 
1. For confirmed transactions we already know the nonce is fine.

2. The last confirmed nomce is already shown on top.

3. Nonces on confirmed transactions could cause additional confusion when they are send from another address they would show that account's address (incoming transfers). Although I am sure it could be made so nonce is only shown for transactions send by the address being viewed we wanted to keep it simple. 

4. I couldn't think of a use case for it and thought keeping it simple would be best.

What is the use case you are thinking of that makes it helpful to see the nonces on confirmed transactions?

**Comment by dartman10** [comment]
@314159265359879 mine is a weird use case.  and with last nonce already at the top (thanks for pointing that out), we can ignore my request.  :)

The use case is with a pending transaction having nonce 260, which was overridden earlier with an already confirmed transaction having same nonce.

![Screen Shot 2022-10-02 at 6 16 42 AM](https://user-images.githubusercontent.com/34408740/193449406-7aabca6e-ca48-4d52-acda-3b468032bcdb.png)

Thank you for taking the time and for explaining!  Cheers!

**Comment by 314159265359879** [comment]
This issue has been resolved some time ago. closing this.
