### ISSUE TITLE
Display status from status page on the explorer

### ISSUE THREAD

**Issue by beguene** [hirosystems/explorer#780]
we need to display some status information at the top of all pages in the explorer if it's the status is not fully operational.
status.hiro.so

**Comment by landitus** [comment]
Sure thing

**Comment by landitus** [comment]
@beguene What information can we pull from the status page? I'm assuming we can show:

- The status label:
  - API Outage
  - Mainnet API - Degraded Performance

Is there a description or text we can pull that would explain more about the issue? Like what appears here: https://status.hiro.so/history

**Comment by beguene** [comment]
Nice @landitus , I would also pick B, it's really visible and consistent across pages.

@andresgalante Sure !

**Comment by beguene** [comment]
@landitus We can know more than what is on the page or in the rss here
https://status.hiro.so/history.rss
I would go with displaying the text in <title></title> if it's not "All Systems Operational" 
The list of possible status based on the history are
* Degraded API Performance
* Mainnet API stalled
* API Outage
* Degraded API Performance

**Comment by landitus** [comment]
Thanks. Here's the final spec with the two types of errors, one for high severity and one for medium severity.

[Figma](https://www.figma.com/file/NtYZVL33JRulRhG0XdbF3k/%23780---API-Status?node-id=10%3A416)
<img width="1440" alt="Status error - Danger" src="https://user-images.githubusercontent.com/239215/179223461-2382269e-a2c6-4d14-9917-68f716cf9495.png">

<img width="1440" alt="Status error - Warning" src="https://user-images.githubusercontent.com/239215/179223449-1712348b-f042-4d8c-af59-ed3c2946330f.png">

**Comment by andresgalante** [comment]
@landitus orange over the pink background fails AA contrast

**Comment by landitus** [comment]
Thanks for pointing it out. Mmmm, I picked this text color from the design system... but now it's changed in the Figma to pass AA contrast

<img width="1440" alt="Status error - Warning" src="https://user-images.githubusercontent.com/239215/179254178-b5667119-6486-4e18-a6d1-187b45b25e3b.png">
!

**Comment by andresgalante** [comment]
I don't think it's a problem with the orange from the design system but with the transparency. If you make it less transparent, maybe the orange works.
