### ISSUE TITLE
Explore graceful degradation and backup when API outages

### ISSUE THREAD

**Issue by beguene** [hirosystems/explorer#781]

**Comment by andresgalante** [comment]
An idea to improve this is to skip the API and make database connections, it'll also improve performance.

**Comment by beguene** [comment]
@andresgalante The direct DB connection we discussed yesterday is not related to this issue. This current issue is about showing something rather than nothing when there is an API outage.

I created a new [issue](https://github.com/hirosystems/explorer/issues/783) for the DB connection solution with more details and why we should at least explore this idea.
