### ISSUE TITLE
Show submitted transaction that hasn't made to mempool

### ISSUE THREAD

**Issue by andresgalante** [hirosystems/explorer#782]
When a transaction was submitted and it hasn't made it to the mempool yet, the explorer shows a 404. It'd be better to have a new state for a tx that reflects this.

It's related to issue on the wallet https://github.com/hirosystems/stacks-wallet-web/issues/2467

**Comment by andresgalante** [comment]
@He1DAr please check what's the deal with this one

**Comment by He1DAr** [comment]
It looks like it's an API issue https://github.com/hirosystems/stacks-blockchain-api/issues/1231
