### ISSUE TITLE
Remove redirect in SSR

### ISSUE THREAD

**Issue by beguene** [hirosystems/explorer#784]
We could remove the redirect in the nextjs [middleware](https://github.com/hirosystems/explorer/blob/main/src/pages/_middleware.ts#L11) to shave ~300ms off the first request and improve our SEO.
below an example where it's ~590ms, but this can vary.
<img width="588" alt="image" src="https://user-images.githubusercontent.com/1501454/178476340-cb908041-2e3a-4d1e-90d8-0035226dba86.png">

The middleware does a redirect because it handles first the chainId (mainnet or testnet), but we could maybe try to handle it client side without using any store server side
if the request has `?chain=mainnet` or `?chain=testnet` => nothing to do, the current code handles this
if the request does not have `?chain=X` or X is invalid, default to mainnet and set the query params client side and set the activeNetwork to mainnet)

At least we should ignore woff fonts and the favicon.png redirects

**Comment by andresgalante** [comment]
This should be outdated. @beguene please reopen it if it's relevenat
