### ISSUE TITLE
Possible Explorer history default nonce display error (off by 1 nonce)

### ISSUE THREAD

**Issue by Hero-Gamer** [hirosystems/explorer#793]
Initially thought was wallet nonce suggestion error
https://github.com/hirosystems/stacks-wallet-web/issues/2590

Turns out it's not wallet suggestion error after checking API endpoint, 
issue maybe with the Explorer page display of the default nonce, it appears to be off by 1 nonce. 
OF a **sponsored tx**. Cannot be sure if it happens on a other types or typical tx. 

To repro:
https://byzantion.xyz/mints/airdropticket
    click mint page, connect wallet, click mint button, confirm tx.
    then you can check in your Explorer history that sponsored tx suggested 1 more nonce than it should, creating nonce gap.

**Comment by beguene** [comment]
Fixed in https://github.com/hirosystems/explorer/pull/806
