### ISSUE TITLE
Add values in USD and BTC

### ISSUE THREAD

**Issue by andresgalante** [hirosystems/explorer#799]
This is a wide effort, the end goal is to show values on BTC and USD whenever we show a STX value. It includes:

- [x] #819
- [x] On the header show the current BTC and STX value, examples are [OnStack Explorer](https://app.onstacks.com/explorer) or [Stacking.club](https://stacking.club/)
- [x] #852
- [x] #853
- [x] #854

I am probably missing other places, please add them to the list.

*important:* Do not tackle these as a bundle, create sub-issues from this one and let's ship one by one.

**Comment by andresgalante** [comment]
Since we are using the free tier API from CoinGecko we need to add attribution. I suggest a line in the footer that reads "BTC and STX prices provided by CoinGecko" with a link to CoinGecko.

**Comment by rafaelcr** [comment]
Hi @andresgalante @leahjlou thanks for these great additions... could it be possible to also add the USD price into a transaction's events? For example here: https://explorer.stacks.co/txid/0xf0e9c3e0080e38963374d683054511d28ad7671ea361cee2ef3026d236395dd4?chain=mainnet
With the event USD quote, you could easily see how much was paid to buy that NFT. I think that would be very useful.

There's no specific reason for this ask, btw, just thought it would be a nice to have 👍
