### ISSUE TITLE
Rethink the Stacking progress indicator UX to support extended stacking

### ISSUE THREAD

**Issue by markmhendrickson** [hirosystems/explorer#804]
It seems for direct Stacking we show a "Stacking progress" unit with circular indicator:

<img width="353" alt="Screen Shot 2022-08-04 at 17 03 55" src="https://user-images.githubusercontent.com/28991/182881442-58b200fa-3797-45a6-891e-20152b1a38d1.png">

But we don't do the same when STX are locked via delegation / pooling:

<img width="352" alt="Screen Shot 2022-08-04 at 17 03 58" src="https://user-images.githubusercontent.com/28991/182881449-5cb9823d-9203-41b4-bf01-2d186b062eef.png">

It'd be helpful to display this indicator in the latter case for users to judge how long it'll be until their STX unlock.

**Comment by andresgalante** [comment]
related to #297

**Comment by friedger** [comment]
With the new feature to extend stacking, the percentage can be confusing when it jumps from 50% to 25% or 0% or so.

**Comment by andresgalante** [comment]
Thanks @friedger I'll rename the issue to improve the UX to support extended stacking

**Comment by andresgalante** [comment]
I am closing this since we are working on a stacking page and a redesign
