### ISSUE TITLE
No transfer received

### ISSUE THREAD

**Issue by VGIS777** [hirosystems/explorer#814]
Good afternoon!

I tried to transfer 100 STX from blockchain.com  to binance.com.
STX has not been received by binance.
After that, I opened a new wallet Hiro Wallet

address details
https://explorer.stacks.co/address/SP3SS9PM2G1CVGYSKPG2XCY5FMFZV1MA0JWSNF0ET?utm_source=stacks-wallet&chain=mainnet

https://explorer.stacks.co/txid/0x02b02d91fcc06c96db9f0158ab433322f2a83aa3f6ef22cca04a51578ccfec6f?utm_source=stacks-wallet&chain=mainnet

99.9996 STX transfer
Sender address
SP3SS9PM2G1CVGYSKPG2XCY5FMFZV1MA0JWSNF0ET

Recipient
SP1P72Z3704VMT3DMHPP2CB8TGQWGDBHD3RPR9GZS

Transaction ID
0x02b02d91fcc06c96db9f0158ab433322f2a83aa3f6ef22cca04a51578ccfec6f

Tell me there is an opportunity to somehow return STX

Sincerely, Gennady Lemeshko

**Comment by andresgalante** [comment]
Hi @VGIS777 

There isn't anything I can do to help, I suggest opening an issue on blockchain.com and binance.com.

Having said that I noticed that you didn't a memo which is required by binance to identify to tx.
