### ISSUE TITLE
Clicking on a tx in the address page on testnet redirects back to mainnet 

### ISSUE THREAD

**Issue by pseudozach** [hirosystems/explorer#829]
**Describe the bug**
Clicking on a tx in the address page on testnet redirects back to mainnet 

**To Reproduce**
1. Go to [any address page on testnet](https://explorer.stacks.co/address/ST1N7CZP8YR2HA3ZWKSF64CR77ZTSHEKW6NTN1DXZ?chain=testnet)
2. Click on any tx in the list
3. page redirects to mainnet and user has to pick testnet again from navbar network menu

**Expected behavior**
explorer should stay on testnet

**Screenshots**
![Screen Shot 2022-08-22 at 4 17 12 PM](https://user-images.githubusercontent.com/3731591/186035841-85e8775d-6ae1-4422-9b5d-c7a01122803f.png)

**Desktop (please complete the following information):**
macOS, brave browser

**Additional context**
I think it's due to the tx link being `https://explorer.stacks.co/txid/0x7144702f8a38305236f9fa6c774b88d81e583316d5ceef36e1319dcb41f4f3fa?chain=https%3A%2F%2Fstacks-node-api.testnet.stacks.co`
normally tx link should end with `?chain=testnet` but since it's incorrect for some reason it falls back to mainnet as default network.

imo need to find out when this bug was introduced that adds the `chain=api address` and revert it.

**Comment by andresgalante** [comment]
I can reproduce this on any list item on testnet, not only txid
