### ISSUE TITLE
Add tooltips to navigation icons in Sandbox

### ISSUE THREAD

**Issue by leahjlou** [hirosystems/explorer#851]
As a new user, I have found navigation within the Sandbox page to be unclear because the menu is only icons. Tutorials & docs published by Hiro reference these sections by name, but you cannot see the name until you click on the icon to navigate to that section.

I think it would be useful to display tooltips on hover or focus of the nav icons. The tooltips would read: "Write & Deploy", "Call a Contract", "Send STX", and "STX Faucet".

Alternatively, the navigation could be changed to display the text at all times, but that would require larger UI changes to the page, and I think tooltips would be a quick improvement.

![Screen Shot 2022-09-06 at 4 50 32 PM](https://user-images.githubusercontent.com/2423414/188754376-f2223450-7011-4436-99b4-b51de849129f.png)

**Comment by tuanphungcz** [comment]
> As a new user, I have found navigation within the Sandbox page to be unclear because the menu is only icons. Tutorials & docs published by Hiro reference these sections by name, but you cannot see the name until you click on the icon to navigate to that section.
> 
> I think it would be useful to display tooltips on hover or focus of the nav icons. The tooltips would read: "Write & Deploy", "Call a Contract", "Send STX", and "STX Faucet".
> 
> Alternatively, the navigation could be changed to display the text at all times, but that would require larger UI changes to the page, and I think tooltips would be a quick improvement.
> 
> ![Screen Shot 2022-09-06 at 4 50 32 PM](https://user-images.githubusercontent.com/2423414/188754376-f2223450-7011-4436-99b4-b51de849129f.png)

Yeah, I actually had an issue with understanding what the icons means when I tried Sanbox the first time 😄

I just opened the PR with a fix https://github.com/hirosystems/explorer/pull/911 🚀
