### ISSUE TITLE
This page is missing. during clarinet devnet

### ISSUE THREAD

**Issue by unclemantis** [hirosystems/explorer#860]
When I visit the local node I get this.
![image](https://user-images.githubusercontent.com/718701/190072898-168fc008-e28e-4b6b-8266-780408e5ab22.png)

after a few seconds I get this
![image](https://user-images.githubusercontent.com/718701/190072930-ca292195-9a68-43cc-b8d3-94c6fd3d92b3.png)

When I refresh the page everything is fine for a few seconds and then I get the page missing error again. What gives?

**Comment by unclemantis** [comment]
I left it alone for a few minutes and refreshed the page. Got the screen below, as you can see devnet is still running and updating. Not sure what the deal is with explorer.

![image](https://user-images.githubusercontent.com/718701/190073483-094bede7-9f7a-4b7f-aaf6-2a5dba519855.png)

**Comment by unclemantis** [comment]
![image](https://user-images.githubusercontent.com/718701/190073719-606099af-56c7-4a50-b7f5-8a13a40fb712.png)

![image](https://user-images.githubusercontent.com/718701/190073742-42cef3bb-600a-497d-aa4e-3b58c39f9771.png)

**Comment by andresgalante** [comment]
This is fixed
