### ISSUE TITLE
Wrongly display "This account hasn't executed a tx yet" - should have displayed "0"

### ISSUE THREAD

**Issue by Hero-Gamer** [hirosystems/explorer#863]
Testnet STX address: https://explorer.stacks.co/address/ST2E3P9B712YSFQF5BAAA2D5G6RC8RQ0WNB8CQKH1?chain=testnet

I'm in testnet, just created couple of more txs (nonce 1, nonce 2), my testnet address HAS previously made Nonce 0 tx, settled anchor 25 days ago. This one: https://explorer.stacks.co/txid/0x9271f70e5032637909a26fbb09d98bd5bd7c2b2e9dbdb66399bc3b767718293e?chain=testnet

But in the Testnet Explorer just how during the tx pending process, it was explorer was displaying 
**"This account hasn't executed a tx yet"** (but I 100% have executed Nonce 0 25 days ago... so in theory it should display "0")

I have seen this type of behavior before on **MAINNET** with other users when I was helping them, which I commented in #wallet channel in discord: https://discord.com/channels/621759717756370964/745197302255321108/1019983297004187699
I believe the user's transaction was BNS pre-order/registration related

Thanks.

**Comment by andresgalante** [comment]
Related to https://github.com/hirosystems/explorer/issues/878

**Comment by He1DAr** [comment]
nonce endpoint: https://stacks-node-api.testnet.stacks.co/extended/v1/address/ST2E3P9B712YSFQF5BAAA2D5G6RC8RQ0WNB8CQKH1/nonces (cc: @rafaelcr)

**Comment by rafaelcr** [comment]
@He1DAr I see this response which looks correct:
```
{
  "last_executed_tx_nonce": 3,
  "last_mempool_tx_nonce": null,
  "possible_next_nonce": 4,
  "detected_missing_nonces": []
}
```
Do you know the response it gave when this was happening?

**Comment by andresgalante** [comment]
I'll close this one in favor of https://github.com/hirosystems/explorer/issues/969
