### ISSUE TITLE
List STXBTC Price in the Explorer Header

### ISSUE THREAD

**Issue by brainharrington** [hirosystems/explorer#873]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Would like to see the STXBTC price listed along side BTCUSD and STXUSD

**Describe alternatives you've considered**
Currently I use a price app on my phone for this

**Additional context**
Pricing STX in sats and thinking about stacking in terms of sats flow per STX instead of as an APY I believe will help growth

**Comment by andresgalante** [comment]
This one is done :)

**Comment by brainharrington** [comment]
I still only see BTCUSD and STXUSD, is there a way for me to update or should I clear browser or something?
<img width="208" alt="Screen Shot 2023-06-22 at 8 16 03 AM" src="https://github.com/hirosystems/explorer/assets/37989507/90c08b0f-7292-44b1-b554-e8fc8e2b648d">
