### ISSUE TITLE
Show 0 USD when balance is 0STX 

### ISSUE THREAD

**Issue by andresgalante** [hirosystems/explorer#879]
<img width="342" alt="unknown" src="https://user-images.githubusercontent.com/1832037/193818186-b235c936-9a0c-4238-92d4-f8a970b4cfdb.png">

**Comment by shamim-io** [comment]
@andresgalante Is the change still needed ? If so, Shall I take up this issue?

**Comment by shamim-io** [comment]
@andresgalante I have raised a PR solving this issue. Kindly review it. Thanks!

**Comment by andresgalante** [comment]
Thanks @shamim-io , we'll get to it! 🙏
