### ISSUE TITLE
Virgin address not recognized in new wallet until it receives a token

### ISSUE THREAD

**Issue by marshallbtc** [hirosystems/explorer#882]
**Bug Description**
When a new user creates their Hiro wallet for the first time, the newly generated address is not recognized by the explorer. I found this to be problematic when helping a friend move STX from Okcoin into their Hiro web wallet for the first time. Okcoin will not allow a user to move funds to an address if it's not found to be valid by the Stacks Explorer.

**To Reproduce**
1. Use a Chrome or Brave browser
2. Sign out of your Hiro wallet, and create a new one
3. Copy your address and paste it into the explorer
4. Notice that the address is "Not found" and shows the message, "No principal found with address '<address>'"

**Expected behavior**
Upon pasting the new "virgin" address, the explorer should recognize that it is a valid address.

**Proposed Solution**
If a Stacks address matches the characteristics of a valid address, but the explorer doesn't find any transactions, there should not be an error message, but rather a different cautionary prompt that says something along the lines of "The address appears valid, but may not exist"
If it walks like an address, but hasn't talked like an address, then it might be an address.

**Desktop and Browser**
macOS Monterey Version 12.6
Brave browser
Version 1.43.89 Chromium: 105.0.5195.102 (Official Build) (x86_64)

**Additional context**
Perhaps this is not a bug, but rather a feature. If so, please advise, and I will share this with Okcoin so that they can improve the user experience on their end.

**Comment by Marshall-Jones-WLU** [comment]
This is the same as issue #544

**Comment by andresgalante** [comment]
I'll close it in favor of https://github.com/hirosystems/explorer/issues/544
