### ISSUE TITLE
Generate all transactions report in CSV

### ISSUE THREAD

**Issue by navisio** [hirosystems/explorer#886]
Hi, Is there a way to generate a CSV of all of my transactions on the STX blockchain, including my staking/farming transactions on AlexLab.co?
Many thanks,

**Comment by diwakergupta** [comment]
Does https://fatstx.github.io/ work for your needs? If so, please close this issue - thanks!

**Comment by andresgalante** [comment]
We've added this feature to the Explorer. Thanks for the suggestion!
