### ISSUE TITLE
Hiro stacking reward problem

### ISSUE THREAD

**Issue by sharp1907** [hirosystems/explorer#906]
Hello,

I run a stacking from cycle #41 to #46, for cycle #44, I did not receive the reward yet.

My Hiro wallet address is SP15ZEDV9HKJ33E0QZNCHCXMJD0KAQHDZ633V1JVY
and reward BTC address is 1H6MJWJkDaATHuyLUJGKV2TTF4o2CZYCik (Binance exchange)

I run a stacking in Hiro Wallet for Desktop version.

I need to know what happened for rewarding process in #44 cycle.

Can you check this matter in your earliest convenience?

And, please send me the result to my e-mail address, lgdf4088@hanmail.net.

If you need any other information, please let me know.

Thanks and best regards.

![Reward issue 2022 10 26](https://user-images.githubusercontent.com/107832270/198189186-a19ef45b-04df-4dc5-a555-aae99955f498.png)

**Comment by andresgalante** [comment]
This is not an Explorer related issue
