### ISSUE TITLE
In dark mode the sandbox input fields are black on black

### ISSUE THREAD

**Issue by whoabuddy** [hirosystems/explorer#916]
**Describe the bug**

If you access the sandbox with dark mode enabled,the input fields are all black on black, and you can only see what you typed by highlighting the text.

**To Reproduce**
1. Enable dark mode
2. Go to sandbox
3. Type into an input field

**Expected behavior**

Text color should be converted (inverted?) so that it's legible on the dark background.

**Screenshots**

Specifying a contract to query:

![Screenshot from 2022-11-11 06-05-05](https://user-images.githubusercontent.com/9038904/201347979-5e4449ea-d2bd-4873-af7d-a2af14160e5d.png)

![Screenshot from 2022-11-11 06-05-36](https://user-images.githubusercontent.com/9038904/201347981-93142582-7646-4ee9-9a4b-09e99f760c0d.png)

Specifying function parameters:

![Screenshot from 2022-11-11 06-06-02](https://user-images.githubusercontent.com/9038904/201347983-a9b74ebc-7db3-4d2d-b455-a994ed6d342a.png)

![Screenshot from 2022-11-11 06-06-30](https://user-images.githubusercontent.com/9038904/201347985-4145e84b-288f-436e-b41a-ace2ced7a338.png)

**Comment by wbnns** [comment]
Am also experiencing this issue

Browser: Firefox 106.0.4

Turning off dark mode to workaround

**Comment by wbnns** [comment]
@He1DAr Thanks for fixing :handshake:

**Comment by 0xBabo** [comment]
Not fixed on the parameters input form.

<img width="928" alt="Screenshot 2022-12-21 at 12 28 34 PM" src="https://user-images.githubusercontent.com/110633279/208997202-ff9163ab-8a0f-4179-a9b2-dc8a6ca6b996.png">

**Comment by wbnns** [comment]
Confirmed and reproduced issue as well. 
![image](https://user-images.githubusercontent.com/1130872/209119568-92931946-dd6e-4c53-90e5-a5defac81620.png)

Cc: @He1DAr

**Comment by whoabuddy** [comment]
Confirmed and reproduced here too

![image](https://user-images.githubusercontent.com/9038904/210854184-84835c1c-b9af-4f21-903b-dd437fbfa055.png)

Should this issue be re-opened @He1DAr ?
