### ISSUE TITLE
Use historical STX price

### ISSUE THREAD

**Issue by He1DAr** [hirosystems/explorer#917]
For completed transactions, we should surface historical STX $ value.

**Comment by andresgalante** [comment]
It'd be better if we can show both current and historical value. Etherscan shows the current value, and on hover, makes it clear that it is the current value and offers a click to show the historical value
![image](https://user-images.githubusercontent.com/1832037/201648537-9ee95f1e-7856-4a83-b9ac-76ddf4d1959a.png)
