### ISSUE TITLE
testnet

### ISSUE THREAD

**Issue by yankelevich1** [hirosystems/explorer#919]
**Describe the bug**

Transaction ID 
Address 
Block#  
Time stamp

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots or consol.log to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem here: 

does not send test stx tokens via google chrome hiro wallet, writes that there are not enough tokens.
through microsoft edge everything is ok

**Comment by yankelevich1** [comment]
does not send test stx tokens via google chrome hiro wallet, writes that there are not enough tokens.
through microsoft edge everything is ok

ST1TT3TCC5KS2DN8H462H944FK4RK0CYHEKTHDRM8 google chrome
ST3RWSBBGCT9B6A8D5N450XRK07D4PK6EEWB1ZF78 m edge

**Comment by yankelevich1** [comment]
Opera is also not sent

**Comment by 314159265359879** [comment]
> does not send test stx tokens via google chrome hiro wallet, writes that there are not enough tokens. through microsoft edge everything is ok
> 
> ST1TT3TCC5KS2DN8H462H944FK4RK0CYHEKTHDRM8 google chrome ST3RWSBBGCT9B6A8D5N450XRK07D4PK6EEWB1ZF78 m edge

Thanks for reporting! I think what you are seeing is related to the issues described here on the Hiro Wallet for web repo: https://github.com/hirosystems/stacks-wallet-web/issues/2898 
A fix has been made and is expected in the next release of the wallet (~today).
