### ISSUE TITLE
use clarity grammar and docs from clarity repo in code editor

### ISSUE THREAD

**Issue by He1DAr** [hirosystems/explorer#926]
https://github.com/hirosystems/clarity-repl/blob/1282a1e2d5a6d759e0df923f4bb30a13b27ea124/src/clarity/docs/mod.rs
https://github.com/hirosystems/clarinet/blob/develop/components/clarity-vscode/syntaxes/clarity.tmLanguage.json

**Comment by leahjlou** [comment]
PR is open for fetching the grammar, code completion is a little more complex.

Discussed w/ @hugocaillard an approach to create a `clarity-completion` JS package and publish it to NPM, which would include all the CompletionItems usable in Monaco. Will follow up on that in the future.
