### ISSUE TITLE
Explorer crashes when trying to display collectibles on a (BNS holding) contract

### ISSUE THREAD

**Issue by 314159265359879** [hirosystems/explorer#941]
**Describe the bug**
Explorer crashes when trying to display collectables on a contract
![image](https://user-images.githubusercontent.com/33360391/207296170-a349cc0b-f56b-4da4-9cbf-73f05a3e44bb.png)

Transaction ID 0xc3d60ca1b920c52005345a01ffdfe81e1015b22cd94ec909f9b573030f8374d6
Address SP34S9DQ11S34TTXF1NM7E913AA7KVQG3PTRXK2F9.bns-1670789313405-v1
Block#  #86785
[#766966](https://mempool.space/block/766966)
2 days ago
Time stamp

**To Reproduce**
1. Go to https://explorer.stacks.co/txid/0x8c87d8fa1c8b394d241a1bb06f008f59fb5df5a98752ac7a77406769f874bc4b?chain=mainnet
2. Click on Holdings --> Collectibles
3. See error (screenshot in first section including console)
Briefly this message is shown below, rest of the page remains blank with no way to go back: 

![image](https://user-images.githubusercontent.com/33360391/207296865-f35a1089-532d-44e1-9287-b5cdb0b17b3e.png)

**Expected behavior**
I would expect to see the tokens, atleast a BNS name. 

**Screenshots**
See above

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Brave 
 - Version 1.46.140

**Comment by andresgalante** [comment]
This one should be fixed. Thanks for the report!
