### ISSUE TITLE
Application error with unknown api node parameter

### ISSUE THREAD

**Issue by friedger** [hirosystems/explorer#961]
**Describe the bug**
An application error occurs when opening a link like https://explorer.stacks.co/blocks?chain=testnet&api=https://2-1-api.testnet.hiro.so and the network defined in the api parameter is unknown

**To Reproduce**
1. Go to https://explorer.stacks.co/blocks?chain=testnet&api=https://2-1-api.testnet.hiro.so
2. See error

**Expected behavior**
Add the api node to the list of networks, inform the user that a new network was added

**Console Ouput**
```
TypeError: c.C(...) is undefined
    m client.ts:96
    W use-search.ts:21
    K use-search.ts:87
    ut search-box.tsx:40
    React 10
    unstable_runWithPriority scheduler.production.min.js:18
    React 6
    ie index.js:467
    ie index.js:603
    e index.js:621
    s runtime.js:45
    _invoke runtime.js:274
    t runtime.js:97
    r _async_to_generator.js:23
    u _async_to_generator.js:12
    Z _async_to_generator.js:17
    Z _async_to_generator.js:9
    ce index.js:639
    ue index.js:612
    e index.js:751
    s runtime.js:45
    _invoke runtime.js:274
    t runtime.js:97
    r _async_to_generator.js:23
    u _async_to_generator.js:12
instrument.js:109:45
```

**Comment by andresgalante** [comment]
Can you help us with another example to troubleshoot it?

**Comment by friedger** [comment]
The key information is that "the network defined in the api parameter is unknown"
