### ISSUE TITLE
Don't convert `<=` to `≤` in contracts

### ISSUE THREAD

**Issue by obycode** [hirosystems/explorer#963]
**Describe the bug**
I think it is confusing to show `<=` as `≤` in Clarity code, because users might think that they need to type `≤` if they are looking at a contract in the explorer and copying parts of it. Note that it does correctly show up as `<=` if you copy and paste this character. Maybe this is just a personal preference, and if so, feel free to ignore and close this issue.

**To Reproduce**
1. Go to [the maimicoin-core-v2 contract](https://explorer.stacks.co/txid/SP1H1733V5MZ3SZ9XRW9FKYGEZT0JDGEB8Y634C7R.miamicoin-core-v2?chain=mainnet)
2. Scroll down to line 153
4. See `≤`

**Expected behavior**
Show `<=` as `<=`

**Screenshots**
<img width="274" alt="image" src="https://user-images.githubusercontent.com/1473715/213480060-543a3285-eff0-4d2f-bb10-ed126a81bace.png">

**Comment by whoabuddy** [comment]
I second this - if I copy and paste the character here it allows me to insert it into a contract in VSCode, but I also verified copying it from the explorer page does produce `<=`. It should show the source code as-is.

**Comment by shamim-io** [comment]
I think the has been resolved because I see `<=` in the code.

**Comment by obycode** [comment]
Agreed! 🎉
