### ISSUE TITLE
Explorer showing "This account hasn't executed a tx yet" when only nonce 0 transaction has been confirmed. 

### ISSUE THREAD

**Issue by 314159265359879** [hirosystems/explorer#969]
**Describe the bug**
See screenshot
![image](https://user-images.githubusercontent.com/33360391/213888052-158c3dee-1351-47e1-8546-5dd7c3f9aa58.png)

Transaction ID 
not relevant will show on any address with a single transaction confirmed

**To Reproduce**
1. Go to create new account
2. Send single transaction with nonce 0
3. Wait for it to get confirmed in an anchor block go to address on the explorer
4. See error: at line four: **Last executed tx nonce: "This account hasn't executed a tx yet"**

**Expected behavior**
Should read "This account has executed it's first transaction" or show a 0:
![image](https://user-images.githubusercontent.com/33360391/213887380-f3e788b6-988c-4aca-96b8-7502ed9a6d71.png)

**Comment by 314159265359879** [comment]
@andresgalante I see this was removed from the board. Does it mean it isn't prioritized?
It is confusing and makes troubleshooting harder. Hero Gamer and I would love to see this fixed.

**Comment by andresgalante** [comment]
We aren't using the "Explorer" board any more, now we are using the "Explorer Board".

**Comment by harrybasra95** [comment]
Hey @andresgalante , I think the issue is in the [address-summary.jsx](https://github.dev/hirosystems/explorer/blob/f6ee4eee16a130d0742bf643935c86b74c6453a4/src/features/address-page/address-summary.tsx#L42-L43) page 

![Image](https://github.com/hirosystems/explorer/assets/20265606/99087564-7e0b-4c17-9f72-9fb6dead1698)

Here when lastExecutedTxNonce is 0 it fails the OR check and second value gets shown.
We can simple change this to 

`  <Value>
                  {lastExecutedTxNonce === null ? "This account hasn't executed a tx yet" : lastExecutedTxNonce}
</Value>`

**Comment by harrybasra95** [comment]
Hey @andresgalante @314159265359879  any updates?

**Comment by 314159265359879** [comment]
@harrybasra95 although I do not have an update here, I do appreciate you looking into the cause of the issue!

**Comment by andresgalante** [comment]
@harrybasra95 would you like to take a stab at trying to solve this issue?

**Comment by harrybasra95** [comment]
Sure

**Comment by harrybasra95** [comment]
@andresgalante It's been resolved already in PR #1139.

You can check from the following link - https://explorer.hiro.so/address/ST2GRSPAZVWE8YW7MKJENFJG3KNBKVZMH66SG9DCZ?chain=testnet

To test this I created a new account and had only one outgoing transaction. In the "Last executed tx nonce" column, it's showing 0.

**Comment by andresgalante** [comment]
Thanks @harrybasra95  🙏  this is awesome! we'll review it soon
