### ISSUE TITLE
Replace Stacks UI with Chakra UI

### ISSUE THREAD

**Issue by He1DAr** [hirosystems/explorer#971]

**Comment by whoabuddy** [comment]
I've tested out Chakra a few times and like the simplicity, literally bookmarked these resources today in case they're helpful:

- https://chakra-templates.dev/
- https://github.com/chakra-ui/awesome-chakra-ui
- https://choc-ui.com/

**Comment by pradel** [comment]
Saw the discussion so just a small note, it looks like chakra is not compatible with server components if you planned to use them :) https://chakra-ui.com/getting-started/nextjs-guide

**Comment by andresgalante** [comment]
This has been done :)

**Comment by whoabuddy** [comment]
Looks great! :heart:
