### ISSUE TITLE
STX supply shows "100.38% is unlocked"

### ISSUE THREAD

**Issue by 314159265359879** [hirosystems/explorer#973]
Front page of the explorer:
![image](https://user-images.githubusercontent.com/33360391/214655807-3e86c992-6ee7-40dc-98b7-5be9c6dadfb5.png)

It can't exceed 100% ;-)

**Comment by fluidvoice** [comment]
Perhaps the reason is the API is returning more unlocked STX than the total amount of STX

`https://stacks-node-api.mainnet.stacks.co/extended/v1/stx_supply`
returns

```
{
  "unlocked_percent": "100.38",
  "total_stx": "1352464600.000000",
  "unlocked_stx": "1357667771.425424",
  "block_height": 92728
}
```

**Comment by 314159265359879** [comment]
I noticed someone saying all unlocks have succeeded but that is not the case. There are still addresses with unlocks such as this one, so perhaps `total-supply` in this API is off?:
https://explorer.stacks.co/address/SMPE609M949ERBAATR32V701XYZ3J09CRP8QGSFT?chain=mainnet

From chain analysis:
First ~two years after Stacks 1.0 launch had a lot of unlocks (~30 M per month)
then a year of almost no unlocks (~1 M per month, that year just passed)
Then 2 more years of some unlocks (~3M per month)

Here is a list of the addresses, they all start with "SM" indicating multisig wallets:
`
STX   Address | Amount | Block
-- | -- | --
SM02ENSM1ZD4EKE6D3AB0JXTJMH7N4DPK733G27X | 13,888,888,888 | 243612
SM0FBQM0B0M1NTF8PE96FGPSXECDRD0YY3WJBECM | 13,888,888,888 | 243612
SM10B79PD3DN2XRBVBJWZ3QJ7SETV4ZGRH932H7BB | 13,888,888,888 | 243612
SM10JM5Z6YV9VFWKWD95Q34QPDTAJ83H0RGJHZZTR | 13,888,888,888 | 243612
SM11M6VMKSSW7TCERW2WERT52A5VF95PSK3SS4JMR | 13,888,888,888 | 243612
SM11WG8D1KF3K6S7RK6Y3RET38A2ERS3PYHRE08RC | 13,888,888,888 | 243612
SM12APCFJM8CEGC5FZMKD8EDHW4TQ8RCJD17B48YH | 13,888,888,888 | 243612
SM12WSR4RS455TJRT7RGNWRG4Y7QXEH8Y8X262Q9 | 13,888,888,888 | 243612
SM132F6Z8GXSHNF5JQW9RKJ4FYPZBN7QD8RVBQ24C | 13,888,888,888 | 243612
SM132WBPXH7WX6YXN5RY9AZKNX8WSYZN79YHSEKSZ | 13,888,888,888 | 243612
SM134H42XHC5B1VT5P4EP6VAYKBQ3V2594NC04EZR | 13,888,888,888 | 243612
SM13KQ31KQ4QGTXTC3CP709YENW2VAE5KSVPF5DSR | 13,888,888,888 | 243612
SM13KWC112MWQ3RXYM3G7NRSVM29KN3X4Z67BEHWC | 13,888,888,888 | 243612
SM151ENM0ZP6V7P1FDP51AQYYDYNB5S9ECP7BFH8R | 13,888,888,888 | 243612
SM15H0A2XH7AXD9B9D56SQV5NJZB2ECSWHQVXS2ZV | 13,888,888,888 | 243612
SM15WA9YNEXQ4BAD3CJ4CWS2WXSHH8X7TAFM289RK | 13,888,888,888 | 243612
SM15ZMWSXHWMKXBNV0E5ADVKP3GNCAR1GGTJ4015Y | 13,888,888,888 | 243612
SM1655NH9E4YQQGM8JYQHE6JEZJWG7RV27HM9ZCPG | 13,888,888,888 | 243612
SM16988WYZA10B9XR398BA7B0ESZ31QQY3AXCK4NV | 13,888,888,888 | 243612
SM16WKZXCF0Y87EZXWRZFS3EF39DYSEHT4HFHEJJ0 | 13,888,888,888 | 243612
SM1811XEFECGZN9K567Z63D9QZHQ7VN921P96YRT0 | 13,888,888,888 | 243612
SM184FZMGFK3VHWHDCXA7KVENARZQEC7PX9S0YBKW | 13,888,888,888 | 243612
SM18XYT8V0948TZXQMTGS0K77KNKSHRRYPB3G6W6M | 13,888,888,888 | 243612
SM195HAZQZNY4HSS4MJKZG803WW9RVX4J2C62Z8SV | 13,888,888,888 | 243612
...see attachment for the rest
`
[addresses-stx-unlockBlock.txt](https://github.com/hirosystems/explorer/files/10503744/addresses-stx-unlockBlock.txt)

**Comment by fluidvoice** [comment]
Interestingly, Coinbase is pulling the same value returned for **'unlocked_stx'** in the above URL for the **"current circulating supply"**. I think this is via Stacks code in the Coinbase Rosetta integration.

**Comment by fluidvoice** [comment]
> Then 2 more years of some unlocks (~3M per month)
> 
> Here is a list of the addresses, they all start with "SM" indicating multisig wallets:

Do you know what these are? Maybe Hiro employee lockups?

**Comment by rafaelcr** [comment]
thanks for flagging, I'm taking a look on the API side
