### ISSUE TITLE
100.40%  is unlocked

### ISSUE THREAD

**Issue by Cookie-Fevereiro** [hirosystems/explorer#975]
https://stacks-node-api.mainnet.stacks.co/extended/v1/stx_supply~

{
"unlocked_percent":
"100.40",
"total_stx":
"1352464600.000000",
"unlocked_stx":
"1357821188.461128",
"block_height":
92869
}

more unlocked that existing

**Comment by diwakergupta** [comment]
Duplicates #973.

Fix is in-review: hirosystems/stacks-blockchain-api#1531
