### ISSUE TITLE
smart contract deplyment

### ISSUE THREAD

**Issue by jstphani2** [hirosystems/explorer#983]
**Describe the bug**

Transaction ID  0x832c603154cfb0ad125e572c59323fd7214f6ce0da4c96105dedd9afcba52c0a
Address  SP2Q4CJX6NRK4FK5Q91SF6CEFZ4WVJ413A3DXZ6CE
Block#  776172
Time stamp

**To Reproduce**
1. Go to 'any payment gateway'
2. Click on 'payment'
3. Scroll down to 'after payment'
4. See error do that transaction again and there will be 2 transactions in pending now

**Expected behavior**

**Screenshots**
If applicable, add screenshots or consol.log to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] windows
 - Browser [e.g. chrome, safari] chrome

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem here:

**Comment by andresgalante** [comment]
I don't understand this report, can you provide more details please?
