### ISSUE TITLE
Name not letting me register 

### ISSUE THREAD

**Issue by 0x3c37-1d1e** [hirosystems/explorer#989]
**Describe the bug**

I am experiencing an issue with a transaction, as it failed on the scan but still shows as pending on the website. Additionally, I am unable to order a new transaction.

Transaction ID 0xd6ced91b62e9bdf9929bf5ce2b004f0071bb288b1fd24ab490a1aa560069f6b0

**To Reproduce**
Not sure it's basically frozen for me. 

**Expected behavior**
It should allow me to refresh and retry.

**Screenshots**
If applicable, add screenshots or consol.log to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] new one for mac
 - Browser [e.g. chrome, safari] chrome
 - Version [e.g. 22] newest 

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem here:

**Comment by andresgalante** [comment]
tx 0xd6ced91b62e9bdf9929bf5ce2b004f0071bb288b1fd24ab490a1aa560069f6b0 failed.
