### ISSUE TITLE
Pre order stuck

### ISSUE THREAD

**Issue by mantacola** [hirosystems/explorer#995]
I submitted the pre order for below mentioned transaction ID. However my Gas fee was erroneously selected more than available balance. The transaction is stuck now and does not move ahead. I transferred more STX in the account but the transaction is not completing. 

Request you to please cancel the same. 
https://explorer.stacks.co/txid/637ff7b504b6c56cf25633e3ac9b73e7e578abc8d9464da471fde10ed3b652f9?chain=mainnet

**Describe the bug**

Transaction ID 0x637ff7b504b6c56cf25633e3ac9b73e7e578abc8d9464da471fde10ed3b652f9
Address  
Block#  
Time stamp

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots or consol.log to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem here:

**Comment by andresgalante** [comment]
Hi, this isn't an Explorer bug. Please ask for help on Discord
