### ISSUE TITLE
Add time-copy-button for blocks as it is available on transactions - improve view for mobile

### ISSUE THREAD

**Issue by 314159265359879** [hirosystems/explorer#997]
**Please review the existing enhancement issues at the link below before creating a new one to ensure you do not create a duplicate request.** 
![image](https://user-images.githubusercontent.com/33360391/219978423-a3905f95-0a67-43c1-97b5-8eb89ebadc18.png)

Hovering over the time when it was mined reveals detailed time, on transactions it will also show a button to copy that. 
![image](https://user-images.githubusercontent.com/33360391/219978551-ac89fcf4-e277-40bd-820c-6e2beb407f6e.png)

**Is your feature request related to a problem? Please describe.**
On mobile users are having trouble seeing the detailed time. Because they can't hover and there is no copy button. 

**Describe the solution you'd like**
Preferably on click the time expands to detailed time that way it works on mobile and desktop? 

**Describe alternatives you've considered**
Just the copy button would help too. 

**Additional context**
A user mentioned clicking the bitcoin block (anchorblock height), to find the confirmation time instead.

**Comment by andresgalante** [comment]
@He1DAr we can use a [hover media](https://drafts.csswg.org/mediaqueries/#hover) query and if a divide isn't able to hover, just show the full time stamp.
