### ISSUE TITLE
Improve clarity in Explorer what are "outgoing" vs "incoming" tx

### ISSUE THREAD

**Issue by Hero-Gamer** [hirosystems/explorer#998]
At current Explorer design, if you go in, you have no explanation of what icons means what type of tx. 
(mentioned the same to the wallet team: https://github.com/hirosystems/stacks-wallet-web/issues/3213 )

I'd guess the most two types of tx are what's leaving your wallet, and what's coming in. 
i.e. In & Out. 

As I mentioned in discord: https://discord.com/channels/621759717756370964/911531946738339900/1070343606407270400
1. These symbols aren't clear what they mean unless I actually think about it. There is no explanation on the page each symbol means either. 
2. Currently if I do it at a glance, all icons basically all look kind of the same no distinction, it's not easy to identify the most important items (which are the tokens in and out), could it be possible to add some color & text saying e.g.  IN (in green circle) OUT (in red circle)

![image](https://user-images.githubusercontent.com/92864860/219999903-93793804-f818-4eca-8c4c-0711de90ee52.png)

Will be great to see further improvement made re to distinction of the two main types of transaction so it is a much pleasant viewing and discovery experience.

**Comment by 314159265359879** [comment]
In the Hiro wallet negative numbers for outgoing funds are now used. I think that is quiet helpful. 

In accounting it is quiet common to make negative numbers red and positive numbers black. That could be considered in addition to the negative sign.

**Comment by chresko** [comment]
Also good for accessibility.

**Comment by andresgalante** [comment]
@andromeda995 Would you like to take a look at this one?

**Comment by andresgalante** [comment]
I'll close this issue since we'll be working on a redesign of the Explorer.
